INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation) VALUES
  (355, 10, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (886, 131, 'severe', 'Unknown', 'Auto-generated interaction'),
  (261, 2, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (999, 16, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (479, 139, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (843, 100, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (960, 79, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (767, 133, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (573, 124, 'low', 'Unknown', 'Auto-generated interaction'),
  (821, 46, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (286, 94, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (66, 100, 'severe', 'Unknown', 'Auto-generated interaction'),
  (577, 133, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (797, 14, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (912, 90, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (183, 99, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (904, 137, 'high', 'Unknown', 'Auto-generated interaction'),
  (253, 37, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (142, 23, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (11, 1, 'severe', 'Unknown', 'Auto-generated interaction'),
  (53, 147, 'low', 'Unknown', 'Auto-generated interaction'),
  (535, 106, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (851, 123, 'low', 'Additive effect', 'Auto-generated interaction'),
  (952, 43, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (182, 149, 'high', 'Unknown', 'Auto-generated interaction'),
  (975, 41, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (48, 110, 'low', 'Additive effect', 'Auto-generated interaction'),
  (395, 16, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (785, 86, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (948, 71, 'severe', 'Unknown', 'Auto-generated interaction'),
  (80, 1, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (50, 19, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (134, 40, 'severe', 'Unknown', 'Auto-generated interaction'),
  (516, 39, 'high', 'Additive effect', 'Auto-generated interaction'),
  (311, 115, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (369, 46, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (987, 12, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (750, 19, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (30, 29, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (35, 20, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (792, 17, 'high', 'Additive effect', 'Auto-generated interaction'),
  (302, 120, 'high', 'Unknown', 'Auto-generated interaction'),
  (886, 104, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (851, 14, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (254, 121, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (501, 138, 'high', 'Additive effect', 'Auto-generated interaction'),
  (348, 13, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (430, 8, 'high', 'Additive effect', 'Auto-generated interaction'),
  (934, 5, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (700, 107, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (58, 143, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (577, 99, 'severe', 'Unknown', 'Auto-generated interaction'),
  (390, 58, 'high', 'Additive effect', 'Auto-generated interaction'),
  (553, 71, 'severe', 'Unknown', 'Auto-generated interaction'),
  (114, 18, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (905, 15, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (610, 70, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (223, 68, 'high', 'Unknown', 'Auto-generated interaction'),
  (833, 42, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (707, 11, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (410, 44, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (519, 57, 'low', 'Unknown', 'Auto-generated interaction'),
  (121, 29, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (233, 117, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (467, 34, 'low', 'Additive effect', 'Auto-generated interaction'),
  (852, 40, 'low', 'Unknown', 'Auto-generated interaction'),
  (670, 106, 'low', 'Additive effect', 'Auto-generated interaction'),
  (680, 114, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (159, 62, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (113, 134, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (390, 105, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (816, 77, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (771, 108, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (807, 121, 'low', 'Unknown', 'Auto-generated interaction'),
  (84, 45, 'low', 'Additive effect', 'Auto-generated interaction'),
  (709, 30, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (975, 96, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (155, 110, 'high', 'Additive effect', 'Auto-generated interaction'),
  (31, 59, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (206, 91, 'high', 'Additive effect', 'Auto-generated interaction'),
  (178, 130, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (868, 110, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (344, 89, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (160, 47, 'high', 'Additive effect', 'Auto-generated interaction'),
  (71, 124, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (770, 65, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (604, 88, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (563, 146, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (40, 57, 'low', 'Unknown', 'Auto-generated interaction'),
  (807, 105, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (426, 77, 'high', 'Unknown', 'Auto-generated interaction'),
  (168, 123, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (460, 99, 'low', 'Unknown', 'Auto-generated interaction'),
  (414, 121, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (671, 30, 'low', 'Additive effect', 'Auto-generated interaction'),
  (123, 72, 'low', 'Additive effect', 'Auto-generated interaction'),
  (226, 38, 'high', 'Additive effect', 'Auto-generated interaction'),
  (424, 103, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (61, 59, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (111, 24, 'high', 'Unknown', 'Auto-generated interaction'),
  (20, 66, 'low', 'Additive effect', 'Auto-generated interaction'),
  (108, 142, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (779, 137, 'high', 'Additive effect', 'Auto-generated interaction'),
  (485, 29, 'high', 'Unknown', 'Auto-generated interaction'),
  (773, 30, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (343, 75, 'high', 'Additive effect', 'Auto-generated interaction'),
  (480, 144, 'high', 'Additive effect', 'Auto-generated interaction'),
  (317, 22, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (952, 46, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (342, 117, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (984, 60, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (106, 92, 'low', 'Additive effect', 'Auto-generated interaction'),
  (783, 49, 'high', 'Unknown', 'Auto-generated interaction'),
  (194, 129, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (652, 133, 'severe', 'Unknown', 'Auto-generated interaction'),
  (108, 6, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (885, 92, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (382, 146, 'low', 'Additive effect', 'Auto-generated interaction'),
  (538, 130, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (560, 71, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (383, 5, 'low', 'Unknown', 'Auto-generated interaction'),
  (446, 95, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (378, 88, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (252, 75, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (470, 4, 'low', 'Additive effect', 'Auto-generated interaction'),
  (679, 100, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (204, 114, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (52, 56, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (356, 127, 'low', 'Unknown', 'Auto-generated interaction'),
  (775, 34, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (424, 67, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (938, 55, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (952, 74, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (342, 54, 'low', 'Additive effect', 'Auto-generated interaction'),
  (73, 136, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (607, 89, 'severe', 'Unknown', 'Auto-generated interaction'),
  (122, 104, 'low', 'Unknown', 'Auto-generated interaction'),
  (804, 67, 'low', 'Additive effect', 'Auto-generated interaction'),
  (197, 70, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (898, 98, 'low', 'Unknown', 'Auto-generated interaction'),
  (653, 37, 'high', 'Unknown', 'Auto-generated interaction'),
  (33, 111, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (743, 85, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (551, 55, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (463, 39, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (907, 149, 'low', 'Additive effect', 'Auto-generated interaction'),
  (802, 49, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (5, 36, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (107, 146, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (446, 117, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (914, 30, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (975, 60, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (661, 57, 'high', 'Additive effect', 'Auto-generated interaction'),
  (109, 36, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (137, 58, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (81, 25, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (727, 24, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (496, 139, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (866, 71, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (201, 103, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (980, 11, 'high', 'Unknown', 'Auto-generated interaction'),
  (135, 1, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (357, 17, 'high', 'Unknown', 'Auto-generated interaction'),
  (945, 44, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (279, 62, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (598, 124, 'high', 'Additive effect', 'Auto-generated interaction'),
  (145, 61, 'high', 'Additive effect', 'Auto-generated interaction'),
  (803, 112, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (565, 56, 'high', 'Unknown', 'Auto-generated interaction'),
  (433, 5, 'high', 'Unknown', 'Auto-generated interaction'),
  (304, 53, 'severe', 'Unknown', 'Auto-generated interaction'),
  (511, 6, 'severe', 'Unknown', 'Auto-generated interaction'),
  (973, 30, 'high', 'Additive effect', 'Auto-generated interaction'),
  (16, 69, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (386, 53, 'high', 'Additive effect', 'Auto-generated interaction'),
  (299, 70, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (975, 53, 'severe', 'Unknown', 'Auto-generated interaction'),
  (111, 53, 'low', 'Unknown', 'Auto-generated interaction'),
  (947, 134, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (274, 146, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (934, 99, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (385, 3, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (868, 27, 'high', 'Additive effect', 'Auto-generated interaction'),
  (795, 132, 'low', 'Unknown', 'Auto-generated interaction'),
  (565, 149, 'low', 'Unknown', 'Auto-generated interaction'),
  (921, 109, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (190, 62, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (79, 109, 'high', 'Additive effect', 'Auto-generated interaction'),
  (277, 55, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (246, 64, 'severe', 'Unknown', 'Auto-generated interaction'),
  (677, 22, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (454, 115, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (89, 77, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (154, 17, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (970, 85, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (708, 29, 'high', 'Additive effect', 'Auto-generated interaction'),
  (939, 88, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (55, 111, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (742, 148, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (102, 34, 'severe', 'Unknown', 'Auto-generated interaction'),
  (110, 14, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (928, 132, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (234, 8, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (649, 12, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (680, 55, 'low', 'Additive effect', 'Auto-generated interaction'),
  (199, 19, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (344, 2, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (331, 147, 'severe', 'Unknown', 'Auto-generated interaction'),
  (767, 70, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (457, 52, 'low', 'Unknown', 'Auto-generated interaction'),
  (112, 6, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (897, 100, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (41, 46, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (593, 33, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (562, 29, 'low', 'Additive effect', 'Auto-generated interaction'),
  (416, 101, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (215, 114, 'low', 'Additive effect', 'Auto-generated interaction'),
  (713, 23, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (926, 115, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (518, 149, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (435, 113, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (123, 117, 'severe', 'Unknown', 'Auto-generated interaction'),
  (236, 98, 'low', 'Additive effect', 'Auto-generated interaction'),
  (164, 133, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (263, 148, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (235, 17, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (68, 44, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (888, 56, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (587, 132, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (585, 123, 'low', 'Additive effect', 'Auto-generated interaction'),
  (507, 100, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (79, 123, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (796, 94, 'low', 'Additive effect', 'Auto-generated interaction'),
  (978, 43, 'high', 'Unknown', 'Auto-generated interaction'),
  (225, 55, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (389, 56, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (102, 69, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (403, 102, 'severe', 'Unknown', 'Auto-generated interaction'),
  (670, 105, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (161, 8, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (206, 5, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (57, 6, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (419, 25, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (660, 72, 'severe', 'Unknown', 'Auto-generated interaction'),
  (811, 4, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (782, 104, 'high', 'Additive effect', 'Auto-generated interaction'),
  (544, 69, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (698, 145, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (509, 87, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (213, 23, 'high', 'Unknown', 'Auto-generated interaction'),
  (662, 17, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (237, 3, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (823, 53, 'high', 'Unknown', 'Auto-generated interaction'),
  (185, 76, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (854, 17, 'low', 'Additive effect', 'Auto-generated interaction'),
  (411, 23, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (138, 126, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (729, 92, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (940, 14, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (770, 24, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (581, 20, 'low', 'Unknown', 'Auto-generated interaction'),
  (707, 101, 'high', 'Unknown', 'Auto-generated interaction'),
  (963, 43, 'severe', 'Unknown', 'Auto-generated interaction'),
  (71, 58, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (325, 48, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (485, 56, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (552, 45, 'severe', 'Unknown', 'Auto-generated interaction'),
  (366, 14, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (846, 90, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (465, 44, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (576, 146, 'high', 'Additive effect', 'Auto-generated interaction'),
  (638, 46, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (300, 68, 'high', 'Additive effect', 'Auto-generated interaction'),
  (967, 85, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (354, 125, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (927, 129, 'high', 'Additive effect', 'Auto-generated interaction'),
  (682, 147, 'low', 'Additive effect', 'Auto-generated interaction'),
  (745, 40, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (423, 79, 'high', 'Unknown', 'Auto-generated interaction'),
  (339, 54, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (349, 57, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (777, 139, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (530, 29, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (320, 37, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (786, 68, 'high', 'Unknown', 'Auto-generated interaction'),
  (117, 100, 'low', 'Unknown', 'Auto-generated interaction'),
  (191, 64, 'low', 'Additive effect', 'Auto-generated interaction'),
  (917, 12, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (926, 143, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (499, 39, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (483, 133, 'low', 'Unknown', 'Auto-generated interaction'),
  (114, 85, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (304, 5, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (373, 112, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (229, 123, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (836, 68, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (548, 110, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (629, 67, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (923, 100, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (782, 123, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (737, 139, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (325, 108, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (537, 102, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (746, 47, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (325, 138, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (237, 57, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (976, 125, 'low', 'Additive effect', 'Auto-generated interaction'),
  (94, 114, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (323, 92, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (725, 17, 'low', 'Unknown', 'Auto-generated interaction'),
  (861, 129, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (804, 27, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (680, 55, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (116, 20, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (921, 147, 'low', 'Additive effect', 'Auto-generated interaction'),
  (186, 116, 'low', 'Unknown', 'Auto-generated interaction'),
  (981, 91, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (766, 7, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (176, 82, 'low', 'Additive effect', 'Auto-generated interaction'),
  (626, 124, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (388, 144, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (273, 75, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (48, 5, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (465, 125, 'high', 'Additive effect', 'Auto-generated interaction'),
  (423, 119, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (885, 137, 'high', 'Additive effect', 'Auto-generated interaction'),
  (672, 96, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (538, 140, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (507, 45, 'high', 'Unknown', 'Auto-generated interaction'),
  (127, 121, 'low', 'Unknown', 'Auto-generated interaction'),
  (797, 104, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (666, 133, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (38, 139, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (844, 129, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (720, 17, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (543, 101, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (234, 127, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (65, 21, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (386, 91, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (642, 131, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (111, 138, 'low', 'Additive effect', 'Auto-generated interaction'),
  (632, 91, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (454, 67, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (410, 138, 'low', 'Additive effect', 'Auto-generated interaction'),
  (992, 49, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (245, 17, 'severe', 'Unknown', 'Auto-generated interaction'),
  (375, 141, 'severe', 'Unknown', 'Auto-generated interaction'),
  (1, 133, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (437, 23, 'high', 'Additive effect', 'Auto-generated interaction'),
  (657, 73, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (255, 4, 'high', 'Additive effect', 'Auto-generated interaction'),
  (735, 117, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (633, 20, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (930, 115, 'low', 'Additive effect', 'Auto-generated interaction'),
  (869, 112, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (7, 129, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (796, 6, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (413, 84, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (757, 20, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (15, 14, 'high', 'Additive effect', 'Auto-generated interaction'),
  (712, 26, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (708, 136, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (186, 146, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (988, 100, 'severe', 'Unknown', 'Auto-generated interaction'),
  (233, 15, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (781, 41, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (176, 85, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (484, 28, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (8, 23, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (189, 125, 'low', 'Additive effect', 'Auto-generated interaction'),
  (391, 28, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (125, 106, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (743, 54, 'low', 'Unknown', 'Auto-generated interaction'),
  (510, 66, 'high', 'Unknown', 'Auto-generated interaction'),
  (534, 42, 'high', 'Additive effect', 'Auto-generated interaction'),
  (199, 120, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (859, 134, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (165, 79, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (457, 79, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (628, 19, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (667, 37, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (307, 43, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (904, 49, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (378, 70, 'high', 'Unknown', 'Auto-generated interaction'),
  (12, 53, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (438, 91, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (87, 27, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (259, 129, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (655, 34, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (94, 21, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (533, 139, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (281, 7, 'high', 'Unknown', 'Auto-generated interaction'),
  (561, 106, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (503, 17, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (620, 55, 'low', 'Additive effect', 'Auto-generated interaction'),
  (721, 138, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (621, 127, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (802, 20, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (251, 24, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (297, 79, 'high', 'Unknown', 'Auto-generated interaction'),
  (187, 102, 'high', 'Unknown', 'Auto-generated interaction'),
  (95, 81, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (120, 131, 'high', 'Unknown', 'Auto-generated interaction'),
  (929, 7, 'high', 'Additive effect', 'Auto-generated interaction'),
  (491, 93, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (618, 9, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (82, 6, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (445, 6, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (471, 106, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (147, 150, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (587, 145, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (318, 85, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (653, 48, 'high', 'Additive effect', 'Auto-generated interaction'),
  (594, 124, 'high', 'Unknown', 'Auto-generated interaction'),
  (366, 67, 'low', 'Unknown', 'Auto-generated interaction'),
  (452, 75, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (922, 90, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (191, 86, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (720, 39, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (787, 83, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (617, 76, 'high', 'Unknown', 'Auto-generated interaction'),
  (923, 69, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (918, 63, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (680, 64, 'high', 'Unknown', 'Auto-generated interaction'),
  (412, 101, 'low', 'Additive effect', 'Auto-generated interaction'),
  (546, 114, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (47, 111, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (15, 101, 'low', 'Unknown', 'Auto-generated interaction'),
  (666, 42, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (218, 123, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (10, 69, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (456, 98, 'high', 'Unknown', 'Auto-generated interaction'),
  (20, 84, 'high', 'Unknown', 'Auto-generated interaction'),
  (82, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (348, 18, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (355, 124, 'high', 'Additive effect', 'Auto-generated interaction'),
  (891, 78, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (908, 29, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (189, 11, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (404, 35, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (945, 101, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (980, 24, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (299, 13, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (11, 144, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (192, 60, 'high', 'Additive effect', 'Auto-generated interaction'),
  (602, 121, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (543, 49, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (668, 100, 'severe', 'Unknown', 'Auto-generated interaction'),
  (268, 29, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (151, 103, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (287, 83, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (957, 98, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (577, 64, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (705, 27, 'severe', 'Unknown', 'Auto-generated interaction'),
  (702, 144, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (92, 1, 'low', 'Unknown', 'Auto-generated interaction'),
  (708, 125, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (855, 113, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (595, 46, 'high', 'Unknown', 'Auto-generated interaction'),
  (669, 137, 'high', 'Unknown', 'Auto-generated interaction'),
  (202, 117, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (496, 125, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (537, 141, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (503, 132, 'low', 'Additive effect', 'Auto-generated interaction'),
  (523, 78, 'low', 'Unknown', 'Auto-generated interaction'),
  (670, 143, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (671, 115, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (851, 9, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (401, 77, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (729, 112, 'high', 'Unknown', 'Auto-generated interaction'),
  (355, 132, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (396, 139, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (105, 9, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (313, 70, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (30, 95, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (697, 117, 'low', 'Additive effect', 'Auto-generated interaction'),
  (325, 13, 'low', 'Unknown', 'Auto-generated interaction'),
  (52, 51, 'high', 'Additive effect', 'Auto-generated interaction'),
  (726, 96, 'low', 'Additive effect', 'Auto-generated interaction'),
  (954, 144, 'low', 'Additive effect', 'Auto-generated interaction'),
  (533, 114, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (658, 57, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (889, 67, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (430, 59, 'severe', 'Unknown', 'Auto-generated interaction'),
  (714, 82, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (114, 134, 'high', 'Unknown', 'Auto-generated interaction'),
  (271, 131, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (407, 77, 'high', 'Additive effect', 'Auto-generated interaction'),
  (870, 27, 'low', 'Additive effect', 'Auto-generated interaction'),
  (11, 47, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (204, 50, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (440, 87, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (231, 132, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (678, 149, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (995, 121, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (680, 121, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (857, 12, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (554, 134, 'high', 'Additive effect', 'Auto-generated interaction'),
  (691, 67, 'low', 'Unknown', 'Auto-generated interaction'),
  (758, 140, 'severe', 'Metabolism inhibition', 'Auto-generated interaction');
