INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation) VALUES
  (47, 12, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (229, 127, 'high', 'Unknown', 'Auto-generated interaction'),
  (926, 66, 'high', 'Additive effect', 'Auto-generated interaction'),
  (262, 125, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (567, 62, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (923, 23, 'high', 'Unknown', 'Auto-generated interaction'),
  (281, 96, 'high', 'Unknown', 'Auto-generated interaction'),
  (604, 108, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (306, 121, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (890, 33, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (455, 27, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (773, 116, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (948, 98, 'severe', 'Unknown', 'Auto-generated interaction'),
  (814, 86, 'low', 'Unknown', 'Auto-generated interaction'),
  (568, 57, 'high', 'Additive effect', 'Auto-generated interaction'),
  (886, 108, 'severe', 'Unknown', 'Auto-generated interaction'),
  (693, 47, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (717, 50, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (92, 77, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (20, 136, 'high', 'Additive effect', 'Auto-generated interaction'),
  (885, 86, 'low', 'Unknown', 'Auto-generated interaction'),
  (895, 124, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (131, 78, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (644, 123, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (28, 116, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (903, 40, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (490, 68, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (289, 79, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (929, 33, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (901, 11, 'severe', 'Unknown', 'Auto-generated interaction'),
  (655, 130, 'high', 'Additive effect', 'Auto-generated interaction'),
  (382, 131, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (560, 82, 'high', 'Additive effect', 'Auto-generated interaction'),
  (663, 97, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (673, 132, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (408, 125, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (58, 117, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (875, 104, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (350, 25, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (971, 13, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (3, 10, 'low', 'Unknown', 'Auto-generated interaction'),
  (971, 93, 'low', 'Additive effect', 'Auto-generated interaction'),
  (520, 125, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (260, 23, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (613, 84, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (490, 101, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (235, 84, 'high', 'Unknown', 'Auto-generated interaction'),
  (892, 72, 'high', 'Additive effect', 'Auto-generated interaction'),
  (600, 74, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (10, 59, 'high', 'Unknown', 'Auto-generated interaction'),
  (712, 54, 'low', 'Unknown', 'Auto-generated interaction'),
  (558, 51, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (130, 150, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (772, 121, 'high', 'Unknown', 'Auto-generated interaction'),
  (950, 97, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (815, 61, 'high', 'Unknown', 'Auto-generated interaction'),
  (845, 40, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (110, 111, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (138, 77, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (995, 27, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (74, 52, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (642, 123, 'high', 'Unknown', 'Auto-generated interaction'),
  (787, 40, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (352, 9, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (122, 45, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (103, 108, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (461, 1, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (299, 68, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (793, 83, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (593, 101, 'severe', 'Unknown', 'Auto-generated interaction'),
  (872, 10, 'low', 'Additive effect', 'Auto-generated interaction'),
  (13, 108, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (743, 81, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (211, 76, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (747, 32, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (348, 76, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (405, 35, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (226, 54, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (475, 77, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (840, 101, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (840, 141, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (330, 83, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (233, 96, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (129, 24, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (504, 53, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (204, 120, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (768, 99, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (81, 150, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (256, 131, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (852, 3, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (344, 92, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (198, 11, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (778, 77, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (840, 39, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (795, 47, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (165, 144, 'high', 'Additive effect', 'Auto-generated interaction'),
  (366, 94, 'low', 'Unknown', 'Auto-generated interaction'),
  (161, 30, 'high', 'Unknown', 'Auto-generated interaction'),
  (960, 59, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (35, 118, 'low', 'Unknown', 'Auto-generated interaction'),
  (380, 33, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (532, 123, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (932, 133, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (144, 149, 'high', 'Unknown', 'Auto-generated interaction'),
  (571, 52, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (442, 50, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (387, 63, 'high', 'Unknown', 'Auto-generated interaction'),
  (743, 46, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (649, 135, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (485, 134, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (233, 118, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (930, 86, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (91, 12, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (225, 122, 'severe', 'Unknown', 'Auto-generated interaction'),
  (50, 30, 'high', 'Unknown', 'Auto-generated interaction'),
  (167, 138, 'high', 'Unknown', 'Auto-generated interaction'),
  (91, 106, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (514, 55, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (409, 149, 'severe', 'Unknown', 'Auto-generated interaction'),
  (282, 26, 'high', 'Additive effect', 'Auto-generated interaction'),
  (140, 40, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (22, 122, 'low', 'Unknown', 'Auto-generated interaction'),
  (148, 49, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (147, 136, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (10, 114, 'low', 'Additive effect', 'Auto-generated interaction'),
  (424, 26, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (548, 150, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (987, 48, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (658, 104, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (334, 146, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (682, 74, 'high', 'Unknown', 'Auto-generated interaction'),
  (336, 90, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (900, 108, 'high', 'Additive effect', 'Auto-generated interaction'),
  (893, 10, 'low', 'Additive effect', 'Auto-generated interaction'),
  (171, 133, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (815, 119, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (713, 81, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (852, 68, 'low', 'Unknown', 'Auto-generated interaction'),
  (828, 37, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (681, 9, 'low', 'Unknown', 'Auto-generated interaction'),
  (799, 86, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (923, 35, 'low', 'Unknown', 'Auto-generated interaction'),
  (569, 100, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (133, 14, 'high', 'Additive effect', 'Auto-generated interaction'),
  (510, 30, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (642, 45, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (158, 19, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (176, 32, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (418, 121, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (320, 138, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (692, 108, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (731, 78, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (179, 67, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (693, 27, 'high', 'Additive effect', 'Auto-generated interaction'),
  (100, 102, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (937, 101, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (549, 105, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (692, 27, 'low', 'Unknown', 'Auto-generated interaction'),
  (840, 52, 'low', 'Additive effect', 'Auto-generated interaction'),
  (433, 93, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (960, 142, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (783, 73, 'low', 'Additive effect', 'Auto-generated interaction'),
  (794, 140, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (744, 3, 'low', 'Additive effect', 'Auto-generated interaction'),
  (373, 83, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (470, 72, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (948, 23, 'severe', 'Unknown', 'Auto-generated interaction'),
  (834, 80, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (157, 47, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (295, 124, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (306, 43, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (927, 76, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (701, 25, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (984, 60, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (286, 74, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (220, 30, 'high', 'Unknown', 'Auto-generated interaction'),
  (990, 62, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (177, 132, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (602, 125, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (883, 47, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (364, 115, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (265, 49, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (176, 59, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (193, 96, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (191, 84, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (812, 102, 'high', 'Additive effect', 'Auto-generated interaction'),
  (899, 139, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (979, 18, 'low', 'Additive effect', 'Auto-generated interaction'),
  (514, 148, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (221, 60, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (17, 55, 'severe', 'Unknown', 'Auto-generated interaction'),
  (307, 111, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (101, 6, 'high', 'Unknown', 'Auto-generated interaction'),
  (623, 8, 'high', 'Additive effect', 'Auto-generated interaction'),
  (165, 127, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (43, 14, 'low', 'Unknown', 'Auto-generated interaction'),
  (94, 41, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (822, 53, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (278, 4, 'low', 'Additive effect', 'Auto-generated interaction'),
  (729, 118, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (374, 74, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (443, 123, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (762, 135, 'high', 'Unknown', 'Auto-generated interaction'),
  (118, 78, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (917, 74, 'low', 'Unknown', 'Auto-generated interaction'),
  (860, 23, 'high', 'Unknown', 'Auto-generated interaction'),
  (697, 40, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (652, 136, 'high', 'Additive effect', 'Auto-generated interaction'),
  (744, 135, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (883, 57, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (259, 93, 'high', 'Unknown', 'Auto-generated interaction'),
  (521, 125, 'low', 'Unknown', 'Auto-generated interaction'),
  (351, 21, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (171, 8, 'low', 'Unknown', 'Auto-generated interaction'),
  (406, 27, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (840, 89, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (520, 53, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (522, 138, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (37, 140, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (562, 72, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (485, 50, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (289, 82, 'severe', 'Unknown', 'Auto-generated interaction'),
  (293, 71, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (475, 81, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (394, 129, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (474, 23, 'high', 'Additive effect', 'Auto-generated interaction'),
  (266, 53, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (78, 16, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (144, 89, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (959, 13, 'high', 'Unknown', 'Auto-generated interaction'),
  (19, 79, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (627, 142, 'low', 'Unknown', 'Auto-generated interaction'),
  (979, 144, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (802, 44, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (231, 106, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (863, 144, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (999, 61, 'low', 'Additive effect', 'Auto-generated interaction'),
  (434, 150, 'severe', 'Unknown', 'Auto-generated interaction'),
  (585, 148, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (406, 125, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (641, 50, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (120, 41, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (907, 19, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (410, 8, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (304, 98, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (344, 6, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (23, 140, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (708, 63, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (296, 31, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (887, 31, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (173, 31, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (668, 102, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (43, 64, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (750, 69, 'high', 'Additive effect', 'Auto-generated interaction'),
  (586, 105, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (995, 83, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (683, 41, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (523, 61, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (642, 68, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (37, 72, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (16, 34, 'high', 'Additive effect', 'Auto-generated interaction'),
  (129, 31, 'low', 'Unknown', 'Auto-generated interaction'),
  (543, 22, 'severe', 'Unknown', 'Auto-generated interaction'),
  (597, 76, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (821, 99, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (55, 135, 'high', 'Additive effect', 'Auto-generated interaction'),
  (855, 144, 'severe', 'Unknown', 'Auto-generated interaction'),
  (607, 106, 'severe', 'Unknown', 'Auto-generated interaction'),
  (87, 31, 'severe', 'Unknown', 'Auto-generated interaction'),
  (532, 95, 'severe', 'Unknown', 'Auto-generated interaction'),
  (294, 119, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (875, 51, 'low', 'Unknown', 'Auto-generated interaction'),
  (326, 4, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (491, 55, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (468, 3, 'high', 'Additive effect', 'Auto-generated interaction'),
  (675, 46, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (140, 30, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (998, 62, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (914, 61, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (285, 145, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (532, 40, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (529, 122, 'low', 'Additive effect', 'Auto-generated interaction'),
  (281, 69, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (1000, 35, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (451, 55, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (209, 45, 'low', 'Unknown', 'Auto-generated interaction'),
  (600, 29, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (28, 43, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (779, 100, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (790, 138, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (731, 55, 'low', 'Unknown', 'Auto-generated interaction'),
  (887, 131, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (596, 138, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (746, 94, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (433, 60, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (616, 60, 'high', 'Unknown', 'Auto-generated interaction'),
  (662, 39, 'low', 'Unknown', 'Auto-generated interaction'),
  (16, 84, 'low', 'Unknown', 'Auto-generated interaction'),
  (630, 130, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (853, 131, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (491, 138, 'high', 'Unknown', 'Auto-generated interaction'),
  (51, 68, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (50, 111, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (141, 82, 'high', 'Unknown', 'Auto-generated interaction'),
  (490, 79, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (385, 7, 'high', 'Additive effect', 'Auto-generated interaction'),
  (527, 102, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (904, 147, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (252, 143, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (938, 6, 'low', 'Unknown', 'Auto-generated interaction'),
  (884, 22, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (216, 114, 'low', 'Unknown', 'Auto-generated interaction'),
  (822, 50, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (49, 55, 'high', 'Unknown', 'Auto-generated interaction'),
  (707, 108, 'severe', 'Unknown', 'Auto-generated interaction'),
  (383, 147, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (48, 36, 'high', 'Unknown', 'Auto-generated interaction'),
  (185, 114, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (277, 55, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (54, 86, 'low', 'Additive effect', 'Auto-generated interaction'),
  (970, 131, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (668, 11, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (666, 7, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (421, 45, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (444, 132, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (726, 128, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (87, 40, 'severe', 'Unknown', 'Auto-generated interaction'),
  (131, 127, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (844, 100, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (313, 100, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (591, 81, 'high', 'Additive effect', 'Auto-generated interaction'),
  (60, 51, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (128, 25, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (38, 43, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (297, 22, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (823, 110, 'low', 'Unknown', 'Auto-generated interaction'),
  (182, 29, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (756, 104, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (731, 67, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (682, 125, 'low', 'Unknown', 'Auto-generated interaction'),
  (759, 139, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (284, 138, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (464, 33, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (934, 90, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (536, 38, 'low', 'Additive effect', 'Auto-generated interaction'),
  (821, 49, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (8, 33, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (590, 12, 'severe', 'Unknown', 'Auto-generated interaction'),
  (530, 48, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (176, 73, 'severe', 'Unknown', 'Auto-generated interaction'),
  (271, 18, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (36, 27, 'low', 'Additive effect', 'Auto-generated interaction'),
  (342, 116, 'high', 'Unknown', 'Auto-generated interaction'),
  (657, 27, 'high', 'Additive effect', 'Auto-generated interaction'),
  (1, 144, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (153, 134, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (618, 128, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (874, 147, 'low', 'Additive effect', 'Auto-generated interaction'),
  (161, 74, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (413, 145, 'high', 'Additive effect', 'Auto-generated interaction'),
  (567, 114, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (688, 82, 'high', 'Unknown', 'Auto-generated interaction'),
  (173, 148, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (110, 51, 'low', 'Additive effect', 'Auto-generated interaction'),
  (514, 125, 'high', 'Unknown', 'Auto-generated interaction'),
  (82, 116, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (902, 49, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (697, 17, 'low', 'Unknown', 'Auto-generated interaction'),
  (289, 106, 'low', 'Additive effect', 'Auto-generated interaction'),
  (833, 7, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (784, 63, 'high', 'Unknown', 'Auto-generated interaction'),
  (783, 140, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (823, 99, 'high', 'Additive effect', 'Auto-generated interaction'),
  (681, 125, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (269, 135, 'low', 'Additive effect', 'Auto-generated interaction'),
  (472, 50, 'high', 'Unknown', 'Auto-generated interaction'),
  (744, 84, 'severe', 'Unknown', 'Auto-generated interaction'),
  (764, 103, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (629, 126, 'severe', 'Unknown', 'Auto-generated interaction'),
  (664, 27, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (504, 19, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (102, 119, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (52, 24, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (34, 105, 'low', 'Unknown', 'Auto-generated interaction'),
  (777, 95, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (27, 136, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (78, 38, 'severe', 'Unknown', 'Auto-generated interaction'),
  (282, 115, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (576, 112, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (69, 30, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (272, 68, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (247, 146, 'severe', 'Unknown', 'Auto-generated interaction'),
  (787, 30, 'severe', 'Unknown', 'Auto-generated interaction'),
  (573, 89, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (463, 123, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (604, 134, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (564, 136, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (130, 142, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (116, 116, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (636, 140, 'severe', 'Unknown', 'Auto-generated interaction'),
  (393, 147, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (591, 15, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (20, 113, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (659, 32, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (459, 53, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (777, 20, 'low', 'Unknown', 'Auto-generated interaction'),
  (299, 59, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (14, 100, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (86, 105, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (191, 140, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (531, 112, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (430, 34, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (211, 116, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (256, 19, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (400, 61, 'low', 'Unknown', 'Auto-generated interaction'),
  (259, 130, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (325, 34, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (595, 75, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (219, 31, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (85, 70, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (771, 144, 'low', 'Additive effect', 'Auto-generated interaction'),
  (788, 6, 'high', 'Additive effect', 'Auto-generated interaction'),
  (69, 129, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (264, 81, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (192, 59, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (243, 81, 'low', 'Unknown', 'Auto-generated interaction'),
  (875, 42, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (626, 50, 'severe', 'Unknown', 'Auto-generated interaction'),
  (48, 20, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (851, 118, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (198, 68, 'high', 'Additive effect', 'Auto-generated interaction'),
  (153, 95, 'high', 'Unknown', 'Auto-generated interaction'),
  (563, 69, 'high', 'Additive effect', 'Auto-generated interaction'),
  (528, 137, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (667, 41, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (818, 138, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (49, 29, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (196, 97, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (956, 26, 'low', 'Additive effect', 'Auto-generated interaction'),
  (187, 57, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (508, 149, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (839, 16, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (365, 60, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (806, 149, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (764, 145, 'low', 'Additive effect', 'Auto-generated interaction'),
  (626, 50, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (271, 133, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (5, 18, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (195, 35, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (662, 39, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (207, 103, 'low', 'Unknown', 'Auto-generated interaction'),
  (608, 7, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (53, 29, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (40, 29, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (3, 131, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (666, 47, 'high', 'Additive effect', 'Auto-generated interaction'),
  (715, 76, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (715, 44, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (958, 112, 'severe', 'Unknown', 'Auto-generated interaction'),
  (936, 88, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (539, 46, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (732, 142, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (902, 34, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (609, 138, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (214, 70, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (319, 135, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (464, 8, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (446, 70, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (763, 34, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (47, 78, 'high', 'Additive effect', 'Auto-generated interaction'),
  (303, 64, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (754, 102, 'severe', 'Unknown', 'Auto-generated interaction'),
  (968, 124, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (148, 51, 'low', 'Unknown', 'Auto-generated interaction'),
  (378, 103, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (575, 57, 'low', 'Additive effect', 'Auto-generated interaction'),
  (420, 3, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (844, 14, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (944, 17, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (811, 34, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (965, 44, 'high', 'Unknown', 'Auto-generated interaction'),
  (141, 10, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (339, 26, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (451, 17, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (779, 46, 'high', 'Additive effect', 'Auto-generated interaction'),
  (751, 91, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (560, 147, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (425, 12, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (234, 4, 'high', 'Additive effect', 'Auto-generated interaction'),
  (829, 54, 'high', 'Additive effect', 'Auto-generated interaction'),
  (938, 55, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (361, 45, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (403, 2, 'severe', 'Unknown', 'Auto-generated interaction'),
  (489, 30, 'high', 'Additive effect', 'Auto-generated interaction'),
  (284, 149, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (690, 130, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (766, 26, 'low', 'Unknown', 'Auto-generated interaction'),
  (654, 63, 'low', 'Additive effect', 'Auto-generated interaction'),
  (866, 25, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (68, 106, 'moderate', 'Unknown', 'Auto-generated interaction');
