INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation) VALUES
  (690, 22, 'low', 'Unknown', 'Auto-generated interaction'),
  (785, 139, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (776, 89, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (189, 111, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (743, 135, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (666, 102, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (503, 111, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (299, 119, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (578, 123, 'low', 'Additive effect', 'Auto-generated interaction'),
  (993, 5, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (196, 144, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (450, 112, 'low', 'Additive effect', 'Auto-generated interaction'),
  (159, 54, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (879, 35, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (702, 60, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (568, 84, 'low', 'Unknown', 'Auto-generated interaction'),
  (639, 69, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (984, 85, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (445, 111, 'severe', 'Unknown', 'Auto-generated interaction'),
  (890, 132, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (233, 14, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (374, 104, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (828, 150, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (969, 67, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (63, 58, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (10, 52, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (554, 106, 'high', 'Unknown', 'Auto-generated interaction'),
  (844, 14, 'low', 'Unknown', 'Auto-generated interaction'),
  (383, 137, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (514, 89, 'high', 'Additive effect', 'Auto-generated interaction'),
  (590, 13, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (460, 70, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (350, 33, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (585, 108, 'severe', 'Unknown', 'Auto-generated interaction'),
  (671, 46, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (129, 133, 'high', 'Unknown', 'Auto-generated interaction'),
  (599, 126, 'high', 'Unknown', 'Auto-generated interaction'),
  (862, 60, 'high', 'Additive effect', 'Auto-generated interaction'),
  (304, 46, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (489, 118, 'high', 'Unknown', 'Auto-generated interaction'),
  (341, 83, 'high', 'Additive effect', 'Auto-generated interaction'),
  (747, 47, 'high', 'Unknown', 'Auto-generated interaction'),
  (852, 128, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (348, 11, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (878, 67, 'low', 'Additive effect', 'Auto-generated interaction'),
  (932, 107, 'high', 'Unknown', 'Auto-generated interaction'),
  (998, 94, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (163, 92, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (439, 84, 'low', 'Additive effect', 'Auto-generated interaction'),
  (945, 121, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (563, 11, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (914, 6, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (434, 132, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (566, 45, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (183, 95, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (478, 137, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (593, 39, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (801, 9, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (374, 150, 'severe', 'Unknown', 'Auto-generated interaction'),
  (702, 4, 'low', 'Additive effect', 'Auto-generated interaction'),
  (216, 98, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (514, 16, 'high', 'Unknown', 'Auto-generated interaction'),
  (172, 136, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (818, 118, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (516, 144, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (735, 64, 'low', 'Unknown', 'Auto-generated interaction'),
  (731, 58, 'low', 'Unknown', 'Auto-generated interaction'),
  (665, 93, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (209, 102, 'low', 'Additive effect', 'Auto-generated interaction'),
  (265, 123, 'low', 'Unknown', 'Auto-generated interaction'),
  (473, 118, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (427, 101, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (811, 37, 'high', 'Additive effect', 'Auto-generated interaction'),
  (159, 97, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (487, 2, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (1000, 84, 'low', 'Unknown', 'Auto-generated interaction'),
  (853, 56, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (397, 118, 'low', 'Additive effect', 'Auto-generated interaction'),
  (84, 23, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (499, 96, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (376, 31, 'high', 'Unknown', 'Auto-generated interaction'),
  (832, 10, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (541, 107, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (19, 13, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (794, 146, 'severe', 'Unknown', 'Auto-generated interaction'),
  (140, 47, 'low', 'Unknown', 'Auto-generated interaction'),
  (140, 134, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (188, 137, 'low', 'Unknown', 'Auto-generated interaction'),
  (531, 46, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (5, 127, 'severe', 'Unknown', 'Auto-generated interaction'),
  (704, 111, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (623, 70, 'low', 'Unknown', 'Auto-generated interaction'),
  (887, 81, 'low', 'Additive effect', 'Auto-generated interaction'),
  (991, 64, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (419, 51, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (568, 53, 'high', 'Additive effect', 'Auto-generated interaction'),
  (92, 51, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (256, 99, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (107, 17, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (547, 51, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (706, 79, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (321, 143, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (391, 88, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (634, 123, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (981, 23, 'low', 'Additive effect', 'Auto-generated interaction'),
  (274, 52, 'low', 'Unknown', 'Auto-generated interaction'),
  (688, 103, 'low', 'Additive effect', 'Auto-generated interaction'),
  (131, 125, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (591, 54, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (279, 145, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (908, 69, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (242, 1, 'low', 'Unknown', 'Auto-generated interaction'),
  (574, 109, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (112, 121, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (891, 148, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (958, 10, 'high', 'Unknown', 'Auto-generated interaction'),
  (49, 18, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (987, 140, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (974, 148, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (117, 5, 'high', 'Additive effect', 'Auto-generated interaction'),
  (560, 77, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (719, 78, 'low', 'Additive effect', 'Auto-generated interaction'),
  (641, 141, 'low', 'Unknown', 'Auto-generated interaction'),
  (693, 25, 'low', 'Unknown', 'Auto-generated interaction'),
  (437, 3, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (424, 104, 'severe', 'Unknown', 'Auto-generated interaction'),
  (244, 11, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (203, 116, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (517, 46, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (71, 107, 'high', 'Unknown', 'Auto-generated interaction'),
  (259, 94, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (16, 22, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (666, 70, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (696, 139, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (788, 1, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (583, 88, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (370, 106, 'severe', 'Unknown', 'Auto-generated interaction'),
  (624, 145, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (259, 111, 'severe', 'Unknown', 'Auto-generated interaction'),
  (747, 42, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (330, 6, 'high', 'Additive effect', 'Auto-generated interaction'),
  (518, 92, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (211, 44, 'low', 'Additive effect', 'Auto-generated interaction'),
  (403, 106, 'low', 'Unknown', 'Auto-generated interaction'),
  (75, 87, 'high', 'Additive effect', 'Auto-generated interaction'),
  (495, 84, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (832, 108, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (448, 53, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (424, 92, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (16, 97, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (222, 96, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (975, 1, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (485, 93, 'low', 'Additive effect', 'Auto-generated interaction'),
  (146, 114, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (34, 21, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (787, 103, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (522, 14, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (25, 101, 'low', 'Additive effect', 'Auto-generated interaction'),
  (525, 121, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (337, 23, 'high', 'Unknown', 'Auto-generated interaction'),
  (291, 74, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (921, 100, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (968, 115, 'low', 'Additive effect', 'Auto-generated interaction'),
  (798, 76, 'high', 'Unknown', 'Auto-generated interaction'),
  (346, 118, 'low', 'Unknown', 'Auto-generated interaction'),
  (922, 82, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (613, 125, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (729, 136, 'severe', 'Unknown', 'Auto-generated interaction'),
  (244, 5, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (789, 18, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (85, 52, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (175, 28, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (168, 89, 'high', 'Unknown', 'Auto-generated interaction'),
  (186, 22, 'high', 'Additive effect', 'Auto-generated interaction'),
  (226, 143, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (734, 13, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (460, 124, 'low', 'Additive effect', 'Auto-generated interaction'),
  (270, 24, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (694, 150, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (814, 125, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (47, 139, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (849, 99, 'high', 'Unknown', 'Auto-generated interaction'),
  (623, 80, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (615, 123, 'low', 'Unknown', 'Auto-generated interaction'),
  (68, 22, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (692, 79, 'severe', 'Unknown', 'Auto-generated interaction'),
  (652, 134, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (219, 91, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (487, 28, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (82, 135, 'low', 'Unknown', 'Auto-generated interaction'),
  (87, 22, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (884, 50, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (17, 70, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (360, 11, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (681, 61, 'severe', 'Unknown', 'Auto-generated interaction'),
  (205, 108, 'low', 'Additive effect', 'Auto-generated interaction'),
  (928, 148, 'low', 'Additive effect', 'Auto-generated interaction'),
  (247, 110, 'high', 'Unknown', 'Auto-generated interaction'),
  (125, 57, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (655, 106, 'severe', 'Unknown', 'Auto-generated interaction'),
  (698, 144, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (659, 36, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (240, 101, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (156, 47, 'low', 'Unknown', 'Auto-generated interaction'),
  (311, 104, 'high', 'Additive effect', 'Auto-generated interaction'),
  (325, 134, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (457, 26, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (215, 71, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (948, 19, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (92, 18, 'severe', 'Unknown', 'Auto-generated interaction'),
  (692, 105, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (262, 72, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (21, 55, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (18, 135, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (78, 97, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (928, 57, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (241, 42, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (33, 121, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (655, 115, 'severe', 'Unknown', 'Auto-generated interaction'),
  (690, 150, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (343, 34, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (192, 148, 'high', 'Unknown', 'Auto-generated interaction'),
  (755, 10, 'low', 'Additive effect', 'Auto-generated interaction'),
  (331, 28, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (194, 56, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (589, 8, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (541, 68, 'low', 'Additive effect', 'Auto-generated interaction'),
  (460, 138, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (212, 65, 'low', 'Additive effect', 'Auto-generated interaction'),
  (669, 9, 'low', 'Unknown', 'Auto-generated interaction'),
  (983, 145, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (254, 78, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (170, 85, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (515, 27, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (352, 91, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (162, 129, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (678, 80, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (204, 2, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (629, 59, 'high', 'Unknown', 'Auto-generated interaction'),
  (100, 48, 'low', 'Additive effect', 'Auto-generated interaction'),
  (14, 102, 'low', 'Unknown', 'Auto-generated interaction'),
  (486, 1, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (857, 81, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (610, 105, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (711, 5, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (529, 45, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (530, 40, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (406, 1, 'high', 'Additive effect', 'Auto-generated interaction'),
  (976, 131, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (118, 57, 'low', 'Additive effect', 'Auto-generated interaction'),
  (181, 136, 'severe', 'Unknown', 'Auto-generated interaction'),
  (68, 72, 'low', 'Unknown', 'Auto-generated interaction'),
  (879, 86, 'high', 'Additive effect', 'Auto-generated interaction'),
  (977, 18, 'severe', 'Unknown', 'Auto-generated interaction'),
  (917, 71, 'low', 'Additive effect', 'Auto-generated interaction'),
  (325, 150, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (849, 61, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (137, 101, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (269, 41, 'severe', 'Unknown', 'Auto-generated interaction'),
  (698, 67, 'high', 'Additive effect', 'Auto-generated interaction'),
  (455, 123, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (86, 121, 'high', 'Unknown', 'Auto-generated interaction'),
  (568, 49, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (3, 54, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (356, 42, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (525, 112, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (609, 22, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (810, 35, 'high', 'Unknown', 'Auto-generated interaction'),
  (188, 46, 'low', 'Additive effect', 'Auto-generated interaction'),
  (615, 67, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (775, 26, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (249, 66, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (18, 51, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (776, 47, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (851, 59, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (495, 80, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (120, 28, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (8, 46, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (550, 80, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (567, 59, 'severe', 'Unknown', 'Auto-generated interaction'),
  (202, 98, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (693, 128, 'low', 'Unknown', 'Auto-generated interaction'),
  (263, 55, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (178, 90, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (6, 3, 'high', 'Additive effect', 'Auto-generated interaction'),
  (173, 95, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (107, 61, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (246, 5, 'low', 'Unknown', 'Auto-generated interaction'),
  (240, 44, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (644, 76, 'low', 'Additive effect', 'Auto-generated interaction'),
  (34, 141, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (501, 111, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (541, 99, 'high', 'Additive effect', 'Auto-generated interaction'),
  (911, 32, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (6, 88, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (786, 114, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (187, 9, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (831, 100, 'high', 'Unknown', 'Auto-generated interaction'),
  (723, 117, 'low', 'Additive effect', 'Auto-generated interaction'),
  (508, 87, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (416, 69, 'high', 'Additive effect', 'Auto-generated interaction'),
  (562, 65, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (357, 110, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (872, 25, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (482, 2, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (588, 64, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (900, 143, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (260, 145, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (719, 92, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (480, 90, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (982, 73, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (105, 99, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (59, 111, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (124, 111, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (59, 110, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (618, 4, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (627, 22, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (873, 10, 'low', 'Additive effect', 'Auto-generated interaction'),
  (347, 121, 'severe', 'Unknown', 'Auto-generated interaction'),
  (138, 124, 'low', 'Additive effect', 'Auto-generated interaction'),
  (110, 146, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (836, 66, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (984, 115, 'severe', 'Unknown', 'Auto-generated interaction'),
  (372, 64, 'high', 'Unknown', 'Auto-generated interaction'),
  (689, 46, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (840, 89, 'low', 'Unknown', 'Auto-generated interaction'),
  (743, 31, 'high', 'Unknown', 'Auto-generated interaction'),
  (276, 33, 'high', 'Unknown', 'Auto-generated interaction'),
  (145, 57, 'low', 'Unknown', 'Auto-generated interaction'),
  (582, 130, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (894, 82, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (304, 103, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (635, 95, 'high', 'Unknown', 'Auto-generated interaction'),
  (7, 119, 'high', 'Additive effect', 'Auto-generated interaction'),
  (566, 83, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (356, 140, 'severe', 'Unknown', 'Auto-generated interaction'),
  (743, 11, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (154, 61, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (854, 58, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (245, 69, 'high', 'Additive effect', 'Auto-generated interaction'),
  (444, 117, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (364, 31, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (907, 72, 'high', 'Unknown', 'Auto-generated interaction'),
  (79, 44, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (224, 41, 'high', 'Additive effect', 'Auto-generated interaction'),
  (634, 49, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (964, 44, 'high', 'Additive effect', 'Auto-generated interaction'),
  (465, 12, 'severe', 'Unknown', 'Auto-generated interaction'),
  (411, 111, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (911, 70, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (36, 45, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (820, 112, 'severe', 'Unknown', 'Auto-generated interaction'),
  (403, 95, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (88, 24, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (407, 108, 'severe', 'Unknown', 'Auto-generated interaction'),
  (606, 99, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (924, 61, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (45, 38, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (43, 56, 'high', 'Additive effect', 'Auto-generated interaction'),
  (846, 117, 'high', 'Additive effect', 'Auto-generated interaction'),
  (904, 87, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (930, 86, 'low', 'Additive effect', 'Auto-generated interaction'),
  (656, 43, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (124, 46, 'high', 'Unknown', 'Auto-generated interaction'),
  (374, 146, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (330, 88, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (464, 33, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (440, 110, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (609, 125, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (559, 136, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (555, 66, 'high', 'Additive effect', 'Auto-generated interaction'),
  (882, 15, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (102, 79, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (773, 79, 'severe', 'Unknown', 'Auto-generated interaction'),
  (137, 120, 'high', 'Unknown', 'Auto-generated interaction'),
  (457, 61, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (558, 7, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (151, 113, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (75, 41, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (516, 116, 'severe', 'Unknown', 'Auto-generated interaction'),
  (158, 23, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (458, 58, 'low', 'Unknown', 'Auto-generated interaction'),
  (612, 3, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (289, 143, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (97, 22, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (578, 59, 'low', 'Unknown', 'Auto-generated interaction'),
  (271, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (438, 14, 'high', 'Unknown', 'Auto-generated interaction'),
  (437, 51, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (866, 148, 'severe', 'Unknown', 'Auto-generated interaction'),
  (716, 130, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (664, 57, 'high', 'Unknown', 'Auto-generated interaction'),
  (108, 139, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (813, 118, 'severe', 'Unknown', 'Auto-generated interaction'),
  (518, 13, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (840, 32, 'high', 'Unknown', 'Auto-generated interaction'),
  (762, 1, 'severe', 'Unknown', 'Auto-generated interaction'),
  (210, 15, 'severe', 'Unknown', 'Auto-generated interaction'),
  (134, 34, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (446, 104, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (64, 16, 'severe', 'Unknown', 'Auto-generated interaction'),
  (930, 63, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (764, 18, 'severe', 'Unknown', 'Auto-generated interaction'),
  (865, 16, 'severe', 'Unknown', 'Auto-generated interaction'),
  (165, 57, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (825, 125, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (163, 7, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (195, 141, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (371, 86, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (820, 145, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (550, 1, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (506, 10, 'severe', 'Unknown', 'Auto-generated interaction'),
  (46, 30, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (7, 61, 'severe', 'Unknown', 'Auto-generated interaction'),
  (835, 121, 'severe', 'Unknown', 'Auto-generated interaction'),
  (558, 6, 'severe', 'Unknown', 'Auto-generated interaction'),
  (11, 36, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (690, 141, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (389, 92, 'high', 'Unknown', 'Auto-generated interaction'),
  (529, 52, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (10, 98, 'high', 'Additive effect', 'Auto-generated interaction'),
  (993, 104, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (527, 104, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (101, 6, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (288, 116, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (507, 66, 'low', 'Unknown', 'Auto-generated interaction'),
  (534, 140, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (125, 79, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (985, 114, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (438, 146, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (665, 106, 'severe', 'Unknown', 'Auto-generated interaction'),
  (474, 137, 'high', 'Additive effect', 'Auto-generated interaction'),
  (463, 62, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (499, 39, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (780, 31, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (263, 111, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (319, 121, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (315, 5, 'high', 'Unknown', 'Auto-generated interaction'),
  (929, 4, 'severe', 'Unknown', 'Auto-generated interaction'),
  (361, 101, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (490, 60, 'high', 'Additive effect', 'Auto-generated interaction'),
  (430, 82, 'severe', 'Unknown', 'Auto-generated interaction'),
  (666, 79, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (579, 96, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (504, 47, 'low', 'Unknown', 'Auto-generated interaction'),
  (293, 34, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (428, 106, 'high', 'Unknown', 'Auto-generated interaction'),
  (354, 25, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (285, 97, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (316, 67, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (213, 11, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (350, 36, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (840, 47, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (204, 138, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (123, 149, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (316, 113, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (336, 21, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (139, 16, 'low', 'Unknown', 'Auto-generated interaction'),
  (203, 65, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (433, 134, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (767, 39, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (567, 131, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (695, 5, 'low', 'Additive effect', 'Auto-generated interaction'),
  (615, 62, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (371, 103, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (86, 113, 'low', 'Additive effect', 'Auto-generated interaction'),
  (107, 68, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (842, 125, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (702, 75, 'high', 'Unknown', 'Auto-generated interaction'),
  (923, 95, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (741, 89, 'high', 'Additive effect', 'Auto-generated interaction'),
  (69, 150, 'high', 'Unknown', 'Auto-generated interaction'),
  (471, 21, 'high', 'Unknown', 'Auto-generated interaction'),
  (21, 134, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (601, 85, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (229, 123, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (696, 29, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (376, 67, 'low', 'Additive effect', 'Auto-generated interaction'),
  (468, 109, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (52, 132, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (841, 109, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (3, 56, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (764, 15, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (738, 40, 'low', 'Unknown', 'Auto-generated interaction'),
  (216, 83, 'high', 'Unknown', 'Auto-generated interaction'),
  (133, 1, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (863, 139, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (639, 9, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (326, 9, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (114, 50, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (46, 37, 'high', 'Additive effect', 'Auto-generated interaction'),
  (26, 150, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (373, 41, 'high', 'Unknown', 'Auto-generated interaction'),
  (285, 5, 'high', 'Unknown', 'Auto-generated interaction'),
  (432, 116, 'severe', 'Unknown', 'Auto-generated interaction'),
  (203, 39, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (236, 38, 'low', 'Additive effect', 'Auto-generated interaction'),
  (618, 113, 'low', 'Unknown', 'Auto-generated interaction'),
  (366, 33, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (74, 110, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction');
