INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation) VALUES
  (878, 136, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (470, 39, 'low', 'Unknown', 'Auto-generated interaction'),
  (285, 41, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (628, 92, 'severe', 'Unknown', 'Auto-generated interaction'),
  (708, 114, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (714, 50, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (502, 58, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (7, 118, 'high', 'Additive effect', 'Auto-generated interaction'),
  (982, 78, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (22, 111, 'severe', 'Unknown', 'Auto-generated interaction'),
  (509, 13, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (856, 62, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (295, 13, 'severe', 'Unknown', 'Auto-generated interaction'),
  (475, 13, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (189, 25, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (918, 47, 'high', 'Unknown', 'Auto-generated interaction'),
  (829, 73, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (953, 57, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (282, 24, 'high', 'Unknown', 'Auto-generated interaction'),
  (930, 125, 'severe', 'Unknown', 'Auto-generated interaction'),
  (10, 33, 'high', 'Unknown', 'Auto-generated interaction'),
  (273, 144, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (412, 66, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (532, 144, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (635, 48, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (520, 39, 'high', 'Additive effect', 'Auto-generated interaction'),
  (719, 143, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (144, 138, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (234, 119, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (820, 21, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (616, 14, 'high', 'Unknown', 'Auto-generated interaction'),
  (96, 68, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (85, 73, 'high', 'Unknown', 'Auto-generated interaction'),
  (476, 31, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (723, 142, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (781, 62, 'low', 'Unknown', 'Auto-generated interaction'),
  (139, 127, 'high', 'Unknown', 'Auto-generated interaction'),
  (905, 51, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (713, 132, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (989, 55, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (530, 139, 'high', 'Additive effect', 'Auto-generated interaction'),
  (504, 102, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (728, 53, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (915, 1, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (245, 106, 'low', 'Additive effect', 'Auto-generated interaction'),
  (909, 56, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (875, 40, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (806, 91, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (905, 38, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (466, 85, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (779, 33, 'high', 'Unknown', 'Auto-generated interaction'),
  (335, 72, 'low', 'Additive effect', 'Auto-generated interaction'),
  (14, 63, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (746, 96, 'low', 'Unknown', 'Auto-generated interaction'),
  (259, 78, 'high', 'Additive effect', 'Auto-generated interaction'),
  (941, 39, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (164, 62, 'high', 'Additive effect', 'Auto-generated interaction'),
  (496, 138, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (302, 121, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (852, 78, 'high', 'Unknown', 'Auto-generated interaction'),
  (429, 4, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (882, 102, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (467, 1, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (672, 6, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (570, 4, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (701, 107, 'low', 'Additive effect', 'Auto-generated interaction'),
  (608, 10, 'high', 'Additive effect', 'Auto-generated interaction'),
  (706, 135, 'high', 'Additive effect', 'Auto-generated interaction'),
  (283, 123, 'high', 'Unknown', 'Auto-generated interaction'),
  (330, 146, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (282, 100, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (866, 88, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (308, 130, 'severe', 'Unknown', 'Auto-generated interaction'),
  (777, 64, 'severe', 'Unknown', 'Auto-generated interaction'),
  (684, 43, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (244, 50, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (548, 147, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (559, 85, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (333, 72, 'severe', 'Unknown', 'Auto-generated interaction'),
  (304, 128, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (386, 64, 'severe', 'Unknown', 'Auto-generated interaction'),
  (575, 65, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (64, 126, 'severe', 'Unknown', 'Auto-generated interaction'),
  (312, 74, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (769, 113, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (573, 22, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (229, 41, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (147, 4, 'severe', 'Unknown', 'Auto-generated interaction'),
  (490, 122, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (297, 115, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (565, 30, 'high', 'Additive effect', 'Auto-generated interaction'),
  (789, 76, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (217, 136, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (606, 109, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (927, 3, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (738, 51, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (857, 25, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (655, 24, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (32, 74, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (627, 90, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (148, 101, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (387, 113, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (103, 99, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (467, 149, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (418, 110, 'high', 'Unknown', 'Auto-generated interaction'),
  (564, 57, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (185, 17, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (165, 132, 'high', 'Unknown', 'Auto-generated interaction'),
  (419, 53, 'low', 'Additive effect', 'Auto-generated interaction'),
  (589, 7, 'high', 'Unknown', 'Auto-generated interaction'),
  (167, 118, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (679, 19, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (947, 39, 'high', 'Unknown', 'Auto-generated interaction'),
  (209, 25, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (354, 126, 'high', 'Unknown', 'Auto-generated interaction'),
  (239, 16, 'high', 'Additive effect', 'Auto-generated interaction'),
  (872, 83, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (536, 142, 'high', 'Unknown', 'Auto-generated interaction'),
  (291, 66, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (708, 68, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (755, 129, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (15, 66, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (520, 92, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (607, 105, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (110, 15, 'low', 'Additive effect', 'Auto-generated interaction'),
  (517, 39, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (381, 31, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (671, 136, 'high', 'Unknown', 'Auto-generated interaction'),
  (81, 52, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (428, 63, 'low', 'Unknown', 'Auto-generated interaction'),
  (111, 17, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (112, 132, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (559, 98, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (577, 42, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (369, 32, 'high', 'Additive effect', 'Auto-generated interaction'),
  (13, 95, 'severe', 'Unknown', 'Auto-generated interaction'),
  (768, 8, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (972, 100, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (808, 149, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (178, 86, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (729, 32, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (582, 146, 'low', 'Additive effect', 'Auto-generated interaction'),
  (35, 137, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (794, 69, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (341, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (950, 134, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (426, 115, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (686, 26, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (202, 13, 'low', 'Unknown', 'Auto-generated interaction'),
  (323, 48, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (423, 93, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (168, 29, 'severe', 'Unknown', 'Auto-generated interaction'),
  (16, 79, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (174, 13, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (633, 147, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (451, 6, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (144, 103, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (34, 75, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (809, 129, 'low', 'Additive effect', 'Auto-generated interaction'),
  (93, 150, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (543, 114, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (48, 45, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (386, 59, 'severe', 'Unknown', 'Auto-generated interaction'),
  (372, 148, 'severe', 'Unknown', 'Auto-generated interaction'),
  (726, 147, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (571, 33, 'low', 'Unknown', 'Auto-generated interaction'),
  (958, 124, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (440, 65, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (839, 62, 'high', 'Additive effect', 'Auto-generated interaction'),
  (610, 58, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (161, 38, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (222, 124, 'severe', 'Unknown', 'Auto-generated interaction'),
  (442, 130, 'low', 'Additive effect', 'Auto-generated interaction'),
  (264, 113, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (934, 3, 'severe', 'Unknown', 'Auto-generated interaction'),
  (397, 117, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (79, 92, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (529, 59, 'low', 'Unknown', 'Auto-generated interaction'),
  (940, 50, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (963, 79, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (443, 5, 'low', 'Unknown', 'Auto-generated interaction'),
  (434, 106, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (296, 142, 'low', 'Additive effect', 'Auto-generated interaction'),
  (340, 126, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (221, 112, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (500, 69, 'severe', 'Unknown', 'Auto-generated interaction'),
  (537, 87, 'high', 'Unknown', 'Auto-generated interaction'),
  (314, 1, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (298, 115, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (168, 121, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (752, 69, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (587, 82, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (698, 98, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (390, 8, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (521, 77, 'high', 'Unknown', 'Auto-generated interaction'),
  (979, 18, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (690, 128, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (965, 142, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (597, 8, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (921, 11, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (318, 149, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (93, 63, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (154, 96, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (178, 91, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (810, 90, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (107, 129, 'high', 'Unknown', 'Auto-generated interaction'),
  (799, 12, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (277, 142, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (781, 113, 'high', 'Unknown', 'Auto-generated interaction'),
  (757, 57, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (4, 48, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (434, 106, 'high', 'Unknown', 'Auto-generated interaction'),
  (242, 144, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (217, 13, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (71, 50, 'low', 'Additive effect', 'Auto-generated interaction'),
  (214, 53, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (99, 94, 'low', 'Unknown', 'Auto-generated interaction'),
  (592, 2, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (77, 59, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (586, 32, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (804, 76, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (706, 72, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (786, 120, 'low', 'Unknown', 'Auto-generated interaction'),
  (794, 30, 'severe', 'Unknown', 'Auto-generated interaction'),
  (588, 118, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (995, 30, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (655, 6, 'low', 'Additive effect', 'Auto-generated interaction'),
  (959, 32, 'high', 'Additive effect', 'Auto-generated interaction'),
  (873, 36, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (708, 117, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (381, 18, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (602, 123, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (538, 125, 'severe', 'Unknown', 'Auto-generated interaction'),
  (277, 105, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (85, 99, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (957, 106, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (885, 37, 'severe', 'Unknown', 'Auto-generated interaction'),
  (317, 85, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (514, 9, 'low', 'Additive effect', 'Auto-generated interaction'),
  (426, 12, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (377, 42, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (630, 143, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (87, 120, 'low', 'Unknown', 'Auto-generated interaction'),
  (776, 123, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (692, 140, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (273, 49, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (209, 23, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (416, 32, 'low', 'Unknown', 'Auto-generated interaction'),
  (624, 77, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (209, 80, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (644, 94, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (550, 21, 'low', 'Additive effect', 'Auto-generated interaction'),
  (635, 131, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (211, 97, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (289, 133, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (283, 94, 'high', 'Additive effect', 'Auto-generated interaction'),
  (63, 88, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (31, 56, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (509, 48, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (695, 31, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (709, 126, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (892, 25, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (539, 40, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (426, 13, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (185, 87, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (679, 20, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (276, 112, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (846, 84, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (704, 78, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (479, 106, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (846, 144, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (411, 2, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (630, 89, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (676, 145, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (453, 144, 'low', 'Additive effect', 'Auto-generated interaction'),
  (626, 107, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (324, 103, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (157, 113, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (952, 135, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (386, 144, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (681, 147, 'severe', 'Unknown', 'Auto-generated interaction'),
  (678, 123, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (82, 39, 'low', 'Unknown', 'Auto-generated interaction'),
  (756, 39, 'severe', 'Unknown', 'Auto-generated interaction'),
  (430, 65, 'high', 'Unknown', 'Auto-generated interaction'),
  (589, 25, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (995, 110, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (487, 87, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (474, 139, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (522, 11, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (597, 144, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (362, 72, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (818, 114, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (353, 9, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (524, 98, 'low', 'Unknown', 'Auto-generated interaction'),
  (454, 105, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (412, 45, 'low', 'Additive effect', 'Auto-generated interaction'),
  (795, 133, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (730, 74, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (24, 24, 'high', 'Unknown', 'Auto-generated interaction'),
  (16, 72, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (339, 26, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (884, 77, 'high', 'Unknown', 'Auto-generated interaction'),
  (977, 97, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (779, 104, 'high', 'Unknown', 'Auto-generated interaction'),
  (570, 120, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (58, 53, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (453, 34, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (261, 103, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (824, 45, 'low', 'Unknown', 'Auto-generated interaction'),
  (568, 29, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (857, 132, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (346, 98, 'high', 'Additive effect', 'Auto-generated interaction'),
  (767, 96, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (814, 50, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (300, 14, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (247, 92, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (60, 117, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (355, 20, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (186, 116, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (59, 60, 'high', 'Additive effect', 'Auto-generated interaction'),
  (413, 21, 'low', 'Additive effect', 'Auto-generated interaction'),
  (230, 31, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (966, 109, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (533, 99, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (193, 66, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (946, 144, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (656, 87, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (347, 119, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (415, 150, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (596, 37, 'severe', 'Unknown', 'Auto-generated interaction'),
  (110, 95, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (806, 109, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (996, 62, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (17, 148, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (847, 80, 'low', 'Additive effect', 'Auto-generated interaction'),
  (512, 90, 'high', 'Unknown', 'Auto-generated interaction'),
  (633, 72, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (597, 48, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (246, 42, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (188, 40, 'high', 'Unknown', 'Auto-generated interaction'),
  (486, 40, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (367, 114, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (136, 98, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (883, 90, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (687, 148, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (567, 89, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (102, 61, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (498, 103, 'severe', 'Unknown', 'Auto-generated interaction'),
  (15, 106, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (153, 131, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (598, 6, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (47, 73, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (195, 8, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (336, 143, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (470, 79, 'low', 'Additive effect', 'Auto-generated interaction'),
  (771, 39, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (82, 14, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (1000, 87, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (83, 65, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (433, 102, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (105, 123, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (928, 16, 'low', 'Additive effect', 'Auto-generated interaction'),
  (819, 67, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (97, 61, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (39, 111, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (604, 5, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (827, 123, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (514, 36, 'severe', 'Unknown', 'Auto-generated interaction'),
  (32, 95, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (19, 69, 'low', 'Unknown', 'Auto-generated interaction'),
  (375, 123, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (212, 83, 'low', 'Additive effect', 'Auto-generated interaction'),
  (529, 87, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (195, 23, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (464, 70, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (259, 51, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (336, 74, 'high', 'Additive effect', 'Auto-generated interaction'),
  (514, 109, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (20, 12, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (314, 84, 'high', 'Additive effect', 'Auto-generated interaction'),
  (337, 58, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (487, 23, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (840, 18, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (682, 91, 'low', 'Additive effect', 'Auto-generated interaction'),
  (176, 7, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (87, 76, 'low', 'Unknown', 'Auto-generated interaction'),
  (700, 12, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (929, 25, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (959, 48, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (777, 136, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (571, 116, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (998, 5, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (47, 82, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (310, 50, 'high', 'Additive effect', 'Auto-generated interaction'),
  (838, 66, 'low', 'Unknown', 'Auto-generated interaction'),
  (290, 138, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (637, 66, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (278, 62, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (539, 104, 'low', 'Additive effect', 'Auto-generated interaction'),
  (623, 35, 'severe', 'Unknown', 'Auto-generated interaction'),
  (619, 149, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (485, 72, 'high', 'Unknown', 'Auto-generated interaction'),
  (515, 39, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (666, 114, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (514, 48, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (856, 41, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (976, 63, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (520, 79, 'high', 'Additive effect', 'Auto-generated interaction'),
  (467, 1, 'low', 'Additive effect', 'Auto-generated interaction'),
  (521, 103, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (633, 116, 'low', 'Additive effect', 'Auto-generated interaction'),
  (154, 72, 'high', 'Additive effect', 'Auto-generated interaction'),
  (461, 34, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (439, 29, 'low', 'Additive effect', 'Auto-generated interaction'),
  (471, 76, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (445, 18, 'high', 'Unknown', 'Auto-generated interaction'),
  (771, 22, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (96, 72, 'low', 'Additive effect', 'Auto-generated interaction'),
  (386, 138, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (663, 21, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (193, 80, 'low', 'Unknown', 'Auto-generated interaction'),
  (821, 108, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (101, 147, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (196, 57, 'high', 'Additive effect', 'Auto-generated interaction'),
  (460, 96, 'high', 'Additive effect', 'Auto-generated interaction'),
  (322, 20, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (805, 16, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (710, 23, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (157, 70, 'high', 'Additive effect', 'Auto-generated interaction'),
  (15, 133, 'low', 'Additive effect', 'Auto-generated interaction'),
  (564, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (156, 35, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (590, 79, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (724, 36, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (596, 67, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (174, 148, 'high', 'Additive effect', 'Auto-generated interaction'),
  (38, 54, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (538, 125, 'high', 'Additive effect', 'Auto-generated interaction'),
  (796, 72, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (605, 66, 'high', 'Additive effect', 'Auto-generated interaction'),
  (343, 87, 'high', 'Additive effect', 'Auto-generated interaction'),
  (614, 86, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (263, 84, 'high', 'Additive effect', 'Auto-generated interaction'),
  (874, 76, 'high', 'Additive effect', 'Auto-generated interaction'),
  (39, 28, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (693, 79, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (872, 140, 'low', 'Unknown', 'Auto-generated interaction'),
  (406, 13, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (625, 93, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (749, 114, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (339, 31, 'low', 'Additive effect', 'Auto-generated interaction'),
  (138, 61, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (305, 84, 'low', 'Additive effect', 'Auto-generated interaction'),
  (2, 74, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (387, 51, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (218, 59, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (408, 135, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (252, 45, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (386, 7, 'high', 'Unknown', 'Auto-generated interaction'),
  (892, 115, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (53, 141, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (247, 124, 'severe', 'Unknown', 'Auto-generated interaction'),
  (165, 15, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (679, 104, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (775, 140, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (784, 97, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (942, 54, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (114, 63, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (746, 59, 'low', 'Unknown', 'Auto-generated interaction'),
  (765, 99, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (710, 84, 'low', 'Unknown', 'Auto-generated interaction'),
  (314, 112, 'severe', 'Unknown', 'Auto-generated interaction'),
  (867, 109, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (729, 12, 'low', 'Additive effect', 'Auto-generated interaction'),
  (82, 118, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (796, 105, 'high', 'Additive effect', 'Auto-generated interaction'),
  (578, 38, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (938, 29, 'high', 'Additive effect', 'Auto-generated interaction'),
  (846, 138, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (734, 50, 'high', 'Unknown', 'Auto-generated interaction'),
  (691, 148, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (148, 120, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (449, 98, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (707, 99, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (975, 63, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (486, 92, 'severe', 'Unknown', 'Auto-generated interaction'),
  (343, 13, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (67, 7, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (706, 70, 'severe', 'Unknown', 'Auto-generated interaction'),
  (407, 136, 'low', 'Additive effect', 'Auto-generated interaction'),
  (850, 102, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (584, 67, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (245, 106, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (559, 119, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (276, 16, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (571, 150, 'severe', 'Unknown', 'Auto-generated interaction'),
  (831, 146, 'low', 'Unknown', 'Auto-generated interaction'),
  (817, 105, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (170, 146, 'high', 'Metabolism inhibition', 'Auto-generated interaction');
