INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation) VALUES
  (194, 99, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (436, 112, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (784, 27, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (776, 125, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (100, 98, 'severe', 'Unknown', 'Auto-generated interaction'),
  (265, 60, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (755, 88, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (922, 37, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (761, 84, 'low', 'Unknown', 'Auto-generated interaction'),
  (977, 80, 'high', 'Additive effect', 'Auto-generated interaction'),
  (213, 111, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (922, 139, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (496, 86, 'high', 'Additive effect', 'Auto-generated interaction'),
  (660, 76, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (525, 65, 'high', 'Unknown', 'Auto-generated interaction'),
  (258, 138, 'high', 'Additive effect', 'Auto-generated interaction'),
  (122, 65, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (188, 122, 'high', 'Unknown', 'Auto-generated interaction'),
  (408, 38, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (310, 122, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (431, 16, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (866, 65, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (635, 132, 'high', 'Unknown', 'Auto-generated interaction'),
  (625, 103, 'low', 'Additive effect', 'Auto-generated interaction'),
  (51, 6, 'high', 'Unknown', 'Auto-generated interaction'),
  (978, 74, 'high', 'Additive effect', 'Auto-generated interaction'),
  (302, 107, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (66, 28, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (481, 103, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (964, 9, 'high', 'Additive effect', 'Auto-generated interaction'),
  (566, 78, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (846, 143, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (43, 63, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (164, 132, 'high', 'Additive effect', 'Auto-generated interaction'),
  (581, 137, 'low', 'Additive effect', 'Auto-generated interaction'),
  (465, 25, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (687, 18, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (340, 94, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (284, 141, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (693, 3, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (553, 93, 'low', 'Unknown', 'Auto-generated interaction'),
  (801, 75, 'low', 'Unknown', 'Auto-generated interaction'),
  (523, 101, 'high', 'Unknown', 'Auto-generated interaction'),
  (964, 49, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (616, 94, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (692, 120, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (137, 89, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (23, 81, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (439, 103, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (600, 119, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (117, 63, 'low', 'Additive effect', 'Auto-generated interaction'),
  (63, 4, 'low', 'Unknown', 'Auto-generated interaction'),
  (404, 56, 'high', 'Additive effect', 'Auto-generated interaction'),
  (882, 41, 'low', 'Unknown', 'Auto-generated interaction'),
  (348, 60, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (858, 6, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (224, 71, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (649, 112, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (749, 18, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (250, 80, 'high', 'Additive effect', 'Auto-generated interaction'),
  (339, 37, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (285, 51, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (776, 119, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (376, 110, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (581, 28, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (825, 94, 'low', 'Additive effect', 'Auto-generated interaction'),
  (551, 77, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (182, 116, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (832, 139, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (383, 89, 'high', 'Additive effect', 'Auto-generated interaction'),
  (464, 110, 'high', 'Additive effect', 'Auto-generated interaction'),
  (278, 54, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (307, 44, 'high', 'Unknown', 'Auto-generated interaction'),
  (821, 77, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (723, 81, 'high', 'Additive effect', 'Auto-generated interaction'),
  (902, 145, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (372, 107, 'high', 'Additive effect', 'Auto-generated interaction'),
  (908, 82, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (138, 56, 'severe', 'Unknown', 'Auto-generated interaction'),
  (369, 1, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (477, 122, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (160, 59, 'severe', 'Unknown', 'Auto-generated interaction'),
  (354, 56, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (44, 103, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (709, 104, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (789, 116, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (571, 25, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (526, 72, 'low', 'Unknown', 'Auto-generated interaction'),
  (687, 28, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (167, 27, 'low', 'Unknown', 'Auto-generated interaction'),
  (198, 150, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (628, 84, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (785, 14, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (428, 73, 'high', 'Additive effect', 'Auto-generated interaction'),
  (846, 146, 'severe', 'Unknown', 'Auto-generated interaction'),
  (371, 149, 'low', 'Unknown', 'Auto-generated interaction'),
  (101, 38, 'high', 'Additive effect', 'Auto-generated interaction'),
  (255, 14, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (385, 125, 'low', 'Additive effect', 'Auto-generated interaction'),
  (257, 137, 'severe', 'Unknown', 'Auto-generated interaction'),
  (44, 93, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (63, 125, 'high', 'Additive effect', 'Auto-generated interaction'),
  (937, 80, 'high', 'Additive effect', 'Auto-generated interaction'),
  (582, 122, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (292, 120, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (801, 16, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (731, 27, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (27, 75, 'high', 'Unknown', 'Auto-generated interaction'),
  (650, 83, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (542, 25, 'high', 'Unknown', 'Auto-generated interaction'),
  (156, 148, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (578, 130, 'high', 'Additive effect', 'Auto-generated interaction'),
  (747, 144, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (672, 51, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (871, 49, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (374, 49, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (315, 102, 'low', 'Additive effect', 'Auto-generated interaction'),
  (757, 93, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (35, 79, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (328, 109, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (535, 55, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (51, 78, 'severe', 'Unknown', 'Auto-generated interaction'),
  (56, 13, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (482, 4, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (97, 78, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (603, 9, 'severe', 'Unknown', 'Auto-generated interaction'),
  (552, 90, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (788, 88, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (933, 135, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (889, 25, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (674, 72, 'high', 'Additive effect', 'Auto-generated interaction'),
  (863, 9, 'high', 'Unknown', 'Auto-generated interaction'),
  (12, 45, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (647, 76, 'severe', 'Unknown', 'Auto-generated interaction'),
  (53, 123, 'high', 'Unknown', 'Auto-generated interaction'),
  (39, 102, 'high', 'Additive effect', 'Auto-generated interaction'),
  (470, 2, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (269, 35, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (874, 77, 'low', 'Unknown', 'Auto-generated interaction'),
  (251, 136, 'high', 'Unknown', 'Auto-generated interaction'),
  (504, 142, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (719, 88, 'low', 'Unknown', 'Auto-generated interaction'),
  (749, 128, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (882, 85, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (271, 10, 'severe', 'Unknown', 'Auto-generated interaction'),
  (60, 130, 'high', 'Unknown', 'Auto-generated interaction'),
  (447, 79, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (384, 13, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (239, 5, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (829, 101, 'high', 'Unknown', 'Auto-generated interaction'),
  (105, 58, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (85, 12, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (509, 105, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (368, 142, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (413, 27, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (181, 143, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (712, 47, 'high', 'Additive effect', 'Auto-generated interaction'),
  (301, 35, 'low', 'Unknown', 'Auto-generated interaction'),
  (32, 89, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (406, 73, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (673, 51, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (921, 41, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (903, 114, 'high', 'Unknown', 'Auto-generated interaction'),
  (621, 64, 'low', 'Unknown', 'Auto-generated interaction'),
  (340, 120, 'low', 'Unknown', 'Auto-generated interaction'),
  (896, 34, 'high', 'Additive effect', 'Auto-generated interaction'),
  (717, 75, 'low', 'Additive effect', 'Auto-generated interaction'),
  (169, 133, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (914, 136, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (638, 4, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (938, 10, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (470, 59, 'high', 'Unknown', 'Auto-generated interaction'),
  (598, 113, 'high', 'Additive effect', 'Auto-generated interaction'),
  (481, 110, 'severe', 'Unknown', 'Auto-generated interaction'),
  (677, 132, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (444, 52, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (942, 54, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (860, 111, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (990, 37, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (784, 66, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (520, 112, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (142, 142, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (965, 24, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (161, 32, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (233, 44, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (803, 120, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (226, 129, 'severe', 'Unknown', 'Auto-generated interaction'),
  (383, 71, 'high', 'Additive effect', 'Auto-generated interaction'),
  (869, 86, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (122, 55, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (563, 127, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (98, 140, 'high', 'Unknown', 'Auto-generated interaction'),
  (38, 28, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (980, 4, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (733, 21, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (783, 76, 'low', 'Additive effect', 'Auto-generated interaction'),
  (291, 141, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (491, 42, 'low', 'Additive effect', 'Auto-generated interaction'),
  (692, 136, 'high', 'Unknown', 'Auto-generated interaction'),
  (506, 72, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (1000, 98, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (930, 33, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (847, 88, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (397, 102, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (292, 37, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (559, 103, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (841, 111, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (8, 36, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (9, 34, 'low', 'Unknown', 'Auto-generated interaction'),
  (874, 36, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (291, 141, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (292, 3, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (481, 100, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (55, 67, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (16, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (446, 30, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (975, 122, 'high', 'Additive effect', 'Auto-generated interaction'),
  (728, 85, 'high', 'Unknown', 'Auto-generated interaction'),
  (736, 69, 'high', 'Unknown', 'Auto-generated interaction'),
  (961, 116, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (748, 132, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (126, 72, 'low', 'Additive effect', 'Auto-generated interaction'),
  (278, 129, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (939, 4, 'low', 'Unknown', 'Auto-generated interaction'),
  (876, 90, 'severe', 'Unknown', 'Auto-generated interaction'),
  (943, 79, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (513, 9, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (202, 93, 'high', 'Additive effect', 'Auto-generated interaction'),
  (130, 114, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (638, 93, 'severe', 'Unknown', 'Auto-generated interaction'),
  (233, 137, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (472, 45, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (44, 77, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (594, 95, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (804, 106, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (481, 120, 'high', 'Additive effect', 'Auto-generated interaction'),
  (607, 80, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (69, 131, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (185, 72, 'low', 'Unknown', 'Auto-generated interaction'),
  (843, 2, 'high', 'Additive effect', 'Auto-generated interaction'),
  (80, 38, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (706, 142, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (640, 66, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (160, 128, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (736, 12, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (100, 138, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (734, 4, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (652, 106, 'low', 'Unknown', 'Auto-generated interaction'),
  (83, 38, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (96, 99, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (444, 99, 'high', 'Additive effect', 'Auto-generated interaction'),
  (984, 92, 'low', 'Additive effect', 'Auto-generated interaction'),
  (683, 30, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (160, 19, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (426, 107, 'low', 'Unknown', 'Auto-generated interaction'),
  (358, 113, 'high', 'Additive effect', 'Auto-generated interaction'),
  (271, 95, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (243, 50, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (326, 146, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (645, 126, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (570, 121, 'severe', 'Unknown', 'Auto-generated interaction'),
  (8, 80, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (780, 145, 'severe', 'Unknown', 'Auto-generated interaction'),
  (705, 20, 'severe', 'Unknown', 'Auto-generated interaction'),
  (627, 12, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (759, 23, 'low', 'Additive effect', 'Auto-generated interaction'),
  (291, 59, 'low', 'Additive effect', 'Auto-generated interaction'),
  (92, 95, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (496, 53, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (474, 31, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (608, 138, 'low', 'Additive effect', 'Auto-generated interaction'),
  (744, 90, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (534, 95, 'high', 'Unknown', 'Auto-generated interaction'),
  (146, 74, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (362, 145, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (815, 137, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (257, 133, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (481, 5, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (791, 98, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (68, 84, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (349, 44, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (72, 139, 'high', 'Unknown', 'Auto-generated interaction'),
  (912, 53, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (679, 89, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (537, 29, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (492, 124, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (456, 25, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (211, 96, 'low', 'Additive effect', 'Auto-generated interaction'),
  (769, 4, 'high', 'Unknown', 'Auto-generated interaction'),
  (102, 17, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (472, 80, 'low', 'Additive effect', 'Auto-generated interaction'),
  (903, 143, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (918, 6, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (79, 137, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (515, 104, 'low', 'Unknown', 'Auto-generated interaction'),
  (408, 98, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (312, 78, 'low', 'Unknown', 'Auto-generated interaction'),
  (442, 116, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (8, 129, 'low', 'Additive effect', 'Auto-generated interaction'),
  (887, 3, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (619, 61, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (139, 116, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (267, 74, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (104, 68, 'high', 'Unknown', 'Auto-generated interaction'),
  (179, 49, 'severe', 'Unknown', 'Auto-generated interaction'),
  (993, 10, 'low', 'Unknown', 'Auto-generated interaction'),
  (575, 79, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (426, 61, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (564, 35, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (818, 96, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (19, 109, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (575, 73, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (36, 58, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (731, 146, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (835, 68, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (375, 116, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (500, 66, 'low', 'Additive effect', 'Auto-generated interaction'),
  (797, 39, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (456, 129, 'high', 'Additive effect', 'Auto-generated interaction'),
  (167, 27, 'high', 'Unknown', 'Auto-generated interaction'),
  (725, 40, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (532, 68, 'low', 'Additive effect', 'Auto-generated interaction'),
  (915, 98, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (785, 8, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (851, 53, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (875, 37, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (143, 94, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (657, 111, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (887, 44, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (963, 18, 'high', 'Unknown', 'Auto-generated interaction'),
  (230, 41, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (449, 119, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (553, 29, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (690, 133, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (2, 38, 'low', 'Unknown', 'Auto-generated interaction'),
  (796, 1, 'low', 'Unknown', 'Auto-generated interaction'),
  (445, 47, 'high', 'Additive effect', 'Auto-generated interaction'),
  (975, 1, 'high', 'Unknown', 'Auto-generated interaction'),
  (326, 97, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (975, 111, 'low', 'Additive effect', 'Auto-generated interaction'),
  (625, 56, 'severe', 'Unknown', 'Auto-generated interaction'),
  (629, 8, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (584, 31, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (374, 40, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (432, 4, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (228, 1, 'high', 'Additive effect', 'Auto-generated interaction'),
  (20, 149, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (701, 131, 'severe', 'Unknown', 'Auto-generated interaction'),
  (397, 93, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (313, 84, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (527, 26, 'severe', 'Unknown', 'Auto-generated interaction'),
  (418, 65, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (733, 11, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (503, 39, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (207, 148, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (104, 68, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (976, 12, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (584, 123, 'high', 'Unknown', 'Auto-generated interaction'),
  (135, 28, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (18, 56, 'high', 'Additive effect', 'Auto-generated interaction'),
  (302, 5, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (672, 144, 'high', 'Unknown', 'Auto-generated interaction'),
  (650, 109, 'severe', 'Unknown', 'Auto-generated interaction'),
  (617, 4, 'low', 'Unknown', 'Auto-generated interaction'),
  (434, 32, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (354, 58, 'severe', 'Unknown', 'Auto-generated interaction'),
  (774, 3, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (456, 140, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (907, 119, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (82, 84, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (405, 82, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (886, 43, 'low', 'Additive effect', 'Auto-generated interaction'),
  (478, 148, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (746, 77, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (557, 147, 'high', 'Additive effect', 'Auto-generated interaction'),
  (596, 121, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (648, 67, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (91, 125, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (848, 3, 'low', 'Unknown', 'Auto-generated interaction'),
  (957, 78, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (756, 98, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (340, 144, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (624, 11, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (498, 71, 'low', 'Additive effect', 'Auto-generated interaction'),
  (271, 142, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (56, 54, 'high', 'Unknown', 'Auto-generated interaction'),
  (465, 139, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (127, 115, 'high', 'Additive effect', 'Auto-generated interaction'),
  (9, 118, 'high', 'Unknown', 'Auto-generated interaction'),
  (13, 43, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (237, 115, 'severe', 'Unknown', 'Auto-generated interaction'),
  (529, 23, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (133, 52, 'high', 'Additive effect', 'Auto-generated interaction'),
  (124, 74, 'low', 'Unknown', 'Auto-generated interaction'),
  (862, 24, 'high', 'Additive effect', 'Auto-generated interaction'),
  (758, 99, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (771, 96, 'high', 'Unknown', 'Auto-generated interaction'),
  (155, 56, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (980, 104, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (448, 62, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (859, 43, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (655, 25, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (631, 29, 'high', 'Additive effect', 'Auto-generated interaction'),
  (590, 49, 'high', 'Unknown', 'Auto-generated interaction'),
  (565, 97, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (900, 26, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (149, 129, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (708, 132, 'high', 'Unknown', 'Auto-generated interaction'),
  (117, 46, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (934, 127, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (518, 86, 'low', 'Additive effect', 'Auto-generated interaction'),
  (566, 85, 'high', 'Additive effect', 'Auto-generated interaction'),
  (822, 92, 'low', 'Unknown', 'Auto-generated interaction'),
  (861, 58, 'high', 'Unknown', 'Auto-generated interaction'),
  (565, 15, 'low', 'Unknown', 'Auto-generated interaction'),
  (360, 108, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (600, 74, 'severe', 'Unknown', 'Auto-generated interaction'),
  (757, 134, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (685, 35, 'low', 'Unknown', 'Auto-generated interaction'),
  (959, 41, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (779, 46, 'low', 'Additive effect', 'Auto-generated interaction'),
  (453, 82, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (879, 145, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (546, 80, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (754, 122, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (299, 135, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (434, 66, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (451, 105, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (650, 18, 'low', 'Unknown', 'Auto-generated interaction'),
  (23, 20, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (735, 79, 'high', 'Unknown', 'Auto-generated interaction'),
  (528, 61, 'low', 'Unknown', 'Auto-generated interaction'),
  (922, 11, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (558, 98, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (244, 91, 'high', 'Unknown', 'Auto-generated interaction'),
  (644, 72, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (88, 95, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (179, 89, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (150, 94, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (810, 124, 'high', 'Additive effect', 'Auto-generated interaction'),
  (613, 43, 'high', 'Additive effect', 'Auto-generated interaction'),
  (105, 42, 'severe', 'Unknown', 'Auto-generated interaction'),
  (93, 134, 'high', 'Unknown', 'Auto-generated interaction'),
  (382, 24, 'high', 'Additive effect', 'Auto-generated interaction'),
  (748, 109, 'severe', 'Unknown', 'Auto-generated interaction'),
  (350, 51, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (144, 91, 'high', 'Additive effect', 'Auto-generated interaction'),
  (287, 87, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (381, 103, 'low', 'Unknown', 'Auto-generated interaction'),
  (898, 129, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (966, 19, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (548, 146, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (576, 40, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (33, 126, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (756, 51, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (564, 97, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (165, 101, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (105, 109, 'moderate', 'Metabolism inhibition', 'Auto-generated interaction'),
  (439, 68, 'high', 'Unknown', 'Auto-generated interaction'),
  (93, 55, 'severe', 'Additive effect', 'Auto-generated interaction'),
  (401, 116, 'severe', 'Unknown', 'Auto-generated interaction'),
  (872, 145, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (514, 138, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (128, 105, 'low', 'Additive effect', 'Auto-generated interaction'),
  (672, 49, 'severe', 'Unknown', 'Auto-generated interaction'),
  (735, 131, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (138, 139, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (170, 78, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (136, 31, 'moderate', 'Absorption reduction', 'Auto-generated interaction'),
  (610, 137, 'low', 'Unknown', 'Auto-generated interaction'),
  (228, 61, 'high', 'Additive effect', 'Auto-generated interaction'),
  (957, 76, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (937, 119, 'severe', 'Unknown', 'Auto-generated interaction'),
  (696, 129, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (978, 39, 'high', 'Additive effect', 'Auto-generated interaction'),
  (107, 112, 'high', 'Absorption reduction', 'Auto-generated interaction'),
  (597, 99, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (176, 10, 'high', 'Additive effect', 'Auto-generated interaction'),
  (679, 51, 'low', 'Additive effect', 'Auto-generated interaction'),
  (292, 20, 'low', 'Additive effect', 'Auto-generated interaction'),
  (59, 74, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (470, 38, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (923, 90, 'high', 'Additive effect', 'Auto-generated interaction'),
  (672, 102, 'severe', 'Unknown', 'Auto-generated interaction'),
  (45, 39, 'low', 'Absorption reduction', 'Auto-generated interaction'),
  (461, 130, 'high', 'Unknown', 'Auto-generated interaction'),
  (682, 10, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (703, 107, 'high', 'Unknown', 'Auto-generated interaction'),
  (265, 35, 'severe', 'Unknown', 'Auto-generated interaction'),
  (637, 107, 'high', 'Metabolism inhibition', 'Auto-generated interaction'),
  (777, 53, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (991, 12, 'low', 'Metabolism inhibition', 'Auto-generated interaction'),
  (88, 22, 'severe', 'Metabolism inhibition', 'Auto-generated interaction'),
  (836, 138, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (800, 87, 'moderate', 'Additive effect', 'Auto-generated interaction'),
  (645, 126, 'severe', 'Absorption reduction', 'Auto-generated interaction'),
  (431, 83, 'severe', 'Unknown', 'Auto-generated interaction'),
  (369, 15, 'moderate', 'Unknown', 'Auto-generated interaction'),
  (851, 47, 'severe', 'Unknown', 'Auto-generated interaction'),
  (247, 115, 'low', 'Metabolism inhibition', 'Auto-generated interaction');
