INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Copper', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 1', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 2', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 3', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 4', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 5', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 6', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 7', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 8', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 9', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 10', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 11', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 12', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 13', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 14', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 15', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 16', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 17', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 18', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 19', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 20', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 21', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 22', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 23', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 24', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 25', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 26', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 27', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 28', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 29', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 30', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 31', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 32', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 33', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 34', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 35', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 36', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 37', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 38', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 39', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 40', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 41', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 42', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 43', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 44', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 45', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 46', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 47', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 48', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 49', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 50', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ashwagandha', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chromium', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Coenzyme Q10 (CoQ10)', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Collagen', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Copper', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('CoQ10', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Curcumin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Prebiotics', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Probiotics', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Quercetin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Resveratrol', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Rhodiola', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Riboflavin', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Thiamine', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric (Curcumin)', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin B12', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;