INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Vitamin E', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Whey Protein', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Zinc', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 1', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 2', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 3', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 4', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 5', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 6', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 7', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 8', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 9', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 10', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 11', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 12', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 13', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 14', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 15', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 16', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 17', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 18', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 19', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 20', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 21', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 22', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 23', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 24', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 25', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 26', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 27', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 28', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 29', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 30', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 31', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 32', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 33', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 34', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 35', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 36', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 37', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 38', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 39', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 40', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 41', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 42', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 43', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 44', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 45', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 46', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 47', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 48', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 49', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 50', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ashwagandha', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chromium', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Collagen', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Copper', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Curcumin', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Prebiotics', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Probiotics', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Quercetin', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Resveratrol', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Rhodiola', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric (Curcumin)', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Whey Protein', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 1', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 2', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 3', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 4', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 5', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 6', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 7', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 8', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 9', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 10', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 11', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 12', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 13', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 14', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 15', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;