INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Supplement 25', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 26', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 27', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 28', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 29', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 30', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 31', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 32', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 33', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 34', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 35', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 36', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 37', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 38', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 39', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 40', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 41', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 42', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 43', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 44', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 45', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 46', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 47', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 48', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 49', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 50', 'Diltiazem', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ashwagandha', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chromium', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Coenzyme Q10 (CoQ10)', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Collagen', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Copper', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('CoQ10', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Curcumin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Prebiotics', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Probiotics', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Quercetin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Resveratrol', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Rhodiola', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Riboflavin', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Thiamine', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric (Curcumin)', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin B12', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Whey Protein', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Zinc', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 1', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 2', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 3', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 4', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 5', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 6', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 7', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 8', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 9', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 10', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 11', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 12', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 13', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 14', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 15', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 16', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 17', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 18', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 19', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 20', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 21', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 22', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 23', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 24', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 25', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 26', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 27', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 28', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 29', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;