INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Supplement 30', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 31', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 32', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 33', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 34', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 35', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 36', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 37', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 38', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 39', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 40', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 41', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 42', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 43', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 44', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 45', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 46', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 47', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 48', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 49', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 50', 'Duloxetine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ashwagandha', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chromium', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Coenzyme Q10 (CoQ10)', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Collagen', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Copper', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('CoQ10', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Curcumin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Prebiotics', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Probiotics', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Quercetin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Resveratrol', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Rhodiola', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Riboflavin', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Thiamine', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric (Curcumin)', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin B12', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Whey Protein', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Zinc', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 1', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 2', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 3', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 4', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 5', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 6', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 7', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 8', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 9', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 10', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 11', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 12', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 13', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 14', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 15', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 16', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 17', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 18', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 19', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 20', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 21', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 22', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 23', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 24', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 25', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 26', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 27', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 28', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 29', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 30', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 31', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 32', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 33', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 34', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Supplement 35', 'Furosemide', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;