INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Fish Oil', 'Warfarin', 'high', 'Increased bleeding risk due to antiplatelet effects', 'Monitor INR closely; report unusual bleeding. Not medical advice.'),
('Fish Oil (Omega-3)', 'Warfarin', 'high', 'Increased bleeding risk due to antiplatelet effects', 'Monitor INR closely; report unusual bleeding. Not medical advice.'),
('Omega-3', 'Warfarin', 'high', 'Increased bleeding risk due to antiplatelet effects', 'Monitor INR closely; report unusual bleeding. Not medical advice.'),
('Garlic', 'Warfarin', 'moderate', 'May potentiate anticoagulant effect', 'Avoid high-dose garlic supplements; monitor INR. Not medical advice.'),
('Ginkgo Biloba', 'Warfarin', 'high', 'Increased bleeding risk', 'Avoid combination; consult prescriber. Not medical advice.'),
('Vitamin E', 'Warfarin', 'moderate', 'High doses may increase bleeding risk', 'Limit vitamin E >400 IU; monitor INR. Not medical advice.'),
('Vitamin K', 'Warfarin', 'high', 'Directly antagonizes warfarin anticoagulant effect', 'Maintain consistent vitamin K intake; consult prescriber. Not medical advice.'),
('Vitamin K2', 'Warfarin', 'high', 'Directly antagonizes warfarin anticoagulant effect', 'Maintain consistent vitamin K intake; consult prescriber. Not medical advice.'),
('Fish Oil', 'Aspirin', 'moderate', 'Additive antiplatelet effects increase bleeding risk', 'Monitor for bleeding signs; separate timing if possible. Not medical advice.'),
('Omega-3', 'Aspirin', 'moderate', 'Additive antiplatelet effects increase bleeding risk', 'Monitor for bleeding signs; separate timing if possible. Not medical advice.'),
('Garlic', 'Clopidogrel', 'moderate', 'May enhance antiplatelet effects', 'Avoid high-dose supplements; monitor for bleeding. Not medical advice.'),
('Garlic', 'Clopidogrel (Plavix)', 'moderate', 'May enhance antiplatelet effects', 'Avoid high-dose supplements; monitor for bleeding. Not medical advice.'),
('Ginkgo Biloba', 'Aspirin', 'moderate', 'Increased bleeding risk', 'Use cautiously; monitor for bleeding. Not medical advice.'),
('Ginkgo Biloba', 'Clopidogrel', 'moderate', 'Increased bleeding risk', 'Use cautiously; monitor for bleeding. Not medical advice.'),
('St. John''s Wort', 'Sertraline', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('St. John''s Wort', 'Sertraline (Zoloft)', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('St. John''s Wort', 'Fluoxetine', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('St. John''s Wort', 'Escitalopram', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('St. John''s Wort', 'Venlafaxine', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('St. John''s Wort', 'Duloxetine', 'severe', 'Risk of serotonin syndrome; CYP inducer reduces drug levels', 'Do not combine; consult prescriber immediately. Not medical advice.'),
('5-HTP', 'Sertraline', 'high', 'Risk of serotonin syndrome', 'Avoid combination; consult prescriber. Not medical advice.'),
('5-HTP', 'Fluoxetine', 'high', 'Risk of serotonin syndrome', 'Avoid combination; consult prescriber. Not medical advice.'),
('5-HTP', 'Escitalopram', 'high', 'Risk of serotonin syndrome', 'Avoid combination; consult prescriber. Not medical advice.'),
('Calcium', 'Levothyroxine', 'moderate', 'Reduces absorption of thyroid medication', 'Separate by at least 4 hours. Not medical advice.'),
('Iron', 'Levothyroxine', 'moderate', 'Reduces absorption of thyroid medication', 'Separate by at least 4 hours. Not medical advice.'),
('Magnesium', 'Levothyroxine', 'moderate', 'May reduce absorption of thyroid medication', 'Separate by at least 2-4 hours. Not medical advice.'),
('Fiber', 'Levothyroxine', 'low', 'High-fiber supplements may reduce absorption', 'Take levothyroxine on empty stomach; separate fiber. Not medical advice.'),
('Iron', 'Omeprazole', 'moderate', 'Reduced iron absorption due to increased gastric pH', 'Consider iron supplementation timing or formulation. Not medical advice.'),
('Iron', 'Omeprazole (Prilosec)', 'moderate', 'Reduced iron absorption due to increased gastric pH', 'Consider iron supplementation timing or formulation. Not medical advice.'),
('Calcium', 'Ciprofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Calcium', 'Levofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Calcium', 'Doxycycline', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Iron', 'Ciprofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Iron', 'Levofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Iron', 'Doxycycline', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Magnesium', 'Ciprofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Magnesium', 'Levofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Zinc', 'Ciprofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Zinc', 'Levofloxacin', 'moderate', 'Chelation reduces antibiotic absorption', 'Separate by at least 2 hours. Not medical advice.'),
('Probiotics', 'Amoxicillin', 'low', 'Antibiotics may reduce probiotic viability', 'Take probiotics several hours apart from antibiotic. Not medical advice.'),
('Probiotics', 'Azithromycin', 'low', 'Antibiotics may reduce probiotic viability', 'Take probiotics several hours apart from antibiotic. Not medical advice.'),
('Probiotics', 'Ciprofloxacin', 'low', 'Antibiotics may reduce probiotic viability', 'Take probiotics several hours apart from antibiotic. Not medical advice.'),
('Niacin', 'Atorvastatin', 'moderate', 'Increased risk of myopathy', 'Use cautiously; monitor for muscle pain. Not medical advice.'),
('Niacin', 'Atorvastatin (Lipitor)', 'moderate', 'Increased risk of myopathy', 'Use cautiously; monitor for muscle pain. Not medical advice.'),
('Niacin', 'Simvastatin', 'moderate', 'Increased risk of myopathy', 'Use cautiously; monitor for muscle pain. Not medical advice.'),
('Niacin', 'Rosuvastatin', 'moderate', 'Increased risk of myopathy', 'Use cautiously; monitor for muscle pain. Not medical advice.'),
('CoQ10', 'Warfarin', 'moderate', 'May reduce anticoagulant effect', 'Monitor INR if starting/stopping CoQ10. Not medical advice.'),
('Coenzyme Q10 (CoQ10)', 'Warfarin', 'moderate', 'May reduce anticoagulant effect', 'Monitor INR if starting/stopping CoQ10. Not medical advice.'),
('Potassium', 'Lisinopril', 'moderate', 'Risk of hyperkalemia', 'Monitor potassium levels; avoid high-dose supplements. Not medical advice.'),
('Potassium', 'Losartan', 'moderate', 'Risk of hyperkalemia', 'Monitor potassium levels; avoid high-dose supplements. Not medical advice.'),
('Potassium', 'Spironolactone', 'high', 'Significant risk of hyperkalemia', 'Avoid potassium supplements; monitor levels closely. Not medical advice.'),
('Magnesium', 'Hydrochlorothiazide', 'low', 'Diuretic may deplete magnesium', 'Magnesium supplementation may be beneficial; consult prescriber. Not medical advice.'),
('Potassium', 'Hydrochlorothiazide', 'low', 'Diuretic may deplete potassium', 'Potassium supplementation may be needed; monitor levels. Not medical advice.'),
('Potassium', 'Furosemide', 'low', 'Diuretic may deplete potassium', 'Potassium supplementation may be needed; monitor levels. Not medical advice.'),
('Magnesium', 'Furosemide', 'low', 'Diuretic may deplete magnesium', 'Magnesium supplementation may be beneficial; consult prescriber. Not medical advice.'),
('Melatonin', 'Zolpidem', 'moderate', 'Additive sedative effects', 'Use cautiously; avoid driving. Not medical advice.'),
('Valerian Root', 'Zolpidem', 'moderate', 'Additive sedative effects', 'Use cautiously; avoid driving. Not medical advice.'),
('Valerian Root', 'Alprazolam', 'moderate', 'Additive sedative effects', 'Use cautiously; consult prescriber. Not medical advice.'),
('Valerian Root', 'Lorazepam', 'moderate', 'Additive sedative effects', 'Use cautiously; consult prescriber. Not medical advice.'),
('Valerian Root', 'Diazepam', 'moderate', 'Additive sedative effects', 'Use cautiously; consult prescriber. Not medical advice.'),
('Valerian Root', 'Clonazepam', 'moderate', 'Additive sedative effects', 'Use cautiously; consult prescriber. Not medical advice.'),
('Magnesium', 'Metformin', 'low', 'Metformin may reduce magnesium absorption', 'Consider magnesium supplementation; monitor levels. Not medical advice.'),
('Vitamin B12', 'Metformin', 'low', 'Long-term metformin may deplete B12', 'Consider B12 supplementation; monitor levels annually. Not medical advice.'),
('Chromium', 'Insulin', 'moderate', 'May enhance insulin effect; hypoglycemia risk', 'Monitor blood glucose closely. Not medical advice.'),
('Chromium', 'Metformin', 'low', 'May enhance glucose-lowering effect', 'Monitor blood glucose; consult prescriber. Not medical advice.'),
('Ginseng', 'Insulin', 'moderate', 'May affect blood glucose control', 'Monitor blood glucose closely. Not medical advice.'),
('Ginseng', 'Metformin', 'low', 'May affect blood glucose control', 'Monitor blood glucose; consult prescriber. Not medical advice.'),
('Vitamin C', 'Warfarin', 'low', 'High doses (>1g/day) may affect INR', 'Keep vitamin C intake consistent; monitor INR. Not medical advice.'),
('Green Tea Extract', 'Warfarin', 'moderate', 'Contains vitamin K; may reduce anticoagulant effect', 'Avoid high doses; monitor INR. Not medical advice.'),
('Zinc', 'Amoxicillin', 'low', 'May reduce antibiotic absorption', 'Separate by 2 hours if possible. Not medical advice.'),
('Calcium', 'Verapamil', 'moderate', 'May reduce effectiveness of calcium channel blocker', 'Consult prescriber before high-dose calcium. Not medical advice.'),
('Calcium', 'Diltiazem', 'moderate', 'May reduce effectiveness of calcium channel blocker', 'Consult prescriber before high-dose calcium. Not medical advice.'),
('St. John''s Wort', 'Digoxin', 'high', 'CYP inducer reduces digoxin levels', 'Avoid combination; consult prescriber. Not medical advice.'),
('St. John''s Wort', 'Verapamil', 'high', 'CYP inducer reduces drug levels', 'Avoid combination; consult prescriber. Not medical advice.'),
('St. John''s Wort', 'Atorvastatin', 'moderate', 'CYP inducer may reduce statin levels', 'Avoid combination; consult prescriber. Not medical advice.'),
('St. John''s Wort', 'Simvastatin', 'moderate', 'CYP inducer may reduce statin levels', 'Avoid combination; consult prescriber. Not medical advice.'),
('Ginkgo Biloba', 'Ibuprofen', 'moderate', 'Increased bleeding risk', 'Use cautiously; monitor for bleeding. Not medical advice.'),
('Ginkgo Biloba', 'Naproxen', 'moderate', 'Increased bleeding risk', 'Use cautiously; monitor for bleeding. Not medical advice.'),
('Garlic', 'Aspirin', 'moderate', 'Additive antiplatelet effects', 'Avoid high-dose garlic; monitor for bleeding. Not medical advice.'),
('Ginger', 'Warfarin', 'moderate', 'May enhance anticoagulant effect', 'Avoid high doses; monitor INR. Not medical advice.'),
('Ginger', 'Aspirin', 'low', 'May enhance antiplatelet effects', 'Use moderate amounts; monitor for bleeding. Not medical advice.'),
('Turmeric', 'Warfarin', 'moderate', 'May enhance anticoagulant effect', 'Avoid high doses; monitor INR. Not medical advice.'),
('Turmeric (Curcumin)', 'Warfarin', 'moderate', 'May enhance anticoagulant effect', 'Avoid high doses; monitor INR. Not medical advice.'),
('Curcumin', 'Warfarin', 'moderate', 'May enhance anticoagulant effect', 'Avoid high doses; monitor INR. Not medical advice.'),
('Vitamin D3', 'Digoxin', 'moderate', 'Hypercalcemia from vitamin D may increase digoxin toxicity', 'Monitor calcium and digoxin levels. Not medical advice.'),
('Calcium', 'Digoxin', 'moderate', 'Hypercalcemia may increase digoxin toxicity', 'Avoid high-dose calcium; monitor levels. Not medical advice.'),
('SAMe', 'Sertraline', 'moderate', 'Risk of serotonin syndrome', 'Avoid combination; consult prescriber. Not medical advice.'),
('SAMe', 'Escitalopram', 'moderate', 'Risk of serotonin syndrome', 'Avoid combination; consult prescriber. Not medical advice.'),
('Niacin', 'Pravastatin', 'moderate', 'Increased risk of myopathy', 'Use cautiously; monitor for muscle pain. Not medical advice.'),
('Ginseng', 'Warfarin', 'moderate', 'May affect INR variability', 'Monitor INR closely; maintain consistent use. Not medical advice.'),
('Vitamin C', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Metoprolol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Amlodipine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Metoprolol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin D3', 'Amlodipine', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin B12', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin B12', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;