INSERT INTO interactions (supplement_id, medication_id, severity, description, recommendation)
SELECT s.id, m.id, v.severity, v.description, v.recommendation
FROM (VALUES
('Glucosamine', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Celecoxib', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Meloxicam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Diclofenac', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Naproxen', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Ibuprofen', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Alprazolam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Lorazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Diazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Clonazepam', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin C', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Simvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Pravastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Rosuvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Vitamin E', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Simvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Niacin', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Niacin', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Valerian Root', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Losartan', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginkgo Biloba', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginkgo Biloba', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginkgo Biloba', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Garlic', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Garlic', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Garlic', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Metformin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Atorvastatin', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Lisinopril', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Alpha Lipoic Acid', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ashwagandha', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Biotin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Caffeine', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Calcium', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chondroitin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Chromium', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Coenzyme Q10 (CoQ10)', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Collagen', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Copper', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('CoQ10', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Creatine Monohydrate', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Curcumin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Echinacea', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Fiber', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Folic Acid', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginger', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Ginseng', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Glucosamine', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Green Tea Extract', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iodine', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Iron', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('L-Theanine', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Magnesium', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Manganese', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Melatonin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Molybdenum', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Prebiotics', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Probiotics', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Quercetin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Resveratrol', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Rhodiola', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Riboflavin', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('SAMe', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Selenium', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Thiamine', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.'),
('Turmeric (Curcumin)', 'Albuterol', 'low', 'No well-documented significant interaction', 'Generally safe to combine; consult healthcare provider. Not medical advice.')
) AS v(supplement_name, medication_name, severity, description, recommendation)
JOIN supplements s ON s.name = v.supplement_name
JOIN medications m ON m.name = v.medication_name
ON CONFLICT (supplement_id, medication_id, severity) DO NOTHING;