INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 751', 'Botanical', '', ''),
  ('Supplement 752', 'Amino Acid', '', ''),
  ('Supplement 753', 'Adaptogen', '', ''),
  ('Supplement 754', 'Adaptogen', '', ''),
  ('Supplement 755', 'Mineral', '', ''),
  ('Supplement 756', 'Amino Acid', '', ''),
  ('Supplement 757', 'Botanical', '', ''),
  ('Supplement 758', 'Electrolyte', '', ''),
  ('Supplement 759', 'Amino Acid', '', ''),
  ('Supplement 760', 'Botanical', '', ''),
  ('Supplement 761', 'Probiotic', '', ''),
  ('Supplement 762', 'Electrolyte', '', ''),
  ('Supplement 763', 'Electrolyte', '', ''),
  ('Supplement 764', 'Mineral', '', ''),
  ('Supplement 765', 'Probiotic', '', ''),
  ('Supplement 766', 'Electrolyte', '', ''),
  ('Supplement 767', 'Amino Acid', '', ''),
  ('Supplement 768', 'Botanical', '', ''),
  ('Supplement 769', 'Adaptogen', '', ''),
  ('Supplement 770', 'Probiotic', '', ''),
  ('Supplement 771', 'Probiotic', '', ''),
  ('Supplement 772', 'Mineral', '', ''),
  ('Supplement 773', 'Botanical', '', ''),
  ('Supplement 774', 'Amino Acid', '', ''),
  ('Supplement 775', 'Amino Acid', '', ''),
  ('Supplement 776', 'Probiotic', '', ''),
  ('Supplement 777', 'Vitamin', '', ''),
  ('Supplement 778', 'Probiotic', '', ''),
  ('Supplement 779', 'Vitamin', '', ''),
  ('Supplement 780', 'Adaptogen', '', ''),
  ('Supplement 781', 'Electrolyte', '', ''),
  ('Supplement 782', 'Botanical', '', ''),
  ('Supplement 783', 'Botanical', '', ''),
  ('Supplement 784', 'Amino Acid', '', ''),
  ('Supplement 785', 'Mineral', '', ''),
  ('Supplement 786', 'Mineral', '', ''),
  ('Supplement 787', 'Adaptogen', '', ''),
  ('Supplement 788', 'Adaptogen', '', ''),
  ('Supplement 789', 'Mineral', '', ''),
  ('Supplement 790', 'Mineral', '', ''),
  ('Supplement 791', 'Probiotic', '', ''),
  ('Supplement 792', 'Botanical', '', ''),
  ('Supplement 793', 'Botanical', '', ''),
  ('Supplement 794', 'Botanical', '', ''),
  ('Supplement 795', 'Electrolyte', '', ''),
  ('Supplement 796', 'Electrolyte', '', ''),
  ('Supplement 797', 'Vitamin', '', ''),
  ('Supplement 798', 'Vitamin', '', ''),
  ('Supplement 799', 'Vitamin', '', ''),
  ('Supplement 800', 'Vitamin', '', ''),
  ('Supplement 801', 'Vitamin', '', ''),
  ('Supplement 802', 'Electrolyte', '', ''),
  ('Supplement 803', 'Electrolyte', '', ''),
  ('Supplement 804', 'Amino Acid', '', ''),
  ('Supplement 805', 'Probiotic', '', ''),
  ('Supplement 806', 'Mineral', '', ''),
  ('Supplement 807', 'Adaptogen', '', ''),
  ('Supplement 808', 'Electrolyte', '', ''),
  ('Supplement 809', 'Amino Acid', '', ''),
  ('Supplement 810', 'Adaptogen', '', ''),
  ('Supplement 811', 'Amino Acid', '', ''),
  ('Supplement 812', 'Botanical', '', ''),
  ('Supplement 813', 'Vitamin', '', ''),
  ('Supplement 814', 'Vitamin', '', ''),
  ('Supplement 815', 'Botanical', '', ''),
  ('Supplement 816', 'Amino Acid', '', ''),
  ('Supplement 817', 'Vitamin', '', ''),
  ('Supplement 818', 'Botanical', '', ''),
  ('Supplement 819', 'Adaptogen', '', ''),
  ('Supplement 820', 'Mineral', '', ''),
  ('Supplement 821', 'Probiotic', '', ''),
  ('Supplement 822', 'Amino Acid', '', ''),
  ('Supplement 823', 'Probiotic', '', ''),
  ('Supplement 824', 'Adaptogen', '', ''),
  ('Supplement 825', 'Vitamin', '', ''),
  ('Supplement 826', 'Probiotic', '', ''),
  ('Supplement 827', 'Mineral', '', ''),
  ('Supplement 828', 'Amino Acid', '', ''),
  ('Supplement 829', 'Probiotic', '', ''),
  ('Supplement 830', 'Botanical', '', ''),
  ('Supplement 831', 'Amino Acid', '', ''),
  ('Supplement 832', 'Adaptogen', '', ''),
  ('Supplement 833', 'Electrolyte', '', ''),
  ('Supplement 834', 'Mineral', '', ''),
  ('Supplement 835', 'Amino Acid', '', ''),
  ('Supplement 836', 'Mineral', '', ''),
  ('Supplement 837', 'Probiotic', '', ''),
  ('Supplement 838', 'Adaptogen', '', ''),
  ('Supplement 839', 'Vitamin', '', ''),
  ('Supplement 840', 'Vitamin', '', ''),
  ('Supplement 841', 'Amino Acid', '', ''),
  ('Supplement 842', 'Electrolyte', '', ''),
  ('Supplement 843', 'Probiotic', '', ''),
  ('Supplement 844', 'Probiotic', '', ''),
  ('Supplement 845', 'Amino Acid', '', ''),
  ('Supplement 846', 'Vitamin', '', ''),
  ('Supplement 847', 'Vitamin', '', ''),
  ('Supplement 848', 'Amino Acid', '', ''),
  ('Supplement 849', 'Botanical', '', ''),
  ('Supplement 850', 'Amino Acid', '', ''),
  ('Supplement 851', 'Mineral', '', ''),
  ('Supplement 852', 'Vitamin', '', ''),
  ('Supplement 853', 'Vitamin', '', ''),
  ('Supplement 854', 'Vitamin', '', ''),
  ('Supplement 855', 'Adaptogen', '', ''),
  ('Supplement 856', 'Mineral', '', ''),
  ('Supplement 857', 'Vitamin', '', ''),
  ('Supplement 858', 'Probiotic', '', ''),
  ('Supplement 859', 'Mineral', '', ''),
  ('Supplement 860', 'Mineral', '', ''),
  ('Supplement 861', 'Adaptogen', '', ''),
  ('Supplement 862', 'Probiotic', '', ''),
  ('Supplement 863', 'Electrolyte', '', ''),
  ('Supplement 864', 'Probiotic', '', ''),
  ('Supplement 865', 'Amino Acid', '', ''),
  ('Supplement 866', 'Amino Acid', '', ''),
  ('Supplement 867', 'Adaptogen', '', ''),
  ('Supplement 868', 'Electrolyte', '', ''),
  ('Supplement 869', 'Adaptogen', '', ''),
  ('Supplement 870', 'Amino Acid', '', ''),
  ('Supplement 871', 'Electrolyte', '', ''),
  ('Supplement 872', 'Probiotic', '', ''),
  ('Supplement 873', 'Botanical', '', ''),
  ('Supplement 874', 'Vitamin', '', ''),
  ('Supplement 875', 'Probiotic', '', ''),
  ('Supplement 876', 'Electrolyte', '', ''),
  ('Supplement 877', 'Adaptogen', '', ''),
  ('Supplement 878', 'Electrolyte', '', ''),
  ('Supplement 879', 'Probiotic', '', ''),
  ('Supplement 880', 'Vitamin', '', ''),
  ('Supplement 881', 'Adaptogen', '', ''),
  ('Supplement 882', 'Botanical', '', ''),
  ('Supplement 883', 'Probiotic', '', ''),
  ('Supplement 884', 'Botanical', '', ''),
  ('Supplement 885', 'Electrolyte', '', ''),
  ('Supplement 886', 'Adaptogen', '', ''),
  ('Supplement 887', 'Vitamin', '', ''),
  ('Supplement 888', 'Amino Acid', '', ''),
  ('Supplement 889', 'Vitamin', '', ''),
  ('Supplement 890', 'Mineral', '', ''),
  ('Supplement 891', 'Amino Acid', '', ''),
  ('Supplement 892', 'Botanical', '', ''),
  ('Supplement 893', 'Probiotic', '', ''),
  ('Supplement 894', 'Vitamin', '', ''),
  ('Supplement 895', 'Vitamin', '', ''),
  ('Supplement 896', 'Amino Acid', '', ''),
  ('Supplement 897', 'Electrolyte', '', ''),
  ('Supplement 898', 'Probiotic', '', ''),
  ('Supplement 899', 'Botanical', '', ''),
  ('Supplement 900', 'Amino Acid', '', ''),
  ('Supplement 901', 'Amino Acid', '', ''),
  ('Supplement 902', 'Mineral', '', ''),
  ('Supplement 903', 'Botanical', '', ''),
  ('Supplement 904', 'Electrolyte', '', ''),
  ('Supplement 905', 'Adaptogen', '', ''),
  ('Supplement 906', 'Amino Acid', '', ''),
  ('Supplement 907', 'Electrolyte', '', ''),
  ('Supplement 908', 'Botanical', '', ''),
  ('Supplement 909', 'Electrolyte', '', ''),
  ('Supplement 910', 'Probiotic', '', ''),
  ('Supplement 911', 'Mineral', '', ''),
  ('Supplement 912', 'Amino Acid', '', ''),
  ('Supplement 913', 'Amino Acid', '', ''),
  ('Supplement 914', 'Mineral', '', ''),
  ('Supplement 915', 'Mineral', '', ''),
  ('Supplement 916', 'Probiotic', '', ''),
  ('Supplement 917', 'Botanical', '', ''),
  ('Supplement 918', 'Botanical', '', ''),
  ('Supplement 919', 'Electrolyte', '', ''),
  ('Supplement 920', 'Amino Acid', '', ''),
  ('Supplement 921', 'Adaptogen', '', ''),
  ('Supplement 922', 'Vitamin', '', ''),
  ('Supplement 923', 'Vitamin', '', ''),
  ('Supplement 924', 'Probiotic', '', ''),
  ('Supplement 925', 'Vitamin', '', ''),
  ('Supplement 926', 'Vitamin', '', ''),
  ('Supplement 927', 'Amino Acid', '', ''),
  ('Supplement 928', 'Electrolyte', '', ''),
  ('Supplement 929', 'Vitamin', '', ''),
  ('Supplement 930', 'Probiotic', '', ''),
  ('Supplement 931', 'Probiotic', '', ''),
  ('Supplement 932', 'Mineral', '', ''),
  ('Supplement 933', 'Vitamin', '', ''),
  ('Supplement 934', 'Probiotic', '', ''),
  ('Supplement 935', 'Amino Acid', '', ''),
  ('Supplement 936', 'Probiotic', '', ''),
  ('Supplement 937', 'Botanical', '', ''),
  ('Supplement 938', 'Mineral', '', ''),
  ('Supplement 939', 'Probiotic', '', ''),
  ('Supplement 940', 'Adaptogen', '', ''),
  ('Supplement 941', 'Mineral', '', ''),
  ('Supplement 942', 'Adaptogen', '', ''),
  ('Supplement 943', 'Botanical', '', ''),
  ('Supplement 944', 'Adaptogen', '', ''),
  ('Supplement 945', 'Mineral', '', ''),
  ('Supplement 946', 'Adaptogen', '', ''),
  ('Supplement 947', 'Electrolyte', '', ''),
  ('Supplement 948', 'Electrolyte', '', ''),
  ('Supplement 949', 'Botanical', '', ''),
  ('Supplement 950', 'Probiotic', '', ''),
  ('Supplement 951', 'Adaptogen', '', ''),
  ('Supplement 952', 'Amino Acid', '', ''),
  ('Supplement 953', 'Amino Acid', '', ''),
  ('Supplement 954', 'Probiotic', '', ''),
  ('Supplement 955', 'Botanical', '', ''),
  ('Supplement 956', 'Vitamin', '', ''),
  ('Supplement 957', 'Botanical', '', ''),
  ('Supplement 958', 'Probiotic', '', ''),
  ('Supplement 959', 'Vitamin', '', ''),
  ('Supplement 960', 'Botanical', '', ''),
  ('Supplement 961', 'Electrolyte', '', ''),
  ('Supplement 962', 'Probiotic', '', ''),
  ('Supplement 963', 'Mineral', '', ''),
  ('Supplement 964', 'Adaptogen', '', ''),
  ('Supplement 965', 'Mineral', '', ''),
  ('Supplement 966', 'Botanical', '', ''),
  ('Supplement 967', 'Amino Acid', '', ''),
  ('Supplement 968', 'Probiotic', '', ''),
  ('Supplement 969', 'Vitamin', '', ''),
  ('Supplement 970', 'Electrolyte', '', ''),
  ('Supplement 971', 'Amino Acid', '', ''),
  ('Supplement 972', 'Vitamin', '', ''),
  ('Supplement 973', 'Mineral', '', ''),
  ('Supplement 974', 'Mineral', '', ''),
  ('Supplement 975', 'Adaptogen', '', ''),
  ('Supplement 976', 'Probiotic', '', ''),
  ('Supplement 977', 'Amino Acid', '', ''),
  ('Supplement 978', 'Amino Acid', '', ''),
  ('Supplement 979', 'Adaptogen', '', ''),
  ('Supplement 980', 'Mineral', '', ''),
  ('Supplement 981', 'Mineral', '', ''),
  ('Supplement 982', 'Electrolyte', '', ''),
  ('Supplement 983', 'Botanical', '', ''),
  ('Supplement 984', 'Amino Acid', '', ''),
  ('Supplement 985', 'Mineral', '', ''),
  ('Supplement 986', 'Mineral', '', ''),
  ('Supplement 987', 'Electrolyte', '', ''),
  ('Supplement 988', 'Amino Acid', '', ''),
  ('Supplement 989', 'Adaptogen', '', ''),
  ('Supplement 990', 'Vitamin', '', ''),
  ('Supplement 991', 'Adaptogen', '', ''),
  ('Supplement 992', 'Adaptogen', '', ''),
  ('Supplement 993', 'Adaptogen', '', ''),
  ('Supplement 994', 'Amino Acid', '', ''),
  ('Supplement 995', 'Vitamin', '', ''),
  ('Supplement 996', 'Amino Acid', '', ''),
  ('Supplement 997', 'Mineral', '', ''),
  ('Supplement 998', 'Electrolyte', '', ''),
  ('Supplement 999', 'Electrolyte', '', ''),
  ('Supplement 1000', 'Adaptogen', '', '')
ON CONFLICT (name) DO NOTHING;