INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 501', 'Mineral', '', ''),
  ('Supplement 502', 'Botanical', '', ''),
  ('Supplement 503', 'Amino Acid', '', ''),
  ('Supplement 504', 'Adaptogen', '', ''),
  ('Supplement 505', 'Amino Acid', '', ''),
  ('Supplement 506', 'Probiotic', '', ''),
  ('Supplement 507', 'Adaptogen', '', ''),
  ('Supplement 508', 'Amino Acid', '', ''),
  ('Supplement 509', 'Adaptogen', '', ''),
  ('Supplement 510', 'Amino Acid', '', ''),
  ('Supplement 511', 'Mineral', '', ''),
  ('Supplement 512', 'Mineral', '', ''),
  ('Supplement 513', 'Adaptogen', '', ''),
  ('Supplement 514', 'Mineral', '', ''),
  ('Supplement 515', 'Mineral', '', ''),
  ('Supplement 516', 'Probiotic', '', ''),
  ('Supplement 517', 'Electrolyte', '', ''),
  ('Supplement 518', 'Amino Acid', '', ''),
  ('Supplement 519', 'Amino Acid', '', ''),
  ('Supplement 520', 'Probiotic', '', ''),
  ('Supplement 521', 'Mineral', '', ''),
  ('Supplement 522', 'Probiotic', '', ''),
  ('Supplement 523', 'Amino Acid', '', ''),
  ('Supplement 524', 'Probiotic', '', ''),
  ('Supplement 525', 'Probiotic', '', ''),
  ('Supplement 526', 'Mineral', '', ''),
  ('Supplement 527', 'Botanical', '', ''),
  ('Supplement 528', 'Probiotic', '', ''),
  ('Supplement 529', 'Vitamin', '', ''),
  ('Supplement 530', 'Vitamin', '', ''),
  ('Supplement 531', 'Botanical', '', ''),
  ('Supplement 532', 'Amino Acid', '', ''),
  ('Supplement 533', 'Mineral', '', ''),
  ('Supplement 534', 'Vitamin', '', ''),
  ('Supplement 535', 'Vitamin', '', ''),
  ('Supplement 536', 'Electrolyte', '', ''),
  ('Supplement 537', 'Electrolyte', '', ''),
  ('Supplement 538', 'Amino Acid', '', ''),
  ('Supplement 539', 'Adaptogen', '', ''),
  ('Supplement 540', 'Vitamin', '', ''),
  ('Supplement 541', 'Mineral', '', ''),
  ('Supplement 542', 'Probiotic', '', ''),
  ('Supplement 543', 'Probiotic', '', ''),
  ('Supplement 544', 'Mineral', '', ''),
  ('Supplement 545', 'Mineral', '', ''),
  ('Supplement 546', 'Botanical', '', ''),
  ('Supplement 547', 'Adaptogen', '', ''),
  ('Supplement 548', 'Vitamin', '', ''),
  ('Supplement 549', 'Adaptogen', '', ''),
  ('Supplement 550', 'Vitamin', '', ''),
  ('Supplement 551', 'Vitamin', '', ''),
  ('Supplement 552', 'Probiotic', '', ''),
  ('Supplement 553', 'Electrolyte', '', ''),
  ('Supplement 554', 'Electrolyte', '', ''),
  ('Supplement 555', 'Electrolyte', '', ''),
  ('Supplement 556', 'Botanical', '', ''),
  ('Supplement 557', 'Electrolyte', '', ''),
  ('Supplement 558', 'Mineral', '', ''),
  ('Supplement 559', 'Amino Acid', '', ''),
  ('Supplement 560', 'Adaptogen', '', ''),
  ('Supplement 561', 'Vitamin', '', ''),
  ('Supplement 562', 'Adaptogen', '', ''),
  ('Supplement 563', 'Amino Acid', '', ''),
  ('Supplement 564', 'Vitamin', '', ''),
  ('Supplement 565', 'Probiotic', '', ''),
  ('Supplement 566', 'Vitamin', '', ''),
  ('Supplement 567', 'Mineral', '', ''),
  ('Supplement 568', 'Adaptogen', '', ''),
  ('Supplement 569', 'Probiotic', '', ''),
  ('Supplement 570', 'Amino Acid', '', ''),
  ('Supplement 571', 'Mineral', '', ''),
  ('Supplement 572', 'Adaptogen', '', ''),
  ('Supplement 573', 'Mineral', '', ''),
  ('Supplement 574', 'Probiotic', '', ''),
  ('Supplement 575', 'Vitamin', '', ''),
  ('Supplement 576', 'Electrolyte', '', ''),
  ('Supplement 577', 'Probiotic', '', ''),
  ('Supplement 578', 'Mineral', '', ''),
  ('Supplement 579', 'Adaptogen', '', ''),
  ('Supplement 580', 'Vitamin', '', ''),
  ('Supplement 581', 'Botanical', '', ''),
  ('Supplement 582', 'Amino Acid', '', ''),
  ('Supplement 583', 'Botanical', '', ''),
  ('Supplement 584', 'Amino Acid', '', ''),
  ('Supplement 585', 'Mineral', '', ''),
  ('Supplement 586', 'Adaptogen', '', ''),
  ('Supplement 587', 'Vitamin', '', ''),
  ('Supplement 588', 'Botanical', '', ''),
  ('Supplement 589', 'Vitamin', '', ''),
  ('Supplement 590', 'Electrolyte', '', ''),
  ('Supplement 591', 'Adaptogen', '', ''),
  ('Supplement 592', 'Adaptogen', '', ''),
  ('Supplement 593', 'Mineral', '', ''),
  ('Supplement 594', 'Botanical', '', ''),
  ('Supplement 595', 'Probiotic', '', ''),
  ('Supplement 596', 'Probiotic', '', ''),
  ('Supplement 597', 'Electrolyte', '', ''),
  ('Supplement 598', 'Botanical', '', ''),
  ('Supplement 599', 'Electrolyte', '', ''),
  ('Supplement 600', 'Vitamin', '', ''),
  ('Supplement 601', 'Botanical', '', ''),
  ('Supplement 602', 'Probiotic', '', ''),
  ('Supplement 603', 'Adaptogen', '', ''),
  ('Supplement 604', 'Electrolyte', '', ''),
  ('Supplement 605', 'Vitamin', '', ''),
  ('Supplement 606', 'Electrolyte', '', ''),
  ('Supplement 607', 'Electrolyte', '', ''),
  ('Supplement 608', 'Botanical', '', ''),
  ('Supplement 609', 'Adaptogen', '', ''),
  ('Supplement 610', 'Probiotic', '', ''),
  ('Supplement 611', 'Botanical', '', ''),
  ('Supplement 612', 'Adaptogen', '', ''),
  ('Supplement 613', 'Adaptogen', '', ''),
  ('Supplement 614', 'Electrolyte', '', ''),
  ('Supplement 615', 'Amino Acid', '', ''),
  ('Supplement 616', 'Electrolyte', '', ''),
  ('Supplement 617', 'Electrolyte', '', ''),
  ('Supplement 618', 'Probiotic', '', ''),
  ('Supplement 619', 'Adaptogen', '', ''),
  ('Supplement 620', 'Adaptogen', '', ''),
  ('Supplement 621', 'Electrolyte', '', ''),
  ('Supplement 622', 'Amino Acid', '', ''),
  ('Supplement 623', 'Adaptogen', '', ''),
  ('Supplement 624', 'Amino Acid', '', ''),
  ('Supplement 625', 'Vitamin', '', ''),
  ('Supplement 626', 'Amino Acid', '', ''),
  ('Supplement 627', 'Vitamin', '', ''),
  ('Supplement 628', 'Vitamin', '', ''),
  ('Supplement 629', 'Amino Acid', '', ''),
  ('Supplement 630', 'Amino Acid', '', ''),
  ('Supplement 631', 'Electrolyte', '', ''),
  ('Supplement 632', 'Amino Acid', '', ''),
  ('Supplement 633', 'Electrolyte', '', ''),
  ('Supplement 634', 'Adaptogen', '', ''),
  ('Supplement 635', 'Adaptogen', '', ''),
  ('Supplement 636', 'Amino Acid', '', ''),
  ('Supplement 637', 'Probiotic', '', ''),
  ('Supplement 638', 'Electrolyte', '', ''),
  ('Supplement 639', 'Amino Acid', '', ''),
  ('Supplement 640', 'Probiotic', '', ''),
  ('Supplement 641', 'Adaptogen', '', ''),
  ('Supplement 642', 'Mineral', '', ''),
  ('Supplement 643', 'Adaptogen', '', ''),
  ('Supplement 644', 'Electrolyte', '', ''),
  ('Supplement 645', 'Adaptogen', '', ''),
  ('Supplement 646', 'Vitamin', '', ''),
  ('Supplement 647', 'Probiotic', '', ''),
  ('Supplement 648', 'Probiotic', '', ''),
  ('Supplement 649', 'Botanical', '', ''),
  ('Supplement 650', 'Vitamin', '', ''),
  ('Supplement 651', 'Probiotic', '', ''),
  ('Supplement 652', 'Amino Acid', '', ''),
  ('Supplement 653', 'Mineral', '', ''),
  ('Supplement 654', 'Vitamin', '', ''),
  ('Supplement 655', 'Electrolyte', '', ''),
  ('Supplement 656', 'Adaptogen', '', ''),
  ('Supplement 657', 'Vitamin', '', ''),
  ('Supplement 658', 'Adaptogen', '', ''),
  ('Supplement 659', 'Botanical', '', ''),
  ('Supplement 660', 'Mineral', '', ''),
  ('Supplement 661', 'Mineral', '', ''),
  ('Supplement 662', 'Botanical', '', ''),
  ('Supplement 663', 'Mineral', '', ''),
  ('Supplement 664', 'Mineral', '', ''),
  ('Supplement 665', 'Mineral', '', ''),
  ('Supplement 666', 'Vitamin', '', ''),
  ('Supplement 667', 'Probiotic', '', ''),
  ('Supplement 668', 'Amino Acid', '', ''),
  ('Supplement 669', 'Vitamin', '', ''),
  ('Supplement 670', 'Electrolyte', '', ''),
  ('Supplement 671', 'Adaptogen', '', ''),
  ('Supplement 672', 'Vitamin', '', ''),
  ('Supplement 673', 'Adaptogen', '', ''),
  ('Supplement 674', 'Adaptogen', '', ''),
  ('Supplement 675', 'Mineral', '', ''),
  ('Supplement 676', 'Adaptogen', '', ''),
  ('Supplement 677', 'Probiotic', '', ''),
  ('Supplement 678', 'Adaptogen', '', ''),
  ('Supplement 679', 'Probiotic', '', ''),
  ('Supplement 680', 'Mineral', '', ''),
  ('Supplement 681', 'Vitamin', '', ''),
  ('Supplement 682', 'Vitamin', '', ''),
  ('Supplement 683', 'Amino Acid', '', ''),
  ('Supplement 684', 'Vitamin', '', ''),
  ('Supplement 685', 'Adaptogen', '', ''),
  ('Supplement 686', 'Amino Acid', '', ''),
  ('Supplement 687', 'Adaptogen', '', ''),
  ('Supplement 688', 'Probiotic', '', ''),
  ('Supplement 689', 'Electrolyte', '', ''),
  ('Supplement 690', 'Probiotic', '', ''),
  ('Supplement 691', 'Electrolyte', '', ''),
  ('Supplement 692', 'Botanical', '', ''),
  ('Supplement 693', 'Probiotic', '', ''),
  ('Supplement 694', 'Botanical', '', ''),
  ('Supplement 695', 'Probiotic', '', ''),
  ('Supplement 696', 'Probiotic', '', ''),
  ('Supplement 697', 'Amino Acid', '', ''),
  ('Supplement 698', 'Probiotic', '', ''),
  ('Supplement 699', 'Botanical', '', ''),
  ('Supplement 700', 'Vitamin', '', ''),
  ('Supplement 701', 'Electrolyte', '', ''),
  ('Supplement 702', 'Amino Acid', '', ''),
  ('Supplement 703', 'Vitamin', '', ''),
  ('Supplement 704', 'Electrolyte', '', ''),
  ('Supplement 705', 'Amino Acid', '', ''),
  ('Supplement 706', 'Electrolyte', '', ''),
  ('Supplement 707', 'Vitamin', '', ''),
  ('Supplement 708', 'Amino Acid', '', ''),
  ('Supplement 709', 'Electrolyte', '', ''),
  ('Supplement 710', 'Electrolyte', '', ''),
  ('Supplement 711', 'Probiotic', '', ''),
  ('Supplement 712', 'Vitamin', '', ''),
  ('Supplement 713', 'Botanical', '', ''),
  ('Supplement 714', 'Adaptogen', '', ''),
  ('Supplement 715', 'Electrolyte', '', ''),
  ('Supplement 716', 'Probiotic', '', ''),
  ('Supplement 717', 'Mineral', '', ''),
  ('Supplement 718', 'Electrolyte', '', ''),
  ('Supplement 719', 'Amino Acid', '', ''),
  ('Supplement 720', 'Electrolyte', '', ''),
  ('Supplement 721', 'Vitamin', '', ''),
  ('Supplement 722', 'Mineral', '', ''),
  ('Supplement 723', 'Amino Acid', '', ''),
  ('Supplement 724', 'Adaptogen', '', ''),
  ('Supplement 725', 'Probiotic', '', ''),
  ('Supplement 726', 'Electrolyte', '', ''),
  ('Supplement 727', 'Probiotic', '', ''),
  ('Supplement 728', 'Electrolyte', '', ''),
  ('Supplement 729', 'Botanical', '', ''),
  ('Supplement 730', 'Botanical', '', ''),
  ('Supplement 731', 'Electrolyte', '', ''),
  ('Supplement 732', 'Botanical', '', ''),
  ('Supplement 733', 'Electrolyte', '', ''),
  ('Supplement 734', 'Electrolyte', '', ''),
  ('Supplement 735', 'Amino Acid', '', ''),
  ('Supplement 736', 'Electrolyte', '', ''),
  ('Supplement 737', 'Vitamin', '', ''),
  ('Supplement 738', 'Amino Acid', '', ''),
  ('Supplement 739', 'Electrolyte', '', ''),
  ('Supplement 740', 'Electrolyte', '', ''),
  ('Supplement 741', 'Amino Acid', '', ''),
  ('Supplement 742', 'Mineral', '', ''),
  ('Supplement 743', 'Vitamin', '', ''),
  ('Supplement 744', 'Probiotic', '', ''),
  ('Supplement 745', 'Adaptogen', '', ''),
  ('Supplement 746', 'Vitamin', '', ''),
  ('Supplement 747', 'Amino Acid', '', ''),
  ('Supplement 748', 'Botanical', '', ''),
  ('Supplement 749', 'Mineral', '', ''),
  ('Supplement 750', 'Adaptogen', '', '')
ON CONFLICT (name) DO NOTHING;