INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 1', 'Vitamin', '', ''),
  ('Supplement 2', 'Amino Acid', '', ''),
  ('Supplement 3', 'Adaptogen', '', ''),
  ('Supplement 4', 'Amino Acid', '', ''),
  ('Supplement 5', 'Botanical', '', ''),
  ('Supplement 6', 'Electrolyte', '', ''),
  ('Supplement 7', 'Amino Acid', '', ''),
  ('Supplement 8', 'Botanical', '', ''),
  ('Supplement 9', 'Adaptogen', '', ''),
  ('Supplement 10', 'Botanical', '', ''),
  ('Supplement 11', 'Botanical', '', ''),
  ('Supplement 12', 'Probiotic', '', ''),
  ('Supplement 13', 'Amino Acid', '', ''),
  ('Supplement 14', 'Botanical', '', ''),
  ('Supplement 15', 'Mineral', '', ''),
  ('Supplement 16', 'Vitamin', '', ''),
  ('Supplement 17', 'Electrolyte', '', ''),
  ('Supplement 18', 'Adaptogen', '', ''),
  ('Supplement 19', 'Electrolyte', '', ''),
  ('Supplement 20', 'Vitamin', '', ''),
  ('Supplement 21', 'Probiotic', '', ''),
  ('Supplement 22', 'Adaptogen', '', ''),
  ('Supplement 23', 'Electrolyte', '', ''),
  ('Supplement 24', 'Adaptogen', '', ''),
  ('Supplement 25', 'Amino Acid', '', ''),
  ('Supplement 26', 'Probiotic', '', ''),
  ('Supplement 27', 'Mineral', '', ''),
  ('Supplement 28', 'Amino Acid', '', ''),
  ('Supplement 29', 'Electrolyte', '', ''),
  ('Supplement 30', 'Probiotic', '', ''),
  ('Supplement 31', 'Botanical', '', ''),
  ('Supplement 32', 'Electrolyte', '', ''),
  ('Supplement 33', 'Electrolyte', '', ''),
  ('Supplement 34', 'Botanical', '', ''),
  ('Supplement 35', 'Adaptogen', '', ''),
  ('Supplement 36', 'Probiotic', '', ''),
  ('Supplement 37', 'Adaptogen', '', ''),
  ('Supplement 38', 'Amino Acid', '', ''),
  ('Supplement 39', 'Probiotic', '', ''),
  ('Supplement 40', 'Electrolyte', '', ''),
  ('Supplement 41', 'Adaptogen', '', ''),
  ('Supplement 42', 'Vitamin', '', ''),
  ('Supplement 43', 'Vitamin', '', ''),
  ('Supplement 44', 'Amino Acid', '', ''),
  ('Supplement 45', 'Vitamin', '', ''),
  ('Supplement 46', 'Probiotic', '', ''),
  ('Supplement 47', 'Mineral', '', ''),
  ('Supplement 48', 'Botanical', '', ''),
  ('Supplement 49', 'Electrolyte', '', ''),
  ('Supplement 50', 'Adaptogen', '', ''),
  ('Supplement 51', 'Electrolyte', '', ''),
  ('Supplement 52', 'Botanical', '', ''),
  ('Supplement 53', 'Botanical', '', ''),
  ('Supplement 54', 'Vitamin', '', ''),
  ('Supplement 55', 'Probiotic', '', ''),
  ('Supplement 56', 'Vitamin', '', ''),
  ('Supplement 57', 'Vitamin', '', ''),
  ('Supplement 58', 'Mineral', '', ''),
  ('Supplement 59', 'Vitamin', '', ''),
  ('Supplement 60', 'Amino Acid', '', ''),
  ('Supplement 61', 'Probiotic', '', ''),
  ('Supplement 62', 'Mineral', '', ''),
  ('Supplement 63', 'Probiotic', '', ''),
  ('Supplement 64', 'Amino Acid', '', ''),
  ('Supplement 65', 'Probiotic', '', ''),
  ('Supplement 66', 'Adaptogen', '', ''),
  ('Supplement 67', 'Electrolyte', '', ''),
  ('Supplement 68', 'Botanical', '', ''),
  ('Supplement 69', 'Probiotic', '', ''),
  ('Supplement 70', 'Mineral', '', ''),
  ('Supplement 71', 'Botanical', '', ''),
  ('Supplement 72', 'Adaptogen', '', ''),
  ('Supplement 73', 'Amino Acid', '', ''),
  ('Supplement 74', 'Probiotic', '', ''),
  ('Supplement 75', 'Electrolyte', '', ''),
  ('Supplement 76', 'Adaptogen', '', ''),
  ('Supplement 77', 'Mineral', '', ''),
  ('Supplement 78', 'Electrolyte', '', ''),
  ('Supplement 79', 'Adaptogen', '', ''),
  ('Supplement 80', 'Vitamin', '', ''),
  ('Supplement 81', 'Vitamin', '', ''),
  ('Supplement 82', 'Amino Acid', '', ''),
  ('Supplement 83', 'Electrolyte', '', ''),
  ('Supplement 84', 'Adaptogen', '', ''),
  ('Supplement 85', 'Electrolyte', '', ''),
  ('Supplement 86', 'Probiotic', '', ''),
  ('Supplement 87', 'Amino Acid', '', ''),
  ('Supplement 88', 'Botanical', '', ''),
  ('Supplement 89', 'Amino Acid', '', ''),
  ('Supplement 90', 'Botanical', '', ''),
  ('Supplement 91', 'Adaptogen', '', ''),
  ('Supplement 92', 'Adaptogen', '', ''),
  ('Supplement 93', 'Mineral', '', ''),
  ('Supplement 94', 'Vitamin', '', ''),
  ('Supplement 95', 'Electrolyte', '', ''),
  ('Supplement 96', 'Adaptogen', '', ''),
  ('Supplement 97', 'Mineral', '', ''),
  ('Supplement 98', 'Mineral', '', ''),
  ('Supplement 99', 'Amino Acid', '', ''),
  ('Supplement 100', 'Electrolyte', '', ''),
  ('Supplement 101', 'Mineral', '', ''),
  ('Supplement 102', 'Electrolyte', '', ''),
  ('Supplement 103', 'Electrolyte', '', ''),
  ('Supplement 104', 'Vitamin', '', ''),
  ('Supplement 105', 'Probiotic', '', ''),
  ('Supplement 106', 'Botanical', '', ''),
  ('Supplement 107', 'Vitamin', '', ''),
  ('Supplement 108', 'Vitamin', '', ''),
  ('Supplement 109', 'Probiotic', '', ''),
  ('Supplement 110', 'Vitamin', '', ''),
  ('Supplement 111', 'Amino Acid', '', ''),
  ('Supplement 112', 'Botanical', '', ''),
  ('Supplement 113', 'Vitamin', '', ''),
  ('Supplement 114', 'Mineral', '', ''),
  ('Supplement 115', 'Mineral', '', ''),
  ('Supplement 116', 'Mineral', '', ''),
  ('Supplement 117', 'Mineral', '', ''),
  ('Supplement 118', 'Botanical', '', ''),
  ('Supplement 119', 'Amino Acid', '', ''),
  ('Supplement 120', 'Electrolyte', '', ''),
  ('Supplement 121', 'Botanical', '', ''),
  ('Supplement 122', 'Electrolyte', '', ''),
  ('Supplement 123', 'Amino Acid', '', ''),
  ('Supplement 124', 'Electrolyte', '', ''),
  ('Supplement 125', 'Amino Acid', '', ''),
  ('Supplement 126', 'Vitamin', '', ''),
  ('Supplement 127', 'Botanical', '', ''),
  ('Supplement 128', 'Adaptogen', '', ''),
  ('Supplement 129', 'Botanical', '', ''),
  ('Supplement 130', 'Probiotic', '', ''),
  ('Supplement 131', 'Mineral', '', ''),
  ('Supplement 132', 'Vitamin', '', ''),
  ('Supplement 133', 'Adaptogen', '', ''),
  ('Supplement 134', 'Electrolyte', '', ''),
  ('Supplement 135', 'Vitamin', '', ''),
  ('Supplement 136', 'Amino Acid', '', ''),
  ('Supplement 137', 'Botanical', '', ''),
  ('Supplement 138', 'Amino Acid', '', ''),
  ('Supplement 139', 'Amino Acid', '', ''),
  ('Supplement 140', 'Adaptogen', '', ''),
  ('Supplement 141', 'Mineral', '', ''),
  ('Supplement 142', 'Electrolyte', '', ''),
  ('Supplement 143', 'Mineral', '', ''),
  ('Supplement 144', 'Adaptogen', '', ''),
  ('Supplement 145', 'Vitamin', '', ''),
  ('Supplement 146', 'Amino Acid', '', ''),
  ('Supplement 147', 'Vitamin', '', ''),
  ('Supplement 148', 'Vitamin', '', ''),
  ('Supplement 149', 'Electrolyte', '', ''),
  ('Supplement 150', 'Adaptogen', '', ''),
  ('Supplement 151', 'Adaptogen', '', ''),
  ('Supplement 152', 'Probiotic', '', ''),
  ('Supplement 153', 'Adaptogen', '', ''),
  ('Supplement 154', 'Adaptogen', '', ''),
  ('Supplement 155', 'Vitamin', '', ''),
  ('Supplement 156', 'Adaptogen', '', ''),
  ('Supplement 157', 'Amino Acid', '', ''),
  ('Supplement 158', 'Adaptogen', '', ''),
  ('Supplement 159', 'Vitamin', '', ''),
  ('Supplement 160', 'Probiotic', '', ''),
  ('Supplement 161', 'Adaptogen', '', ''),
  ('Supplement 162', 'Amino Acid', '', ''),
  ('Supplement 163', 'Botanical', '', ''),
  ('Supplement 164', 'Vitamin', '', ''),
  ('Supplement 165', 'Vitamin', '', ''),
  ('Supplement 166', 'Vitamin', '', ''),
  ('Supplement 167', 'Electrolyte', '', ''),
  ('Supplement 168', 'Probiotic', '', ''),
  ('Supplement 169', 'Probiotic', '', ''),
  ('Supplement 170', 'Electrolyte', '', ''),
  ('Supplement 171', 'Mineral', '', ''),
  ('Supplement 172', 'Probiotic', '', ''),
  ('Supplement 173', 'Probiotic', '', ''),
  ('Supplement 174', 'Amino Acid', '', ''),
  ('Supplement 175', 'Mineral', '', ''),
  ('Supplement 176', 'Electrolyte', '', ''),
  ('Supplement 177', 'Amino Acid', '', ''),
  ('Supplement 178', 'Botanical', '', ''),
  ('Supplement 179', 'Electrolyte', '', ''),
  ('Supplement 180', 'Electrolyte', '', ''),
  ('Supplement 181', 'Probiotic', '', ''),
  ('Supplement 182', 'Amino Acid', '', ''),
  ('Supplement 183', 'Adaptogen', '', ''),
  ('Supplement 184', 'Botanical', '', ''),
  ('Supplement 185', 'Probiotic', '', ''),
  ('Supplement 186', 'Botanical', '', ''),
  ('Supplement 187', 'Mineral', '', ''),
  ('Supplement 188', 'Adaptogen', '', ''),
  ('Supplement 189', 'Vitamin', '', ''),
  ('Supplement 190', 'Botanical', '', ''),
  ('Supplement 191', 'Probiotic', '', ''),
  ('Supplement 192', 'Botanical', '', ''),
  ('Supplement 193', 'Adaptogen', '', ''),
  ('Supplement 194', 'Electrolyte', '', ''),
  ('Supplement 195', 'Electrolyte', '', ''),
  ('Supplement 196', 'Vitamin', '', ''),
  ('Supplement 197', 'Botanical', '', ''),
  ('Supplement 198', 'Probiotic', '', ''),
  ('Supplement 199', 'Vitamin', '', ''),
  ('Supplement 200', 'Adaptogen', '', ''),
  ('Supplement 201', 'Electrolyte', '', ''),
  ('Supplement 202', 'Mineral', '', ''),
  ('Supplement 203', 'Probiotic', '', ''),
  ('Supplement 204', 'Amino Acid', '', ''),
  ('Supplement 205', 'Mineral', '', ''),
  ('Supplement 206', 'Mineral', '', ''),
  ('Supplement 207', 'Amino Acid', '', ''),
  ('Supplement 208', 'Botanical', '', ''),
  ('Supplement 209', 'Amino Acid', '', ''),
  ('Supplement 210', 'Botanical', '', ''),
  ('Supplement 211', 'Botanical', '', ''),
  ('Supplement 212', 'Amino Acid', '', ''),
  ('Supplement 213', 'Probiotic', '', ''),
  ('Supplement 214', 'Amino Acid', '', ''),
  ('Supplement 215', 'Adaptogen', '', ''),
  ('Supplement 216', 'Vitamin', '', ''),
  ('Supplement 217', 'Electrolyte', '', ''),
  ('Supplement 218', 'Mineral', '', ''),
  ('Supplement 219', 'Electrolyte', '', ''),
  ('Supplement 220', 'Botanical', '', ''),
  ('Supplement 221', 'Probiotic', '', ''),
  ('Supplement 222', 'Adaptogen', '', ''),
  ('Supplement 223', 'Amino Acid', '', ''),
  ('Supplement 224', 'Adaptogen', '', ''),
  ('Supplement 225', 'Probiotic', '', ''),
  ('Supplement 226', 'Botanical', '', ''),
  ('Supplement 227', 'Amino Acid', '', ''),
  ('Supplement 228', 'Amino Acid', '', ''),
  ('Supplement 229', 'Adaptogen', '', ''),
  ('Supplement 230', 'Mineral', '', ''),
  ('Supplement 231', 'Probiotic', '', ''),
  ('Supplement 232', 'Vitamin', '', ''),
  ('Supplement 233', 'Adaptogen', '', ''),
  ('Supplement 234', 'Botanical', '', ''),
  ('Supplement 235', 'Mineral', '', ''),
  ('Supplement 236', 'Electrolyte', '', ''),
  ('Supplement 237', 'Vitamin', '', ''),
  ('Supplement 238', 'Probiotic', '', ''),
  ('Supplement 239', 'Mineral', '', ''),
  ('Supplement 240', 'Vitamin', '', ''),
  ('Supplement 241', 'Adaptogen', '', ''),
  ('Supplement 242', 'Probiotic', '', ''),
  ('Supplement 243', 'Botanical', '', ''),
  ('Supplement 244', 'Electrolyte', '', ''),
  ('Supplement 245', 'Vitamin', '', ''),
  ('Supplement 246', 'Probiotic', '', ''),
  ('Supplement 247', 'Adaptogen', '', ''),
  ('Supplement 248', 'Amino Acid', '', ''),
  ('Supplement 249', 'Electrolyte', '', ''),
  ('Supplement 250', 'Vitamin', '', '')
ON CONFLICT (name) DO NOTHING;