INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 251', 'Botanical', '', ''),
  ('Supplement 252', 'Vitamin', '', ''),
  ('Supplement 253', 'Mineral', '', ''),
  ('Supplement 254', 'Mineral', '', ''),
  ('Supplement 255', 'Adaptogen', '', ''),
  ('Supplement 256', 'Probiotic', '', ''),
  ('Supplement 257', 'Botanical', '', ''),
  ('Supplement 258', 'Electrolyte', '', ''),
  ('Supplement 259', 'Probiotic', '', ''),
  ('Supplement 260', 'Vitamin', '', ''),
  ('Supplement 261', 'Vitamin', '', ''),
  ('Supplement 262', 'Adaptogen', '', ''),
  ('Supplement 263', 'Mineral', '', ''),
  ('Supplement 264', 'Amino Acid', '', ''),
  ('Supplement 265', 'Probiotic', '', ''),
  ('Supplement 266', 'Botanical', '', ''),
  ('Supplement 267', 'Probiotic', '', ''),
  ('Supplement 268', 'Botanical', '', ''),
  ('Supplement 269', 'Vitamin', '', ''),
  ('Supplement 270', 'Electrolyte', '', ''),
  ('Supplement 271', 'Electrolyte', '', ''),
  ('Supplement 272', 'Electrolyte', '', ''),
  ('Supplement 273', 'Adaptogen', '', ''),
  ('Supplement 274', 'Amino Acid', '', ''),
  ('Supplement 275', 'Amino Acid', '', ''),
  ('Supplement 276', 'Vitamin', '', ''),
  ('Supplement 277', 'Probiotic', '', ''),
  ('Supplement 278', 'Botanical', '', ''),
  ('Supplement 279', 'Adaptogen', '', ''),
  ('Supplement 280', 'Probiotic', '', ''),
  ('Supplement 281', 'Botanical', '', ''),
  ('Supplement 282', 'Probiotic', '', ''),
  ('Supplement 283', 'Botanical', '', ''),
  ('Supplement 284', 'Electrolyte', '', ''),
  ('Supplement 285', 'Electrolyte', '', ''),
  ('Supplement 286', 'Vitamin', '', ''),
  ('Supplement 287', 'Amino Acid', '', ''),
  ('Supplement 288', 'Electrolyte', '', ''),
  ('Supplement 289', 'Adaptogen', '', ''),
  ('Supplement 290', 'Mineral', '', ''),
  ('Supplement 291', 'Probiotic', '', ''),
  ('Supplement 292', 'Electrolyte', '', ''),
  ('Supplement 293', 'Adaptogen', '', ''),
  ('Supplement 294', 'Electrolyte', '', ''),
  ('Supplement 295', 'Adaptogen', '', ''),
  ('Supplement 296', 'Adaptogen', '', ''),
  ('Supplement 297', 'Electrolyte', '', ''),
  ('Supplement 298', 'Mineral', '', ''),
  ('Supplement 299', 'Electrolyte', '', ''),
  ('Supplement 300', 'Adaptogen', '', ''),
  ('Supplement 301', 'Amino Acid', '', ''),
  ('Supplement 302', 'Adaptogen', '', ''),
  ('Supplement 303', 'Mineral', '', ''),
  ('Supplement 304', 'Adaptogen', '', ''),
  ('Supplement 305', 'Vitamin', '', ''),
  ('Supplement 306', 'Probiotic', '', ''),
  ('Supplement 307', 'Amino Acid', '', ''),
  ('Supplement 308', 'Botanical', '', ''),
  ('Supplement 309', 'Mineral', '', ''),
  ('Supplement 310', 'Botanical', '', ''),
  ('Supplement 311', 'Electrolyte', '', ''),
  ('Supplement 312', 'Amino Acid', '', ''),
  ('Supplement 313', 'Mineral', '', ''),
  ('Supplement 314', 'Adaptogen', '', ''),
  ('Supplement 315', 'Botanical', '', ''),
  ('Supplement 316', 'Electrolyte', '', ''),
  ('Supplement 317', 'Electrolyte', '', ''),
  ('Supplement 318', 'Adaptogen', '', ''),
  ('Supplement 319', 'Botanical', '', ''),
  ('Supplement 320', 'Adaptogen', '', ''),
  ('Supplement 321', 'Adaptogen', '', ''),
  ('Supplement 322', 'Mineral', '', ''),
  ('Supplement 323', 'Amino Acid', '', ''),
  ('Supplement 324', 'Electrolyte', '', ''),
  ('Supplement 325', 'Adaptogen', '', ''),
  ('Supplement 326', 'Botanical', '', ''),
  ('Supplement 327', 'Botanical', '', ''),
  ('Supplement 328', 'Adaptogen', '', ''),
  ('Supplement 329', 'Vitamin', '', ''),
  ('Supplement 330', 'Amino Acid', '', ''),
  ('Supplement 331', 'Vitamin', '', ''),
  ('Supplement 332', 'Electrolyte', '', ''),
  ('Supplement 333', 'Adaptogen', '', ''),
  ('Supplement 334', 'Amino Acid', '', ''),
  ('Supplement 335', 'Vitamin', '', ''),
  ('Supplement 336', 'Mineral', '', ''),
  ('Supplement 337', 'Amino Acid', '', ''),
  ('Supplement 338', 'Amino Acid', '', ''),
  ('Supplement 339', 'Vitamin', '', ''),
  ('Supplement 340', 'Electrolyte', '', ''),
  ('Supplement 341', 'Botanical', '', ''),
  ('Supplement 342', 'Probiotic', '', ''),
  ('Supplement 343', 'Botanical', '', ''),
  ('Supplement 344', 'Probiotic', '', ''),
  ('Supplement 345', 'Adaptogen', '', ''),
  ('Supplement 346', 'Probiotic', '', ''),
  ('Supplement 347', 'Probiotic', '', ''),
  ('Supplement 348', 'Adaptogen', '', ''),
  ('Supplement 349', 'Probiotic', '', ''),
  ('Supplement 350', 'Electrolyte', '', ''),
  ('Supplement 351', 'Vitamin', '', ''),
  ('Supplement 352', 'Vitamin', '', ''),
  ('Supplement 353', 'Vitamin', '', ''),
  ('Supplement 354', 'Amino Acid', '', ''),
  ('Supplement 355', 'Probiotic', '', ''),
  ('Supplement 356', 'Vitamin', '', ''),
  ('Supplement 357', 'Mineral', '', ''),
  ('Supplement 358', 'Amino Acid', '', ''),
  ('Supplement 359', 'Probiotic', '', ''),
  ('Supplement 360', 'Botanical', '', ''),
  ('Supplement 361', 'Amino Acid', '', ''),
  ('Supplement 362', 'Electrolyte', '', ''),
  ('Supplement 363', 'Adaptogen', '', ''),
  ('Supplement 364', 'Probiotic', '', ''),
  ('Supplement 365', 'Amino Acid', '', ''),
  ('Supplement 366', 'Probiotic', '', ''),
  ('Supplement 367', 'Vitamin', '', ''),
  ('Supplement 368', 'Mineral', '', ''),
  ('Supplement 369', 'Adaptogen', '', ''),
  ('Supplement 370', 'Botanical', '', ''),
  ('Supplement 371', 'Electrolyte', '', ''),
  ('Supplement 372', 'Botanical', '', ''),
  ('Supplement 373', 'Mineral', '', ''),
  ('Supplement 374', 'Botanical', '', ''),
  ('Supplement 375', 'Vitamin', '', ''),
  ('Supplement 376', 'Amino Acid', '', ''),
  ('Supplement 377', 'Vitamin', '', ''),
  ('Supplement 378', 'Mineral', '', ''),
  ('Supplement 379', 'Vitamin', '', ''),
  ('Supplement 380', 'Adaptogen', '', ''),
  ('Supplement 381', 'Amino Acid', '', ''),
  ('Supplement 382', 'Amino Acid', '', ''),
  ('Supplement 383', 'Amino Acid', '', ''),
  ('Supplement 384', 'Electrolyte', '', ''),
  ('Supplement 385', 'Mineral', '', ''),
  ('Supplement 386', 'Adaptogen', '', ''),
  ('Supplement 387', 'Mineral', '', ''),
  ('Supplement 388', 'Amino Acid', '', ''),
  ('Supplement 389', 'Botanical', '', ''),
  ('Supplement 390', 'Electrolyte', '', ''),
  ('Supplement 391', 'Vitamin', '', ''),
  ('Supplement 392', 'Vitamin', '', ''),
  ('Supplement 393', 'Botanical', '', ''),
  ('Supplement 394', 'Vitamin', '', ''),
  ('Supplement 395', 'Electrolyte', '', ''),
  ('Supplement 396', 'Amino Acid', '', ''),
  ('Supplement 397', 'Vitamin', '', ''),
  ('Supplement 398', 'Probiotic', '', ''),
  ('Supplement 399', 'Electrolyte', '', ''),
  ('Supplement 400', 'Adaptogen', '', ''),
  ('Supplement 401', 'Electrolyte', '', ''),
  ('Supplement 402', 'Mineral', '', ''),
  ('Supplement 403', 'Amino Acid', '', ''),
  ('Supplement 404', 'Adaptogen', '', ''),
  ('Supplement 405', 'Probiotic', '', ''),
  ('Supplement 406', 'Adaptogen', '', ''),
  ('Supplement 407', 'Adaptogen', '', ''),
  ('Supplement 408', 'Botanical', '', ''),
  ('Supplement 409', 'Adaptogen', '', ''),
  ('Supplement 410', 'Mineral', '', ''),
  ('Supplement 411', 'Adaptogen', '', ''),
  ('Supplement 412', 'Adaptogen', '', ''),
  ('Supplement 413', 'Mineral', '', ''),
  ('Supplement 414', 'Amino Acid', '', ''),
  ('Supplement 415', 'Amino Acid', '', ''),
  ('Supplement 416', 'Probiotic', '', ''),
  ('Supplement 417', 'Vitamin', '', ''),
  ('Supplement 418', 'Mineral', '', ''),
  ('Supplement 419', 'Electrolyte', '', ''),
  ('Supplement 420', 'Botanical', '', ''),
  ('Supplement 421', 'Mineral', '', ''),
  ('Supplement 422', 'Electrolyte', '', ''),
  ('Supplement 423', 'Electrolyte', '', ''),
  ('Supplement 424', 'Botanical', '', ''),
  ('Supplement 425', 'Vitamin', '', ''),
  ('Supplement 426', 'Botanical', '', ''),
  ('Supplement 427', 'Amino Acid', '', ''),
  ('Supplement 428', 'Adaptogen', '', ''),
  ('Supplement 429', 'Electrolyte', '', ''),
  ('Supplement 430', 'Electrolyte', '', ''),
  ('Supplement 431', 'Electrolyte', '', ''),
  ('Supplement 432', 'Probiotic', '', ''),
  ('Supplement 433', 'Vitamin', '', ''),
  ('Supplement 434', 'Mineral', '', ''),
  ('Supplement 435', 'Vitamin', '', ''),
  ('Supplement 436', 'Electrolyte', '', ''),
  ('Supplement 437', 'Adaptogen', '', ''),
  ('Supplement 438', 'Electrolyte', '', ''),
  ('Supplement 439', 'Adaptogen', '', ''),
  ('Supplement 440', 'Botanical', '', ''),
  ('Supplement 441', 'Electrolyte', '', ''),
  ('Supplement 442', 'Mineral', '', ''),
  ('Supplement 443', 'Vitamin', '', ''),
  ('Supplement 444', 'Amino Acid', '', ''),
  ('Supplement 445', 'Vitamin', '', ''),
  ('Supplement 446', 'Amino Acid', '', ''),
  ('Supplement 447', 'Mineral', '', ''),
  ('Supplement 448', 'Mineral', '', ''),
  ('Supplement 449', 'Mineral', '', ''),
  ('Supplement 450', 'Vitamin', '', ''),
  ('Supplement 451', 'Mineral', '', ''),
  ('Supplement 452', 'Probiotic', '', ''),
  ('Supplement 453', 'Amino Acid', '', ''),
  ('Supplement 454', 'Botanical', '', ''),
  ('Supplement 455', 'Mineral', '', ''),
  ('Supplement 456', 'Adaptogen', '', ''),
  ('Supplement 457', 'Amino Acid', '', ''),
  ('Supplement 458', 'Adaptogen', '', ''),
  ('Supplement 459', 'Electrolyte', '', ''),
  ('Supplement 460', 'Mineral', '', ''),
  ('Supplement 461', 'Adaptogen', '', ''),
  ('Supplement 462', 'Botanical', '', ''),
  ('Supplement 463', 'Vitamin', '', ''),
  ('Supplement 464', 'Vitamin', '', ''),
  ('Supplement 465', 'Probiotic', '', ''),
  ('Supplement 466', 'Probiotic', '', ''),
  ('Supplement 467', 'Amino Acid', '', ''),
  ('Supplement 468', 'Probiotic', '', ''),
  ('Supplement 469', 'Probiotic', '', ''),
  ('Supplement 470', 'Vitamin', '', ''),
  ('Supplement 471', 'Probiotic', '', ''),
  ('Supplement 472', 'Mineral', '', ''),
  ('Supplement 473', 'Botanical', '', ''),
  ('Supplement 474', 'Adaptogen', '', ''),
  ('Supplement 475', 'Mineral', '', ''),
  ('Supplement 476', 'Mineral', '', ''),
  ('Supplement 477', 'Mineral', '', ''),
  ('Supplement 478', 'Botanical', '', ''),
  ('Supplement 479', 'Mineral', '', ''),
  ('Supplement 480', 'Adaptogen', '', ''),
  ('Supplement 481', 'Electrolyte', '', ''),
  ('Supplement 482', 'Amino Acid', '', ''),
  ('Supplement 483', 'Botanical', '', ''),
  ('Supplement 484', 'Amino Acid', '', ''),
  ('Supplement 485', 'Adaptogen', '', ''),
  ('Supplement 486', 'Vitamin', '', ''),
  ('Supplement 487', 'Probiotic', '', ''),
  ('Supplement 488', 'Botanical', '', ''),
  ('Supplement 489', 'Botanical', '', ''),
  ('Supplement 490', 'Electrolyte', '', ''),
  ('Supplement 491', 'Electrolyte', '', ''),
  ('Supplement 492', 'Botanical', '', ''),
  ('Supplement 493', 'Amino Acid', '', ''),
  ('Supplement 494', 'Vitamin', '', ''),
  ('Supplement 495', 'Mineral', '', ''),
  ('Supplement 496', 'Mineral', '', ''),
  ('Supplement 497', 'Vitamin', '', ''),
  ('Supplement 498', 'Vitamin', '', ''),
  ('Supplement 499', 'Mineral', '', ''),
  ('Supplement 500', 'Vitamin', '', '')
ON CONFLICT (name) DO NOTHING;