INSERT INTO interactions (supplement_id, medication_id, severity, mechanism, evidence, notes)
VALUES
  (47, 12, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (229, 127, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (926, 66, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (262, 125, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (567, 62, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (923, 23, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (281, 96, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (604, 108, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (306, 121, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (890, 33, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (455, 27, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (773, 116, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (948, 98, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (814, 86, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (568, 57, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (886, 108, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (693, 47, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (717, 50, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (92, 77, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (20, 136, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (885, 86, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (895, 124, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (131, 78, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (644, 123, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (28, 116, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (903, 40, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (490, 68, 'Moderate', 'Additive effect', 'B', 'Auto-generated interaction'),
  (289, 79, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (929, 33, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (901, 11, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (655, 130, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (382, 131, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (560, 82, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (663, 97, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (673, 132, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (408, 125, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (58, 117, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (875, 104, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (350, 25, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (971, 13, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (3, 10, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (971, 93, 'Low', 'Additive effect', 'A', 'Auto-generated interaction'),
  (520, 125, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (260, 23, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (613, 84, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (490, 101, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (235, 84, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (892, 72, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (600, 74, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (10, 59, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (712, 54, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (558, 51, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (130, 150, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (772, 121, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (950, 97, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (815, 61, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (845, 40, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (110, 111, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (138, 77, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (995, 27, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (74, 52, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (642, 123, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (787, 40, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (352, 9, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (122, 45, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (103, 108, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (461, 1, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (299, 68, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (793, 83, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (593, 101, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (872, 10, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (13, 108, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (743, 81, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (211, 76, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (747, 32, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (348, 76, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (405, 35, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (226, 54, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (475, 77, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (840, 101, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (840, 141, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (330, 83, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (233, 96, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (129, 24, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (504, 53, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (204, 120, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (768, 99, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (81, 150, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (256, 131, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (852, 3, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (344, 92, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (198, 11, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (778, 77, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (840, 39, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (795, 47, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (165, 144, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (366, 94, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (161, 30, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (960, 59, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (35, 118, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (380, 33, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (532, 123, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (932, 133, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (144, 149, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (571, 52, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (442, 50, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (387, 63, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (743, 46, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (649, 135, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (485, 134, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (233, 118, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (930, 86, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (91, 12, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (225, 122, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (50, 30, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (167, 138, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (91, 106, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (514, 55, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (409, 149, 'Severe', 'Unknown', 'A', 'Auto-generated interaction'),
  (282, 26, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (140, 40, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (22, 122, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (148, 49, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (147, 136, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (10, 114, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (424, 26, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (548, 150, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (987, 48, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (658, 104, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (334, 146, 'Severe', 'Additive effect', 'C', 'Auto-generated interaction'),
  (682, 74, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (336, 90, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (900, 108, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (893, 10, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (171, 133, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (815, 119, 'Moderate', 'Additive effect', 'B', 'Auto-generated interaction'),
  (713, 81, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (852, 68, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (828, 37, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (681, 9, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (799, 86, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (923, 35, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (569, 100, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (133, 14, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (510, 30, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (642, 45, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (158, 19, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (176, 32, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (418, 121, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (320, 138, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (692, 108, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (731, 78, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (179, 67, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (693, 27, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (100, 102, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (937, 101, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (549, 105, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (692, 27, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (840, 52, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (433, 93, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (960, 142, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (783, 73, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (794, 140, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (744, 3, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (373, 83, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (470, 72, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (948, 23, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (834, 80, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (157, 47, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (295, 124, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (306, 43, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (927, 76, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (701, 25, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (984, 60, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (286, 74, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (220, 30, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (990, 62, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (177, 132, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (602, 125, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (883, 47, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (364, 115, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (265, 49, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (176, 59, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (193, 96, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (191, 84, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (812, 102, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (899, 139, 'Severe', 'Additive effect', 'C', 'Auto-generated interaction'),
  (979, 18, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (514, 148, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (221, 60, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (17, 55, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (307, 111, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (101, 6, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (623, 8, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (165, 127, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (43, 14, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (94, 41, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (822, 53, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (278, 4, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (729, 118, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (374, 74, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (443, 123, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (762, 135, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (118, 78, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (917, 74, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (860, 23, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (697, 40, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (652, 136, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (744, 135, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (883, 57, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (259, 93, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (521, 125, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (351, 21, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (171, 8, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (406, 27, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (840, 89, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (520, 53, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (522, 138, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (37, 140, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (562, 72, 'Severe', 'Additive effect', 'C', 'Auto-generated interaction'),
  (485, 50, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (289, 82, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (293, 71, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (475, 81, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (394, 129, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (474, 23, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (266, 53, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (78, 16, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (144, 89, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (959, 13, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (19, 79, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (627, 142, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (979, 144, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (802, 44, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (231, 106, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (863, 144, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (999, 61, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (434, 150, 'Severe', 'Unknown', 'A', 'Auto-generated interaction'),
  (585, 148, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (406, 125, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (641, 50, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (120, 41, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (907, 19, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (410, 8, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (304, 98, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (344, 6, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (23, 140, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (708, 63, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (296, 31, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (887, 31, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (173, 31, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (668, 102, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (43, 64, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (750, 69, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (586, 105, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (995, 83, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (683, 41, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (523, 61, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (642, 68, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (37, 72, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (16, 34, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (129, 31, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (543, 22, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (597, 76, 'Moderate', 'Additive effect', 'B', 'Auto-generated interaction'),
  (821, 99, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (55, 135, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (855, 144, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (607, 106, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (87, 31, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (532, 95, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (294, 119, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (875, 51, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (326, 4, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (491, 55, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (468, 3, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (675, 46, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (140, 30, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (998, 62, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (914, 61, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (285, 145, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (532, 40, 'Severe', 'Additive effect', 'C', 'Auto-generated interaction'),
  (529, 122, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (281, 69, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (1000, 35, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (451, 55, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (209, 45, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (600, 29, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (28, 43, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (779, 100, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (790, 138, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (731, 55, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (887, 131, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (596, 138, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (746, 94, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (433, 60, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (616, 60, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (662, 39, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (16, 84, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (630, 130, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (853, 131, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (491, 138, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (51, 68, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (50, 111, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (141, 82, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (490, 79, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (385, 7, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (527, 102, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (904, 147, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (252, 143, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (938, 6, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (884, 22, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (216, 114, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (822, 50, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (49, 55, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (707, 108, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (383, 147, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (48, 36, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (185, 114, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (277, 55, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (54, 86, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (970, 131, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (668, 11, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (666, 7, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (421, 45, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (444, 132, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (726, 128, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (87, 40, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (131, 127, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (844, 100, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (313, 100, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (591, 81, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (60, 51, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (128, 25, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (38, 43, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (297, 22, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (823, 110, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (182, 29, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (756, 104, 'Moderate', 'Additive effect', 'B', 'Auto-generated interaction'),
  (731, 67, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (682, 125, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (759, 139, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (284, 138, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (464, 33, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (934, 90, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (536, 38, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (821, 49, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (8, 33, 'Severe', 'Additive effect', 'C', 'Auto-generated interaction'),
  (590, 12, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (530, 48, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (176, 73, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (271, 18, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (36, 27, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (342, 116, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (657, 27, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (1, 144, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (153, 134, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (618, 128, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (874, 147, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (161, 74, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (413, 145, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (567, 114, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (688, 82, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (173, 148, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (110, 51, 'Low', 'Additive effect', 'A', 'Auto-generated interaction'),
  (514, 125, 'High', 'Unknown', 'C', 'Auto-generated interaction'),
  (82, 116, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (902, 49, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (697, 17, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (289, 106, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (833, 7, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (784, 63, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (783, 140, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (823, 99, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (681, 125, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (269, 135, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (472, 50, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (744, 84, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (764, 103, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (629, 126, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (664, 27, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (504, 19, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (102, 119, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (52, 24, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (34, 105, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (777, 95, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (27, 136, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (78, 38, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (282, 115, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (576, 112, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (69, 30, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (272, 68, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (247, 146, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (787, 30, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (573, 89, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (463, 123, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (604, 134, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (564, 136, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (130, 142, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (116, 116, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (636, 140, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (393, 147, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (591, 15, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (20, 113, 'Low', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (659, 32, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (459, 53, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (777, 20, 'Low', 'Unknown', 'B', 'Auto-generated interaction'),
  (299, 59, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (14, 100, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (86, 105, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (191, 140, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (531, 112, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (430, 34, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (211, 116, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (256, 19, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (400, 61, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (259, 130, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (325, 34, 'High', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (595, 75, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (219, 31, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (85, 70, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (771, 144, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (788, 6, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (69, 129, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (264, 81, 'Low', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (192, 59, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (243, 81, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (875, 42, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (626, 50, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (48, 20, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (851, 118, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (198, 68, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (153, 95, 'High', 'Unknown', 'B', 'Auto-generated interaction'),
  (563, 69, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (528, 137, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (667, 41, 'Moderate', 'Unknown', 'C', 'Auto-generated interaction'),
  (818, 138, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (49, 29, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (196, 97, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (956, 26, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (187, 57, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (508, 149, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (839, 16, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (365, 60, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (806, 149, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (764, 145, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (626, 50, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (271, 133, 'High', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (5, 18, 'Severe', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (195, 35, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (662, 39, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (207, 103, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (608, 7, 'High', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (53, 29, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (40, 29, 'Moderate', 'Additive effect', 'B', 'Auto-generated interaction'),
  (3, 131, 'Moderate', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (666, 47, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (715, 76, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (715, 44, 'Severe', 'Absorption reduction', 'B', 'Auto-generated interaction'),
  (958, 112, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (936, 88, 'Severe', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (539, 46, 'Low', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (732, 142, 'Low', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (902, 34, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (609, 138, 'Moderate', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (214, 70, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (319, 135, 'High', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (464, 8, 'Moderate', 'Additive effect', 'C', 'Auto-generated interaction'),
  (446, 70, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (763, 34, 'High', 'Absorption reduction', 'C', 'Auto-generated interaction'),
  (47, 78, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (303, 64, 'Moderate', 'Additive effect', 'A', 'Auto-generated interaction'),
  (754, 102, 'Severe', 'Unknown', 'B', 'Auto-generated interaction'),
  (968, 124, 'Moderate', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (148, 51, 'Low', 'Unknown', 'C', 'Auto-generated interaction'),
  (378, 103, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction'),
  (575, 57, 'Low', 'Additive effect', 'B', 'Auto-generated interaction'),
  (420, 3, 'Severe', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (844, 14, 'Low', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (944, 17, 'Severe', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (811, 34, 'Moderate', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (965, 44, 'High', 'Unknown', 'A', 'Auto-generated interaction'),
  (141, 10, 'Severe', 'Absorption reduction', 'A', 'Auto-generated interaction'),
  (339, 26, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (451, 17, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (779, 46, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (751, 91, 'Low', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (560, 147, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (425, 12, 'Moderate', 'Unknown', 'A', 'Auto-generated interaction'),
  (234, 4, 'High', 'Additive effect', 'A', 'Auto-generated interaction'),
  (829, 54, 'High', 'Additive effect', 'C', 'Auto-generated interaction'),
  (938, 55, 'Moderate', 'Metabolism inhibition', 'A', 'Auto-generated interaction'),
  (361, 45, 'Severe', 'Additive effect', 'B', 'Auto-generated interaction'),
  (403, 2, 'Severe', 'Unknown', 'C', 'Auto-generated interaction'),
  (489, 30, 'High', 'Additive effect', 'B', 'Auto-generated interaction'),
  (284, 149, 'Severe', 'Additive effect', 'A', 'Auto-generated interaction'),
  (690, 130, 'Moderate', 'Metabolism inhibition', 'B', 'Auto-generated interaction'),
  (766, 26, 'Low', 'Unknown', 'A', 'Auto-generated interaction'),
  (654, 63, 'Low', 'Additive effect', 'C', 'Auto-generated interaction'),
  (866, 25, 'High', 'Metabolism inhibition', 'C', 'Auto-generated interaction'),
  (68, 106, 'Moderate', 'Unknown', 'B', 'Auto-generated interaction')
ON CONFLICT (id) DO UPDATE SET
  supplement_id = EXCLUDED.supplement_id, medication_id = EXCLUDED.medication_id, severity = EXCLUDED.severity, mechanism = EXCLUDED.mechanism, evidence = EXCLUDED.evidence, notes = EXCLUDED.notes;