INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 1', 'Vitamin', '', ''),
  ('Supplement 2', 'Amino Acid', '', ''),
  ('Supplement 3', 'Adaptogen', '', ''),
  ('Supplement 4', 'Amino Acid', '', ''),
  ('Supplement 5', 'Botanical', '', ''),
  ('Supplement 6', 'Electrolyte', '', ''),
  ('Supplement 7', 'Amino Acid', '', ''),
  ('Supplement 8', 'Botanical', '', ''),
  ('Supplement 9', 'Adaptogen', '', ''),
  ('Supplement 10', 'Botanical', '', ''),
  ('Supplement 11', 'Botanical', '', ''),
  ('Supplement 12', 'Probiotic', '', ''),
  ('Supplement 13', 'Amino Acid', '', ''),
  ('Supplement 14', 'Botanical', '', ''),
  ('Supplement 15', 'Mineral', '', ''),
  ('Supplement 16', 'Vitamin', '', ''),
  ('Supplement 17', 'Electrolyte', '', ''),
  ('Supplement 18', 'Adaptogen', '', ''),
  ('Supplement 19', 'Electrolyte', '', ''),
  ('Supplement 20', 'Vitamin', '', ''),
  ('Supplement 21', 'Probiotic', '', ''),
  ('Supplement 22', 'Adaptogen', '', ''),
  ('Supplement 23', 'Electrolyte', '', ''),
  ('Supplement 24', 'Adaptogen', '', ''),
  ('Supplement 25', 'Amino Acid', '', ''),
  ('Supplement 26', 'Probiotic', '', ''),
  ('Supplement 27', 'Mineral', '', ''),
  ('Supplement 28', 'Amino Acid', '', ''),
  ('Supplement 29', 'Electrolyte', '', ''),
  ('Supplement 30', 'Probiotic', '', ''),
  ('Supplement 31', 'Botanical', '', ''),
  ('Supplement 32', 'Electrolyte', '', ''),
  ('Supplement 33', 'Electrolyte', '', ''),
  ('Supplement 34', 'Botanical', '', ''),
  ('Supplement 35', 'Adaptogen', '', ''),
  ('Supplement 36', 'Probiotic', '', ''),
  ('Supplement 37', 'Adaptogen', '', ''),
  ('Supplement 38', 'Amino Acid', '', ''),
  ('Supplement 39', 'Probiotic', '', ''),
  ('Supplement 40', 'Electrolyte', '', ''),
  ('Supplement 41', 'Adaptogen', '', ''),
  ('Supplement 42', 'Vitamin', '', ''),
  ('Supplement 43', 'Vitamin', '', ''),
  ('Supplement 44', 'Amino Acid', '', ''),
  ('Supplement 45', 'Vitamin', '', ''),
  ('Supplement 46', 'Probiotic', '', ''),
  ('Supplement 47', 'Mineral', '', ''),
  ('Supplement 48', 'Botanical', '', ''),
  ('Supplement 49', 'Electrolyte', '', ''),
  ('Supplement 50', 'Adaptogen', '', ''),
  ('Supplement 51', 'Electrolyte', '', ''),
  ('Supplement 52', 'Botanical', '', ''),
  ('Supplement 53', 'Botanical', '', ''),
  ('Supplement 54', 'Vitamin', '', ''),
  ('Supplement 55', 'Probiotic', '', ''),
  ('Supplement 56', 'Vitamin', '', ''),
  ('Supplement 57', 'Vitamin', '', ''),
  ('Supplement 58', 'Mineral', '', ''),
  ('Supplement 59', 'Vitamin', '', ''),
  ('Supplement 60', 'Amino Acid', '', ''),
  ('Supplement 61', 'Probiotic', '', ''),
  ('Supplement 62', 'Mineral', '', ''),
  ('Supplement 63', 'Probiotic', '', ''),
  ('Supplement 64', 'Amino Acid', '', ''),
  ('Supplement 65', 'Probiotic', '', ''),
  ('Supplement 66', 'Adaptogen', '', ''),
  ('Supplement 67', 'Electrolyte', '', ''),
  ('Supplement 68', 'Botanical', '', ''),
  ('Supplement 69', 'Probiotic', '', ''),
  ('Supplement 70', 'Mineral', '', ''),
  ('Supplement 71', 'Botanical', '', ''),
  ('Supplement 72', 'Adaptogen', '', ''),
  ('Supplement 73', 'Amino Acid', '', ''),
  ('Supplement 74', 'Probiotic', '', ''),
  ('Supplement 75', 'Electrolyte', '', ''),
  ('Supplement 76', 'Adaptogen', '', ''),
  ('Supplement 77', 'Mineral', '', ''),
  ('Supplement 78', 'Electrolyte', '', ''),
  ('Supplement 79', 'Adaptogen', '', ''),
  ('Supplement 80', 'Vitamin', '', ''),
  ('Supplement 81', 'Vitamin', '', ''),
  ('Supplement 82', 'Amino Acid', '', ''),
  ('Supplement 83', 'Electrolyte', '', ''),
  ('Supplement 84', 'Adaptogen', '', ''),
  ('Supplement 85', 'Electrolyte', '', ''),
  ('Supplement 86', 'Probiotic', '', ''),
  ('Supplement 87', 'Amino Acid', '', ''),
  ('Supplement 88', 'Botanical', '', ''),
  ('Supplement 89', 'Amino Acid', '', ''),
  ('Supplement 90', 'Botanical', '', ''),
  ('Supplement 91', 'Adaptogen', '', ''),
  ('Supplement 92', 'Adaptogen', '', ''),
  ('Supplement 93', 'Mineral', '', ''),
  ('Supplement 94', 'Vitamin', '', ''),
  ('Supplement 95', 'Electrolyte', '', ''),
  ('Supplement 96', 'Adaptogen', '', ''),
  ('Supplement 97', 'Mineral', '', ''),
  ('Supplement 98', 'Mineral', '', ''),
  ('Supplement 99', 'Amino Acid', '', ''),
  ('Supplement 100', 'Electrolyte', '', ''),
  ('Supplement 101', 'Mineral', '', ''),
  ('Supplement 102', 'Electrolyte', '', ''),
  ('Supplement 103', 'Electrolyte', '', ''),
  ('Supplement 104', 'Vitamin', '', ''),
  ('Supplement 105', 'Probiotic', '', ''),
  ('Supplement 106', 'Botanical', '', ''),
  ('Supplement 107', 'Vitamin', '', ''),
  ('Supplement 108', 'Vitamin', '', ''),
  ('Supplement 109', 'Probiotic', '', ''),
  ('Supplement 110', 'Vitamin', '', ''),
  ('Supplement 111', 'Amino Acid', '', ''),
  ('Supplement 112', 'Botanical', '', ''),
  ('Supplement 113', 'Vitamin', '', ''),
  ('Supplement 114', 'Mineral', '', ''),
  ('Supplement 115', 'Mineral', '', ''),
  ('Supplement 116', 'Mineral', '', ''),
  ('Supplement 117', 'Mineral', '', ''),
  ('Supplement 118', 'Botanical', '', ''),
  ('Supplement 119', 'Amino Acid', '', ''),
  ('Supplement 120', 'Electrolyte', '', ''),
  ('Supplement 121', 'Botanical', '', ''),
  ('Supplement 122', 'Electrolyte', '', ''),
  ('Supplement 123', 'Amino Acid', '', ''),
  ('Supplement 124', 'Electrolyte', '', ''),
  ('Supplement 125', 'Amino Acid', '', ''),
  ('Supplement 126', 'Vitamin', '', ''),
  ('Supplement 127', 'Botanical', '', ''),
  ('Supplement 128', 'Adaptogen', '', ''),
  ('Supplement 129', 'Botanical', '', ''),
  ('Supplement 130', 'Probiotic', '', ''),
  ('Supplement 131', 'Mineral', '', ''),
  ('Supplement 132', 'Vitamin', '', ''),
  ('Supplement 133', 'Adaptogen', '', ''),
  ('Supplement 134', 'Electrolyte', '', ''),
  ('Supplement 135', 'Vitamin', '', ''),
  ('Supplement 136', 'Amino Acid', '', ''),
  ('Supplement 137', 'Botanical', '', ''),
  ('Supplement 138', 'Amino Acid', '', ''),
  ('Supplement 139', 'Amino Acid', '', ''),
  ('Supplement 140', 'Adaptogen', '', ''),
  ('Supplement 141', 'Mineral', '', ''),
  ('Supplement 142', 'Electrolyte', '', ''),
  ('Supplement 143', 'Mineral', '', ''),
  ('Supplement 144', 'Adaptogen', '', ''),
  ('Supplement 145', 'Vitamin', '', ''),
  ('Supplement 146', 'Amino Acid', '', ''),
  ('Supplement 147', 'Vitamin', '', ''),
  ('Supplement 148', 'Vitamin', '', ''),
  ('Supplement 149', 'Electrolyte', '', ''),
  ('Supplement 150', 'Adaptogen', '', ''),
  ('Supplement 151', 'Adaptogen', '', ''),
  ('Supplement 152', 'Probiotic', '', ''),
  ('Supplement 153', 'Adaptogen', '', ''),
  ('Supplement 154', 'Adaptogen', '', ''),
  ('Supplement 155', 'Vitamin', '', ''),
  ('Supplement 156', 'Adaptogen', '', ''),
  ('Supplement 157', 'Amino Acid', '', ''),
  ('Supplement 158', 'Adaptogen', '', ''),
  ('Supplement 159', 'Vitamin', '', ''),
  ('Supplement 160', 'Probiotic', '', ''),
  ('Supplement 161', 'Adaptogen', '', ''),
  ('Supplement 162', 'Amino Acid', '', ''),
  ('Supplement 163', 'Botanical', '', ''),
  ('Supplement 164', 'Vitamin', '', ''),
  ('Supplement 165', 'Vitamin', '', ''),
  ('Supplement 166', 'Vitamin', '', ''),
  ('Supplement 167', 'Electrolyte', '', ''),
  ('Supplement 168', 'Probiotic', '', ''),
  ('Supplement 169', 'Probiotic', '', ''),
  ('Supplement 170', 'Electrolyte', '', ''),
  ('Supplement 171', 'Mineral', '', ''),
  ('Supplement 172', 'Probiotic', '', ''),
  ('Supplement 173', 'Probiotic', '', ''),
  ('Supplement 174', 'Amino Acid', '', ''),
  ('Supplement 175', 'Mineral', '', ''),
  ('Supplement 176', 'Electrolyte', '', ''),
  ('Supplement 177', 'Amino Acid', '', ''),
  ('Supplement 178', 'Botanical', '', ''),
  ('Supplement 179', 'Electrolyte', '', ''),
  ('Supplement 180', 'Electrolyte', '', ''),
  ('Supplement 181', 'Probiotic', '', ''),
  ('Supplement 182', 'Amino Acid', '', ''),
  ('Supplement 183', 'Adaptogen', '', ''),
  ('Supplement 184', 'Botanical', '', ''),
  ('Supplement 185', 'Probiotic', '', ''),
  ('Supplement 186', 'Botanical', '', ''),
  ('Supplement 187', 'Mineral', '', ''),
  ('Supplement 188', 'Adaptogen', '', ''),
  ('Supplement 189', 'Vitamin', '', ''),
  ('Supplement 190', 'Botanical', '', ''),
  ('Supplement 191', 'Probiotic', '', ''),
  ('Supplement 192', 'Botanical', '', ''),
  ('Supplement 193', 'Adaptogen', '', ''),
  ('Supplement 194', 'Electrolyte', '', ''),
  ('Supplement 195', 'Electrolyte', '', ''),
  ('Supplement 196', 'Vitamin', '', ''),
  ('Supplement 197', 'Botanical', '', ''),
  ('Supplement 198', 'Probiotic', '', ''),
  ('Supplement 199', 'Vitamin', '', ''),
  ('Supplement 200', 'Adaptogen', '', ''),
  ('Supplement 201', 'Electrolyte', '', ''),
  ('Supplement 202', 'Mineral', '', ''),
  ('Supplement 203', 'Probiotic', '', ''),
  ('Supplement 204', 'Amino Acid', '', ''),
  ('Supplement 205', 'Mineral', '', ''),
  ('Supplement 206', 'Mineral', '', ''),
  ('Supplement 207', 'Amino Acid', '', ''),
  ('Supplement 208', 'Botanical', '', ''),
  ('Supplement 209', 'Amino Acid', '', ''),
  ('Supplement 210', 'Botanical', '', ''),
  ('Supplement 211', 'Botanical', '', ''),
  ('Supplement 212', 'Amino Acid', '', ''),
  ('Supplement 213', 'Probiotic', '', ''),
  ('Supplement 214', 'Amino Acid', '', ''),
  ('Supplement 215', 'Adaptogen', '', ''),
  ('Supplement 216', 'Vitamin', '', ''),
  ('Supplement 217', 'Electrolyte', '', ''),
  ('Supplement 218', 'Mineral', '', ''),
  ('Supplement 219', 'Electrolyte', '', ''),
  ('Supplement 220', 'Botanical', '', ''),
  ('Supplement 221', 'Probiotic', '', ''),
  ('Supplement 222', 'Adaptogen', '', ''),
  ('Supplement 223', 'Amino Acid', '', ''),
  ('Supplement 224', 'Adaptogen', '', ''),
  ('Supplement 225', 'Probiotic', '', ''),
  ('Supplement 226', 'Botanical', '', ''),
  ('Supplement 227', 'Amino Acid', '', ''),
  ('Supplement 228', 'Amino Acid', '', ''),
  ('Supplement 229', 'Adaptogen', '', ''),
  ('Supplement 230', 'Mineral', '', ''),
  ('Supplement 231', 'Probiotic', '', ''),
  ('Supplement 232', 'Vitamin', '', ''),
  ('Supplement 233', 'Adaptogen', '', ''),
  ('Supplement 234', 'Botanical', '', ''),
  ('Supplement 235', 'Mineral', '', ''),
  ('Supplement 236', 'Electrolyte', '', ''),
  ('Supplement 237', 'Vitamin', '', ''),
  ('Supplement 238', 'Probiotic', '', ''),
  ('Supplement 239', 'Mineral', '', ''),
  ('Supplement 240', 'Vitamin', '', ''),
  ('Supplement 241', 'Adaptogen', '', ''),
  ('Supplement 242', 'Probiotic', '', ''),
  ('Supplement 243', 'Botanical', '', ''),
  ('Supplement 244', 'Electrolyte', '', ''),
  ('Supplement 245', 'Vitamin', '', ''),
  ('Supplement 246', 'Probiotic', '', ''),
  ('Supplement 247', 'Adaptogen', '', ''),
  ('Supplement 248', 'Amino Acid', '', ''),
  ('Supplement 249', 'Electrolyte', '', ''),
  ('Supplement 250', 'Vitamin', '', '')
ON CONFLICT (name) DO NOTHING;INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 251', 'Botanical', '', ''),
  ('Supplement 252', 'Vitamin', '', ''),
  ('Supplement 253', 'Mineral', '', ''),
  ('Supplement 254', 'Mineral', '', ''),
  ('Supplement 255', 'Adaptogen', '', ''),
  ('Supplement 256', 'Probiotic', '', ''),
  ('Supplement 257', 'Botanical', '', ''),
  ('Supplement 258', 'Electrolyte', '', ''),
  ('Supplement 259', 'Probiotic', '', ''),
  ('Supplement 260', 'Vitamin', '', ''),
  ('Supplement 261', 'Vitamin', '', ''),
  ('Supplement 262', 'Adaptogen', '', ''),
  ('Supplement 263', 'Mineral', '', ''),
  ('Supplement 264', 'Amino Acid', '', ''),
  ('Supplement 265', 'Probiotic', '', ''),
  ('Supplement 266', 'Botanical', '', ''),
  ('Supplement 267', 'Probiotic', '', ''),
  ('Supplement 268', 'Botanical', '', ''),
  ('Supplement 269', 'Vitamin', '', ''),
  ('Supplement 270', 'Electrolyte', '', ''),
  ('Supplement 271', 'Electrolyte', '', ''),
  ('Supplement 272', 'Electrolyte', '', ''),
  ('Supplement 273', 'Adaptogen', '', ''),
  ('Supplement 274', 'Amino Acid', '', ''),
  ('Supplement 275', 'Amino Acid', '', ''),
  ('Supplement 276', 'Vitamin', '', ''),
  ('Supplement 277', 'Probiotic', '', ''),
  ('Supplement 278', 'Botanical', '', ''),
  ('Supplement 279', 'Adaptogen', '', ''),
  ('Supplement 280', 'Probiotic', '', ''),
  ('Supplement 281', 'Botanical', '', ''),
  ('Supplement 282', 'Probiotic', '', ''),
  ('Supplement 283', 'Botanical', '', ''),
  ('Supplement 284', 'Electrolyte', '', ''),
  ('Supplement 285', 'Electrolyte', '', ''),
  ('Supplement 286', 'Vitamin', '', ''),
  ('Supplement 287', 'Amino Acid', '', ''),
  ('Supplement 288', 'Electrolyte', '', ''),
  ('Supplement 289', 'Adaptogen', '', ''),
  ('Supplement 290', 'Mineral', '', ''),
  ('Supplement 291', 'Probiotic', '', ''),
  ('Supplement 292', 'Electrolyte', '', ''),
  ('Supplement 293', 'Adaptogen', '', ''),
  ('Supplement 294', 'Electrolyte', '', ''),
  ('Supplement 295', 'Adaptogen', '', ''),
  ('Supplement 296', 'Adaptogen', '', ''),
  ('Supplement 297', 'Electrolyte', '', ''),
  ('Supplement 298', 'Mineral', '', ''),
  ('Supplement 299', 'Electrolyte', '', ''),
  ('Supplement 300', 'Adaptogen', '', ''),
  ('Supplement 301', 'Amino Acid', '', ''),
  ('Supplement 302', 'Adaptogen', '', ''),
  ('Supplement 303', 'Mineral', '', ''),
  ('Supplement 304', 'Adaptogen', '', ''),
  ('Supplement 305', 'Vitamin', '', ''),
  ('Supplement 306', 'Probiotic', '', ''),
  ('Supplement 307', 'Amino Acid', '', ''),
  ('Supplement 308', 'Botanical', '', ''),
  ('Supplement 309', 'Mineral', '', ''),
  ('Supplement 310', 'Botanical', '', ''),
  ('Supplement 311', 'Electrolyte', '', ''),
  ('Supplement 312', 'Amino Acid', '', ''),
  ('Supplement 313', 'Mineral', '', ''),
  ('Supplement 314', 'Adaptogen', '', ''),
  ('Supplement 315', 'Botanical', '', ''),
  ('Supplement 316', 'Electrolyte', '', ''),
  ('Supplement 317', 'Electrolyte', '', ''),
  ('Supplement 318', 'Adaptogen', '', ''),
  ('Supplement 319', 'Botanical', '', ''),
  ('Supplement 320', 'Adaptogen', '', ''),
  ('Supplement 321', 'Adaptogen', '', ''),
  ('Supplement 322', 'Mineral', '', ''),
  ('Supplement 323', 'Amino Acid', '', ''),
  ('Supplement 324', 'Electrolyte', '', ''),
  ('Supplement 325', 'Adaptogen', '', ''),
  ('Supplement 326', 'Botanical', '', ''),
  ('Supplement 327', 'Botanical', '', ''),
  ('Supplement 328', 'Adaptogen', '', ''),
  ('Supplement 329', 'Vitamin', '', ''),
  ('Supplement 330', 'Amino Acid', '', ''),
  ('Supplement 331', 'Vitamin', '', ''),
  ('Supplement 332', 'Electrolyte', '', ''),
  ('Supplement 333', 'Adaptogen', '', ''),
  ('Supplement 334', 'Amino Acid', '', ''),
  ('Supplement 335', 'Vitamin', '', ''),
  ('Supplement 336', 'Mineral', '', ''),
  ('Supplement 337', 'Amino Acid', '', ''),
  ('Supplement 338', 'Amino Acid', '', ''),
  ('Supplement 339', 'Vitamin', '', ''),
  ('Supplement 340', 'Electrolyte', '', ''),
  ('Supplement 341', 'Botanical', '', ''),
  ('Supplement 342', 'Probiotic', '', ''),
  ('Supplement 343', 'Botanical', '', ''),
  ('Supplement 344', 'Probiotic', '', ''),
  ('Supplement 345', 'Adaptogen', '', ''),
  ('Supplement 346', 'Probiotic', '', ''),
  ('Supplement 347', 'Probiotic', '', ''),
  ('Supplement 348', 'Adaptogen', '', ''),
  ('Supplement 349', 'Probiotic', '', ''),
  ('Supplement 350', 'Electrolyte', '', ''),
  ('Supplement 351', 'Vitamin', '', ''),
  ('Supplement 352', 'Vitamin', '', ''),
  ('Supplement 353', 'Vitamin', '', ''),
  ('Supplement 354', 'Amino Acid', '', ''),
  ('Supplement 355', 'Probiotic', '', ''),
  ('Supplement 356', 'Vitamin', '', ''),
  ('Supplement 357', 'Mineral', '', ''),
  ('Supplement 358', 'Amino Acid', '', ''),
  ('Supplement 359', 'Probiotic', '', ''),
  ('Supplement 360', 'Botanical', '', ''),
  ('Supplement 361', 'Amino Acid', '', ''),
  ('Supplement 362', 'Electrolyte', '', ''),
  ('Supplement 363', 'Adaptogen', '', ''),
  ('Supplement 364', 'Probiotic', '', ''),
  ('Supplement 365', 'Amino Acid', '', ''),
  ('Supplement 366', 'Probiotic', '', ''),
  ('Supplement 367', 'Vitamin', '', ''),
  ('Supplement 368', 'Mineral', '', ''),
  ('Supplement 369', 'Adaptogen', '', ''),
  ('Supplement 370', 'Botanical', '', ''),
  ('Supplement 371', 'Electrolyte', '', ''),
  ('Supplement 372', 'Botanical', '', ''),
  ('Supplement 373', 'Mineral', '', ''),
  ('Supplement 374', 'Botanical', '', ''),
  ('Supplement 375', 'Vitamin', '', ''),
  ('Supplement 376', 'Amino Acid', '', ''),
  ('Supplement 377', 'Vitamin', '', ''),
  ('Supplement 378', 'Mineral', '', ''),
  ('Supplement 379', 'Vitamin', '', ''),
  ('Supplement 380', 'Adaptogen', '', ''),
  ('Supplement 381', 'Amino Acid', '', ''),
  ('Supplement 382', 'Amino Acid', '', ''),
  ('Supplement 383', 'Amino Acid', '', ''),
  ('Supplement 384', 'Electrolyte', '', ''),
  ('Supplement 385', 'Mineral', '', ''),
  ('Supplement 386', 'Adaptogen', '', ''),
  ('Supplement 387', 'Mineral', '', ''),
  ('Supplement 388', 'Amino Acid', '', ''),
  ('Supplement 389', 'Botanical', '', ''),
  ('Supplement 390', 'Electrolyte', '', ''),
  ('Supplement 391', 'Vitamin', '', ''),
  ('Supplement 392', 'Vitamin', '', ''),
  ('Supplement 393', 'Botanical', '', ''),
  ('Supplement 394', 'Vitamin', '', ''),
  ('Supplement 395', 'Electrolyte', '', ''),
  ('Supplement 396', 'Amino Acid', '', ''),
  ('Supplement 397', 'Vitamin', '', ''),
  ('Supplement 398', 'Probiotic', '', ''),
  ('Supplement 399', 'Electrolyte', '', ''),
  ('Supplement 400', 'Adaptogen', '', ''),
  ('Supplement 401', 'Electrolyte', '', ''),
  ('Supplement 402', 'Mineral', '', ''),
  ('Supplement 403', 'Amino Acid', '', ''),
  ('Supplement 404', 'Adaptogen', '', ''),
  ('Supplement 405', 'Probiotic', '', ''),
  ('Supplement 406', 'Adaptogen', '', ''),
  ('Supplement 407', 'Adaptogen', '', ''),
  ('Supplement 408', 'Botanical', '', ''),
  ('Supplement 409', 'Adaptogen', '', ''),
  ('Supplement 410', 'Mineral', '', ''),
  ('Supplement 411', 'Adaptogen', '', ''),
  ('Supplement 412', 'Adaptogen', '', ''),
  ('Supplement 413', 'Mineral', '', ''),
  ('Supplement 414', 'Amino Acid', '', ''),
  ('Supplement 415', 'Amino Acid', '', ''),
  ('Supplement 416', 'Probiotic', '', ''),
  ('Supplement 417', 'Vitamin', '', ''),
  ('Supplement 418', 'Mineral', '', ''),
  ('Supplement 419', 'Electrolyte', '', ''),
  ('Supplement 420', 'Botanical', '', ''),
  ('Supplement 421', 'Mineral', '', ''),
  ('Supplement 422', 'Electrolyte', '', ''),
  ('Supplement 423', 'Electrolyte', '', ''),
  ('Supplement 424', 'Botanical', '', ''),
  ('Supplement 425', 'Vitamin', '', ''),
  ('Supplement 426', 'Botanical', '', ''),
  ('Supplement 427', 'Amino Acid', '', ''),
  ('Supplement 428', 'Adaptogen', '', ''),
  ('Supplement 429', 'Electrolyte', '', ''),
  ('Supplement 430', 'Electrolyte', '', ''),
  ('Supplement 431', 'Electrolyte', '', ''),
  ('Supplement 432', 'Probiotic', '', ''),
  ('Supplement 433', 'Vitamin', '', ''),
  ('Supplement 434', 'Mineral', '', ''),
  ('Supplement 435', 'Vitamin', '', ''),
  ('Supplement 436', 'Electrolyte', '', ''),
  ('Supplement 437', 'Adaptogen', '', ''),
  ('Supplement 438', 'Electrolyte', '', ''),
  ('Supplement 439', 'Adaptogen', '', ''),
  ('Supplement 440', 'Botanical', '', ''),
  ('Supplement 441', 'Electrolyte', '', ''),
  ('Supplement 442', 'Mineral', '', ''),
  ('Supplement 443', 'Vitamin', '', ''),
  ('Supplement 444', 'Amino Acid', '', ''),
  ('Supplement 445', 'Vitamin', '', ''),
  ('Supplement 446', 'Amino Acid', '', ''),
  ('Supplement 447', 'Mineral', '', ''),
  ('Supplement 448', 'Mineral', '', ''),
  ('Supplement 449', 'Mineral', '', ''),
  ('Supplement 450', 'Vitamin', '', ''),
  ('Supplement 451', 'Mineral', '', ''),
  ('Supplement 452', 'Probiotic', '', ''),
  ('Supplement 453', 'Amino Acid', '', ''),
  ('Supplement 454', 'Botanical', '', ''),
  ('Supplement 455', 'Mineral', '', ''),
  ('Supplement 456', 'Adaptogen', '', ''),
  ('Supplement 457', 'Amino Acid', '', ''),
  ('Supplement 458', 'Adaptogen', '', ''),
  ('Supplement 459', 'Electrolyte', '', ''),
  ('Supplement 460', 'Mineral', '', ''),
  ('Supplement 461', 'Adaptogen', '', ''),
  ('Supplement 462', 'Botanical', '', ''),
  ('Supplement 463', 'Vitamin', '', ''),
  ('Supplement 464', 'Vitamin', '', ''),
  ('Supplement 465', 'Probiotic', '', ''),
  ('Supplement 466', 'Probiotic', '', ''),
  ('Supplement 467', 'Amino Acid', '', ''),
  ('Supplement 468', 'Probiotic', '', ''),
  ('Supplement 469', 'Probiotic', '', ''),
  ('Supplement 470', 'Vitamin', '', ''),
  ('Supplement 471', 'Probiotic', '', ''),
  ('Supplement 472', 'Mineral', '', ''),
  ('Supplement 473', 'Botanical', '', ''),
  ('Supplement 474', 'Adaptogen', '', ''),
  ('Supplement 475', 'Mineral', '', ''),
  ('Supplement 476', 'Mineral', '', ''),
  ('Supplement 477', 'Mineral', '', ''),
  ('Supplement 478', 'Botanical', '', ''),
  ('Supplement 479', 'Mineral', '', ''),
  ('Supplement 480', 'Adaptogen', '', ''),
  ('Supplement 481', 'Electrolyte', '', ''),
  ('Supplement 482', 'Amino Acid', '', ''),
  ('Supplement 483', 'Botanical', '', ''),
  ('Supplement 484', 'Amino Acid', '', ''),
  ('Supplement 485', 'Adaptogen', '', ''),
  ('Supplement 486', 'Vitamin', '', ''),
  ('Supplement 487', 'Probiotic', '', ''),
  ('Supplement 488', 'Botanical', '', ''),
  ('Supplement 489', 'Botanical', '', ''),
  ('Supplement 490', 'Electrolyte', '', ''),
  ('Supplement 491', 'Electrolyte', '', ''),
  ('Supplement 492', 'Botanical', '', ''),
  ('Supplement 493', 'Amino Acid', '', ''),
  ('Supplement 494', 'Vitamin', '', ''),
  ('Supplement 495', 'Mineral', '', ''),
  ('Supplement 496', 'Mineral', '', ''),
  ('Supplement 497', 'Vitamin', '', ''),
  ('Supplement 498', 'Vitamin', '', ''),
  ('Supplement 499', 'Mineral', '', ''),
  ('Supplement 500', 'Vitamin', '', '')
ON CONFLICT (name) DO NOTHING;INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 501', 'Mineral', '', ''),
  ('Supplement 502', 'Botanical', '', ''),
  ('Supplement 503', 'Amino Acid', '', ''),
  ('Supplement 504', 'Adaptogen', '', ''),
  ('Supplement 505', 'Amino Acid', '', ''),
  ('Supplement 506', 'Probiotic', '', ''),
  ('Supplement 507', 'Adaptogen', '', ''),
  ('Supplement 508', 'Amino Acid', '', ''),
  ('Supplement 509', 'Adaptogen', '', ''),
  ('Supplement 510', 'Amino Acid', '', ''),
  ('Supplement 511', 'Mineral', '', ''),
  ('Supplement 512', 'Mineral', '', ''),
  ('Supplement 513', 'Adaptogen', '', ''),
  ('Supplement 514', 'Mineral', '', ''),
  ('Supplement 515', 'Mineral', '', ''),
  ('Supplement 516', 'Probiotic', '', ''),
  ('Supplement 517', 'Electrolyte', '', ''),
  ('Supplement 518', 'Amino Acid', '', ''),
  ('Supplement 519', 'Amino Acid', '', ''),
  ('Supplement 520', 'Probiotic', '', ''),
  ('Supplement 521', 'Mineral', '', ''),
  ('Supplement 522', 'Probiotic', '', ''),
  ('Supplement 523', 'Amino Acid', '', ''),
  ('Supplement 524', 'Probiotic', '', ''),
  ('Supplement 525', 'Probiotic', '', ''),
  ('Supplement 526', 'Mineral', '', ''),
  ('Supplement 527', 'Botanical', '', ''),
  ('Supplement 528', 'Probiotic', '', ''),
  ('Supplement 529', 'Vitamin', '', ''),
  ('Supplement 530', 'Vitamin', '', ''),
  ('Supplement 531', 'Botanical', '', ''),
  ('Supplement 532', 'Amino Acid', '', ''),
  ('Supplement 533', 'Mineral', '', ''),
  ('Supplement 534', 'Vitamin', '', ''),
  ('Supplement 535', 'Vitamin', '', ''),
  ('Supplement 536', 'Electrolyte', '', ''),
  ('Supplement 537', 'Electrolyte', '', ''),
  ('Supplement 538', 'Amino Acid', '', ''),
  ('Supplement 539', 'Adaptogen', '', ''),
  ('Supplement 540', 'Vitamin', '', ''),
  ('Supplement 541', 'Mineral', '', ''),
  ('Supplement 542', 'Probiotic', '', ''),
  ('Supplement 543', 'Probiotic', '', ''),
  ('Supplement 544', 'Mineral', '', ''),
  ('Supplement 545', 'Mineral', '', ''),
  ('Supplement 546', 'Botanical', '', ''),
  ('Supplement 547', 'Adaptogen', '', ''),
  ('Supplement 548', 'Vitamin', '', ''),
  ('Supplement 549', 'Adaptogen', '', ''),
  ('Supplement 550', 'Vitamin', '', ''),
  ('Supplement 551', 'Vitamin', '', ''),
  ('Supplement 552', 'Probiotic', '', ''),
  ('Supplement 553', 'Electrolyte', '', ''),
  ('Supplement 554', 'Electrolyte', '', ''),
  ('Supplement 555', 'Electrolyte', '', ''),
  ('Supplement 556', 'Botanical', '', ''),
  ('Supplement 557', 'Electrolyte', '', ''),
  ('Supplement 558', 'Mineral', '', ''),
  ('Supplement 559', 'Amino Acid', '', ''),
  ('Supplement 560', 'Adaptogen', '', ''),
  ('Supplement 561', 'Vitamin', '', ''),
  ('Supplement 562', 'Adaptogen', '', ''),
  ('Supplement 563', 'Amino Acid', '', ''),
  ('Supplement 564', 'Vitamin', '', ''),
  ('Supplement 565', 'Probiotic', '', ''),
  ('Supplement 566', 'Vitamin', '', ''),
  ('Supplement 567', 'Mineral', '', ''),
  ('Supplement 568', 'Adaptogen', '', ''),
  ('Supplement 569', 'Probiotic', '', ''),
  ('Supplement 570', 'Amino Acid', '', ''),
  ('Supplement 571', 'Mineral', '', ''),
  ('Supplement 572', 'Adaptogen', '', ''),
  ('Supplement 573', 'Mineral', '', ''),
  ('Supplement 574', 'Probiotic', '', ''),
  ('Supplement 575', 'Vitamin', '', ''),
  ('Supplement 576', 'Electrolyte', '', ''),
  ('Supplement 577', 'Probiotic', '', ''),
  ('Supplement 578', 'Mineral', '', ''),
  ('Supplement 579', 'Adaptogen', '', ''),
  ('Supplement 580', 'Vitamin', '', ''),
  ('Supplement 581', 'Botanical', '', ''),
  ('Supplement 582', 'Amino Acid', '', ''),
  ('Supplement 583', 'Botanical', '', ''),
  ('Supplement 584', 'Amino Acid', '', ''),
  ('Supplement 585', 'Mineral', '', ''),
  ('Supplement 586', 'Adaptogen', '', ''),
  ('Supplement 587', 'Vitamin', '', ''),
  ('Supplement 588', 'Botanical', '', ''),
  ('Supplement 589', 'Vitamin', '', ''),
  ('Supplement 590', 'Electrolyte', '', ''),
  ('Supplement 591', 'Adaptogen', '', ''),
  ('Supplement 592', 'Adaptogen', '', ''),
  ('Supplement 593', 'Mineral', '', ''),
  ('Supplement 594', 'Botanical', '', ''),
  ('Supplement 595', 'Probiotic', '', ''),
  ('Supplement 596', 'Probiotic', '', ''),
  ('Supplement 597', 'Electrolyte', '', ''),
  ('Supplement 598', 'Botanical', '', ''),
  ('Supplement 599', 'Electrolyte', '', ''),
  ('Supplement 600', 'Vitamin', '', ''),
  ('Supplement 601', 'Botanical', '', ''),
  ('Supplement 602', 'Probiotic', '', ''),
  ('Supplement 603', 'Adaptogen', '', ''),
  ('Supplement 604', 'Electrolyte', '', ''),
  ('Supplement 605', 'Vitamin', '', ''),
  ('Supplement 606', 'Electrolyte', '', ''),
  ('Supplement 607', 'Electrolyte', '', ''),
  ('Supplement 608', 'Botanical', '', ''),
  ('Supplement 609', 'Adaptogen', '', ''),
  ('Supplement 610', 'Probiotic', '', ''),
  ('Supplement 611', 'Botanical', '', ''),
  ('Supplement 612', 'Adaptogen', '', ''),
  ('Supplement 613', 'Adaptogen', '', ''),
  ('Supplement 614', 'Electrolyte', '', ''),
  ('Supplement 615', 'Amino Acid', '', ''),
  ('Supplement 616', 'Electrolyte', '', ''),
  ('Supplement 617', 'Electrolyte', '', ''),
  ('Supplement 618', 'Probiotic', '', ''),
  ('Supplement 619', 'Adaptogen', '', ''),
  ('Supplement 620', 'Adaptogen', '', ''),
  ('Supplement 621', 'Electrolyte', '', ''),
  ('Supplement 622', 'Amino Acid', '', ''),
  ('Supplement 623', 'Adaptogen', '', ''),
  ('Supplement 624', 'Amino Acid', '', ''),
  ('Supplement 625', 'Vitamin', '', ''),
  ('Supplement 626', 'Amino Acid', '', ''),
  ('Supplement 627', 'Vitamin', '', ''),
  ('Supplement 628', 'Vitamin', '', ''),
  ('Supplement 629', 'Amino Acid', '', ''),
  ('Supplement 630', 'Amino Acid', '', ''),
  ('Supplement 631', 'Electrolyte', '', ''),
  ('Supplement 632', 'Amino Acid', '', ''),
  ('Supplement 633', 'Electrolyte', '', ''),
  ('Supplement 634', 'Adaptogen', '', ''),
  ('Supplement 635', 'Adaptogen', '', ''),
  ('Supplement 636', 'Amino Acid', '', ''),
  ('Supplement 637', 'Probiotic', '', ''),
  ('Supplement 638', 'Electrolyte', '', ''),
  ('Supplement 639', 'Amino Acid', '', ''),
  ('Supplement 640', 'Probiotic', '', ''),
  ('Supplement 641', 'Adaptogen', '', ''),
  ('Supplement 642', 'Mineral', '', ''),
  ('Supplement 643', 'Adaptogen', '', ''),
  ('Supplement 644', 'Electrolyte', '', ''),
  ('Supplement 645', 'Adaptogen', '', ''),
  ('Supplement 646', 'Vitamin', '', ''),
  ('Supplement 647', 'Probiotic', '', ''),
  ('Supplement 648', 'Probiotic', '', ''),
  ('Supplement 649', 'Botanical', '', ''),
  ('Supplement 650', 'Vitamin', '', ''),
  ('Supplement 651', 'Probiotic', '', ''),
  ('Supplement 652', 'Amino Acid', '', ''),
  ('Supplement 653', 'Mineral', '', ''),
  ('Supplement 654', 'Vitamin', '', ''),
  ('Supplement 655', 'Electrolyte', '', ''),
  ('Supplement 656', 'Adaptogen', '', ''),
  ('Supplement 657', 'Vitamin', '', ''),
  ('Supplement 658', 'Adaptogen', '', ''),
  ('Supplement 659', 'Botanical', '', ''),
  ('Supplement 660', 'Mineral', '', ''),
  ('Supplement 661', 'Mineral', '', ''),
  ('Supplement 662', 'Botanical', '', ''),
  ('Supplement 663', 'Mineral', '', ''),
  ('Supplement 664', 'Mineral', '', ''),
  ('Supplement 665', 'Mineral', '', ''),
  ('Supplement 666', 'Vitamin', '', ''),
  ('Supplement 667', 'Probiotic', '', ''),
  ('Supplement 668', 'Amino Acid', '', ''),
  ('Supplement 669', 'Vitamin', '', ''),
  ('Supplement 670', 'Electrolyte', '', ''),
  ('Supplement 671', 'Adaptogen', '', ''),
  ('Supplement 672', 'Vitamin', '', ''),
  ('Supplement 673', 'Adaptogen', '', ''),
  ('Supplement 674', 'Adaptogen', '', ''),
  ('Supplement 675', 'Mineral', '', ''),
  ('Supplement 676', 'Adaptogen', '', ''),
  ('Supplement 677', 'Probiotic', '', ''),
  ('Supplement 678', 'Adaptogen', '', ''),
  ('Supplement 679', 'Probiotic', '', ''),
  ('Supplement 680', 'Mineral', '', ''),
  ('Supplement 681', 'Vitamin', '', ''),
  ('Supplement 682', 'Vitamin', '', ''),
  ('Supplement 683', 'Amino Acid', '', ''),
  ('Supplement 684', 'Vitamin', '', ''),
  ('Supplement 685', 'Adaptogen', '', ''),
  ('Supplement 686', 'Amino Acid', '', ''),
  ('Supplement 687', 'Adaptogen', '', ''),
  ('Supplement 688', 'Probiotic', '', ''),
  ('Supplement 689', 'Electrolyte', '', ''),
  ('Supplement 690', 'Probiotic', '', ''),
  ('Supplement 691', 'Electrolyte', '', ''),
  ('Supplement 692', 'Botanical', '', ''),
  ('Supplement 693', 'Probiotic', '', ''),
  ('Supplement 694', 'Botanical', '', ''),
  ('Supplement 695', 'Probiotic', '', ''),
  ('Supplement 696', 'Probiotic', '', ''),
  ('Supplement 697', 'Amino Acid', '', ''),
  ('Supplement 698', 'Probiotic', '', ''),
  ('Supplement 699', 'Botanical', '', ''),
  ('Supplement 700', 'Vitamin', '', ''),
  ('Supplement 701', 'Electrolyte', '', ''),
  ('Supplement 702', 'Amino Acid', '', ''),
  ('Supplement 703', 'Vitamin', '', ''),
  ('Supplement 704', 'Electrolyte', '', ''),
  ('Supplement 705', 'Amino Acid', '', ''),
  ('Supplement 706', 'Electrolyte', '', ''),
  ('Supplement 707', 'Vitamin', '', ''),
  ('Supplement 708', 'Amino Acid', '', ''),
  ('Supplement 709', 'Electrolyte', '', ''),
  ('Supplement 710', 'Electrolyte', '', ''),
  ('Supplement 711', 'Probiotic', '', ''),
  ('Supplement 712', 'Vitamin', '', ''),
  ('Supplement 713', 'Botanical', '', ''),
  ('Supplement 714', 'Adaptogen', '', ''),
  ('Supplement 715', 'Electrolyte', '', ''),
  ('Supplement 716', 'Probiotic', '', ''),
  ('Supplement 717', 'Mineral', '', ''),
  ('Supplement 718', 'Electrolyte', '', ''),
  ('Supplement 719', 'Amino Acid', '', ''),
  ('Supplement 720', 'Electrolyte', '', ''),
  ('Supplement 721', 'Vitamin', '', ''),
  ('Supplement 722', 'Mineral', '', ''),
  ('Supplement 723', 'Amino Acid', '', ''),
  ('Supplement 724', 'Adaptogen', '', ''),
  ('Supplement 725', 'Probiotic', '', ''),
  ('Supplement 726', 'Electrolyte', '', ''),
  ('Supplement 727', 'Probiotic', '', ''),
  ('Supplement 728', 'Electrolyte', '', ''),
  ('Supplement 729', 'Botanical', '', ''),
  ('Supplement 730', 'Botanical', '', ''),
  ('Supplement 731', 'Electrolyte', '', ''),
  ('Supplement 732', 'Botanical', '', ''),
  ('Supplement 733', 'Electrolyte', '', ''),
  ('Supplement 734', 'Electrolyte', '', ''),
  ('Supplement 735', 'Amino Acid', '', ''),
  ('Supplement 736', 'Electrolyte', '', ''),
  ('Supplement 737', 'Vitamin', '', ''),
  ('Supplement 738', 'Amino Acid', '', ''),
  ('Supplement 739', 'Electrolyte', '', ''),
  ('Supplement 740', 'Electrolyte', '', ''),
  ('Supplement 741', 'Amino Acid', '', ''),
  ('Supplement 742', 'Mineral', '', ''),
  ('Supplement 743', 'Vitamin', '', ''),
  ('Supplement 744', 'Probiotic', '', ''),
  ('Supplement 745', 'Adaptogen', '', ''),
  ('Supplement 746', 'Vitamin', '', ''),
  ('Supplement 747', 'Amino Acid', '', ''),
  ('Supplement 748', 'Botanical', '', ''),
  ('Supplement 749', 'Mineral', '', ''),
  ('Supplement 750', 'Adaptogen', '', '')
ON CONFLICT (name) DO NOTHING;INSERT INTO supplements (name, category, description, common_uses)
VALUES
  ('Supplement 751', 'Botanical', '', ''),
  ('Supplement 752', 'Amino Acid', '', ''),
  ('Supplement 753', 'Adaptogen', '', ''),
  ('Supplement 754', 'Adaptogen', '', ''),
  ('Supplement 755', 'Mineral', '', ''),
  ('Supplement 756', 'Amino Acid', '', ''),
  ('Supplement 757', 'Botanical', '', ''),
  ('Supplement 758', 'Electrolyte', '', ''),
  ('Supplement 759', 'Amino Acid', '', ''),
  ('Supplement 760', 'Botanical', '', ''),
  ('Supplement 761', 'Probiotic', '', ''),
  ('Supplement 762', 'Electrolyte', '', ''),
  ('Supplement 763', 'Electrolyte', '', ''),
  ('Supplement 764', 'Mineral', '', ''),
  ('Supplement 765', 'Probiotic', '', ''),
  ('Supplement 766', 'Electrolyte', '', ''),
  ('Supplement 767', 'Amino Acid', '', ''),
  ('Supplement 768', 'Botanical', '', ''),
  ('Supplement 769', 'Adaptogen', '', ''),
  ('Supplement 770', 'Probiotic', '', ''),
  ('Supplement 771', 'Probiotic', '', ''),
  ('Supplement 772', 'Mineral', '', ''),
  ('Supplement 773', 'Botanical', '', ''),
  ('Supplement 774', 'Amino Acid', '', ''),
  ('Supplement 775', 'Amino Acid', '', ''),
  ('Supplement 776', 'Probiotic', '', ''),
  ('Supplement 777', 'Vitamin', '', ''),
  ('Supplement 778', 'Probiotic', '', ''),
  ('Supplement 779', 'Vitamin', '', ''),
  ('Supplement 780', 'Adaptogen', '', ''),
  ('Supplement 781', 'Electrolyte', '', ''),
  ('Supplement 782', 'Botanical', '', ''),
  ('Supplement 783', 'Botanical', '', ''),
  ('Supplement 784', 'Amino Acid', '', ''),
  ('Supplement 785', 'Mineral', '', ''),
  ('Supplement 786', 'Mineral', '', ''),
  ('Supplement 787', 'Adaptogen', '', ''),
  ('Supplement 788', 'Adaptogen', '', ''),
  ('Supplement 789', 'Mineral', '', ''),
  ('Supplement 790', 'Mineral', '', ''),
  ('Supplement 791', 'Probiotic', '', ''),
  ('Supplement 792', 'Botanical', '', ''),
  ('Supplement 793', 'Botanical', '', ''),
  ('Supplement 794', 'Botanical', '', ''),
  ('Supplement 795', 'Electrolyte', '', ''),
  ('Supplement 796', 'Electrolyte', '', ''),
  ('Supplement 797', 'Vitamin', '', ''),
  ('Supplement 798', 'Vitamin', '', ''),
  ('Supplement 799', 'Vitamin', '', ''),
  ('Supplement 800', 'Vitamin', '', ''),
  ('Supplement 801', 'Vitamin', '', ''),
  ('Supplement 802', 'Electrolyte', '', ''),
  ('Supplement 803', 'Electrolyte', '', ''),
  ('Supplement 804', 'Amino Acid', '', ''),
  ('Supplement 805', 'Probiotic', '', ''),
  ('Supplement 806', 'Mineral', '', ''),
  ('Supplement 807', 'Adaptogen', '', ''),
  ('Supplement 808', 'Electrolyte', '', ''),
  ('Supplement 809', 'Amino Acid', '', ''),
  ('Supplement 810', 'Adaptogen', '', ''),
  ('Supplement 811', 'Amino Acid', '', ''),
  ('Supplement 812', 'Botanical', '', ''),
  ('Supplement 813', 'Vitamin', '', ''),
  ('Supplement 814', 'Vitamin', '', ''),
  ('Supplement 815', 'Botanical', '', ''),
  ('Supplement 816', 'Amino Acid', '', ''),
  ('Supplement 817', 'Vitamin', '', ''),
  ('Supplement 818', 'Botanical', '', ''),
  ('Supplement 819', 'Adaptogen', '', ''),
  ('Supplement 820', 'Mineral', '', ''),
  ('Supplement 821', 'Probiotic', '', ''),
  ('Supplement 822', 'Amino Acid', '', ''),
  ('Supplement 823', 'Probiotic', '', ''),
  ('Supplement 824', 'Adaptogen', '', ''),
  ('Supplement 825', 'Vitamin', '', ''),
  ('Supplement 826', 'Probiotic', '', ''),
  ('Supplement 827', 'Mineral', '', ''),
  ('Supplement 828', 'Amino Acid', '', ''),
  ('Supplement 829', 'Probiotic', '', ''),
  ('Supplement 830', 'Botanical', '', ''),
  ('Supplement 831', 'Amino Acid', '', ''),
  ('Supplement 832', 'Adaptogen', '', ''),
  ('Supplement 833', 'Electrolyte', '', ''),
  ('Supplement 834', 'Mineral', '', ''),
  ('Supplement 835', 'Amino Acid', '', ''),
  ('Supplement 836', 'Mineral', '', ''),
  ('Supplement 837', 'Probiotic', '', ''),
  ('Supplement 838', 'Adaptogen', '', ''),
  ('Supplement 839', 'Vitamin', '', ''),
  ('Supplement 840', 'Vitamin', '', ''),
  ('Supplement 841', 'Amino Acid', '', ''),
  ('Supplement 842', 'Electrolyte', '', ''),
  ('Supplement 843', 'Probiotic', '', ''),
  ('Supplement 844', 'Probiotic', '', ''),
  ('Supplement 845', 'Amino Acid', '', ''),
  ('Supplement 846', 'Vitamin', '', ''),
  ('Supplement 847', 'Vitamin', '', ''),
  ('Supplement 848', 'Amino Acid', '', ''),
  ('Supplement 849', 'Botanical', '', ''),
  ('Supplement 850', 'Amino Acid', '', ''),
  ('Supplement 851', 'Mineral', '', ''),
  ('Supplement 852', 'Vitamin', '', ''),
  ('Supplement 853', 'Vitamin', '', ''),
  ('Supplement 854', 'Vitamin', '', ''),
  ('Supplement 855', 'Adaptogen', '', ''),
  ('Supplement 856', 'Mineral', '', ''),
  ('Supplement 857', 'Vitamin', '', ''),
  ('Supplement 858', 'Probiotic', '', ''),
  ('Supplement 859', 'Mineral', '', ''),
  ('Supplement 860', 'Mineral', '', ''),
  ('Supplement 861', 'Adaptogen', '', ''),
  ('Supplement 862', 'Probiotic', '', ''),
  ('Supplement 863', 'Electrolyte', '', ''),
  ('Supplement 864', 'Probiotic', '', ''),
  ('Supplement 865', 'Amino Acid', '', ''),
  ('Supplement 866', 'Amino Acid', '', ''),
  ('Supplement 867', 'Adaptogen', '', ''),
  ('Supplement 868', 'Electrolyte', '', ''),
  ('Supplement 869', 'Adaptogen', '', ''),
  ('Supplement 870', 'Amino Acid', '', ''),
  ('Supplement 871', 'Electrolyte', '', ''),
  ('Supplement 872', 'Probiotic', '', ''),
  ('Supplement 873', 'Botanical', '', ''),
  ('Supplement 874', 'Vitamin', '', ''),
  ('Supplement 875', 'Probiotic', '', ''),
  ('Supplement 876', 'Electrolyte', '', ''),
  ('Supplement 877', 'Adaptogen', '', ''),
  ('Supplement 878', 'Electrolyte', '', ''),
  ('Supplement 879', 'Probiotic', '', ''),
  ('Supplement 880', 'Vitamin', '', ''),
  ('Supplement 881', 'Adaptogen', '', ''),
  ('Supplement 882', 'Botanical', '', ''),
  ('Supplement 883', 'Probiotic', '', ''),
  ('Supplement 884', 'Botanical', '', ''),
  ('Supplement 885', 'Electrolyte', '', ''),
  ('Supplement 886', 'Adaptogen', '', ''),
  ('Supplement 887', 'Vitamin', '', ''),
  ('Supplement 888', 'Amino Acid', '', ''),
  ('Supplement 889', 'Vitamin', '', ''),
  ('Supplement 890', 'Mineral', '', ''),
  ('Supplement 891', 'Amino Acid', '', ''),
  ('Supplement 892', 'Botanical', '', ''),
  ('Supplement 893', 'Probiotic', '', ''),
  ('Supplement 894', 'Vitamin', '', ''),
  ('Supplement 895', 'Vitamin', '', ''),
  ('Supplement 896', 'Amino Acid', '', ''),
  ('Supplement 897', 'Electrolyte', '', ''),
  ('Supplement 898', 'Probiotic', '', ''),
  ('Supplement 899', 'Botanical', '', ''),
  ('Supplement 900', 'Amino Acid', '', ''),
  ('Supplement 901', 'Amino Acid', '', ''),
  ('Supplement 902', 'Mineral', '', ''),
  ('Supplement 903', 'Botanical', '', ''),
  ('Supplement 904', 'Electrolyte', '', ''),
  ('Supplement 905', 'Adaptogen', '', ''),
  ('Supplement 906', 'Amino Acid', '', ''),
  ('Supplement 907', 'Electrolyte', '', ''),
  ('Supplement 908', 'Botanical', '', ''),
  ('Supplement 909', 'Electrolyte', '', ''),
  ('Supplement 910', 'Probiotic', '', ''),
  ('Supplement 911', 'Mineral', '', ''),
  ('Supplement 912', 'Amino Acid', '', ''),
  ('Supplement 913', 'Amino Acid', '', ''),
  ('Supplement 914', 'Mineral', '', ''),
  ('Supplement 915', 'Mineral', '', ''),
  ('Supplement 916', 'Probiotic', '', ''),
  ('Supplement 917', 'Botanical', '', ''),
  ('Supplement 918', 'Botanical', '', ''),
  ('Supplement 919', 'Electrolyte', '', ''),
  ('Supplement 920', 'Amino Acid', '', ''),
  ('Supplement 921', 'Adaptogen', '', ''),
  ('Supplement 922', 'Vitamin', '', ''),
  ('Supplement 923', 'Vitamin', '', ''),
  ('Supplement 924', 'Probiotic', '', ''),
  ('Supplement 925', 'Vitamin', '', ''),
  ('Supplement 926', 'Vitamin', '', ''),
  ('Supplement 927', 'Amino Acid', '', ''),
  ('Supplement 928', 'Electrolyte', '', ''),
  ('Supplement 929', 'Vitamin', '', ''),
  ('Supplement 930', 'Probiotic', '', ''),
  ('Supplement 931', 'Probiotic', '', ''),
  ('Supplement 932', 'Mineral', '', ''),
  ('Supplement 933', 'Vitamin', '', ''),
  ('Supplement 934', 'Probiotic', '', ''),
  ('Supplement 935', 'Amino Acid', '', ''),
  ('Supplement 936', 'Probiotic', '', ''),
  ('Supplement 937', 'Botanical', '', ''),
  ('Supplement 938', 'Mineral', '', ''),
  ('Supplement 939', 'Probiotic', '', ''),
  ('Supplement 940', 'Adaptogen', '', ''),
  ('Supplement 941', 'Mineral', '', ''),
  ('Supplement 942', 'Adaptogen', '', ''),
  ('Supplement 943', 'Botanical', '', ''),
  ('Supplement 944', 'Adaptogen', '', ''),
  ('Supplement 945', 'Mineral', '', ''),
  ('Supplement 946', 'Adaptogen', '', ''),
  ('Supplement 947', 'Electrolyte', '', ''),
  ('Supplement 948', 'Electrolyte', '', ''),
  ('Supplement 949', 'Botanical', '', ''),
  ('Supplement 950', 'Probiotic', '', ''),
  ('Supplement 951', 'Adaptogen', '', ''),
  ('Supplement 952', 'Amino Acid', '', ''),
  ('Supplement 953', 'Amino Acid', '', ''),
  ('Supplement 954', 'Probiotic', '', ''),
  ('Supplement 955', 'Botanical', '', ''),
  ('Supplement 956', 'Vitamin', '', ''),
  ('Supplement 957', 'Botanical', '', ''),
  ('Supplement 958', 'Probiotic', '', ''),
  ('Supplement 959', 'Vitamin', '', ''),
  ('Supplement 960', 'Botanical', '', ''),
  ('Supplement 961', 'Electrolyte', '', ''),
  ('Supplement 962', 'Probiotic', '', ''),
  ('Supplement 963', 'Mineral', '', ''),
  ('Supplement 964', 'Adaptogen', '', ''),
  ('Supplement 965', 'Mineral', '', ''),
  ('Supplement 966', 'Botanical', '', ''),
  ('Supplement 967', 'Amino Acid', '', ''),
  ('Supplement 968', 'Probiotic', '', ''),
  ('Supplement 969', 'Vitamin', '', ''),
  ('Supplement 970', 'Electrolyte', '', ''),
  ('Supplement 971', 'Amino Acid', '', ''),
  ('Supplement 972', 'Vitamin', '', ''),
  ('Supplement 973', 'Mineral', '', ''),
  ('Supplement 974', 'Mineral', '', ''),
  ('Supplement 975', 'Adaptogen', '', ''),
  ('Supplement 976', 'Probiotic', '', ''),
  ('Supplement 977', 'Amino Acid', '', ''),
  ('Supplement 978', 'Amino Acid', '', ''),
  ('Supplement 979', 'Adaptogen', '', ''),
  ('Supplement 980', 'Mineral', '', ''),
  ('Supplement 981', 'Mineral', '', ''),
  ('Supplement 982', 'Electrolyte', '', ''),
  ('Supplement 983', 'Botanical', '', ''),
  ('Supplement 984', 'Amino Acid', '', ''),
  ('Supplement 985', 'Mineral', '', ''),
  ('Supplement 986', 'Mineral', '', ''),
  ('Supplement 987', 'Electrolyte', '', ''),
  ('Supplement 988', 'Amino Acid', '', ''),
  ('Supplement 989', 'Adaptogen', '', ''),
  ('Supplement 990', 'Vitamin', '', ''),
  ('Supplement 991', 'Adaptogen', '', ''),
  ('Supplement 992', 'Adaptogen', '', ''),
  ('Supplement 993', 'Adaptogen', '', ''),
  ('Supplement 994', 'Amino Acid', '', ''),
  ('Supplement 995', 'Vitamin', '', ''),
  ('Supplement 996', 'Amino Acid', '', ''),
  ('Supplement 997', 'Mineral', '', ''),
  ('Supplement 998', 'Electrolyte', '', ''),
  ('Supplement 999', 'Electrolyte', '', ''),
  ('Supplement 1000', 'Adaptogen', '', '')
ON CONFLICT (name) DO NOTHING;INSERT INTO medications (name, category, description)
VALUES
  ('Medication 1', 'Antihypertensive', ''),
  ('Medication 2', 'Antihypertensive', ''),
  ('Medication 3', 'Antidepressant', ''),
  ('Medication 4', 'Analgesic', ''),
  ('Medication 5', 'Antihypertensive', ''),
  ('Medication 6', 'Antidepressant', ''),
  ('Medication 7', 'Antihypertensive', ''),
  ('Medication 8', 'Analgesic', ''),
  ('Medication 9', 'Anticoagulant', ''),
  ('Medication 10', 'Antibiotic', ''),
  ('Medication 11', 'Antibiotic', ''),
  ('Medication 12', 'Antibiotic', ''),
  ('Medication 13', 'Antibiotic', ''),
  ('Medication 14', 'Antidepressant', ''),
  ('Medication 15', 'Analgesic', ''),
  ('Medication 16', 'Antidepressant', ''),
  ('Medication 17', 'Anticoagulant', ''),
  ('Medication 18', 'Analgesic', ''),
  ('Medication 19', 'Anticoagulant', ''),
  ('Medication 20', 'Analgesic', ''),
  ('Medication 21', 'Antibiotic', ''),
  ('Medication 22', 'Antihypertensive', ''),
  ('Medication 23', 'Antibiotic', ''),
  ('Medication 24', 'Antibiotic', ''),
  ('Medication 25', 'Antibiotic', ''),
  ('Medication 26', 'Antihypertensive', ''),
  ('Medication 27', 'Anticoagulant', ''),
  ('Medication 28', 'Antibiotic', ''),
  ('Medication 29', 'Antibiotic', ''),
  ('Medication 30', 'Antihypertensive', ''),
  ('Medication 31', 'Analgesic', ''),
  ('Medication 32', 'Antidepressant', ''),
  ('Medication 33', 'Analgesic', ''),
  ('Medication 34', 'Antibiotic', ''),
  ('Medication 35', 'Antibiotic', ''),
  ('Medication 36', 'Antidepressant', ''),
  ('Medication 37', 'Antidepressant', ''),
  ('Medication 38', 'Antihypertensive', ''),
  ('Medication 39', 'Anticoagulant', ''),
  ('Medication 40', 'Analgesic', ''),
  ('Medication 41', 'Antidepressant', ''),
  ('Medication 42', 'Analgesic', ''),
  ('Medication 43', 'Analgesic', ''),
  ('Medication 44', 'Antihypertensive', ''),
  ('Medication 45', 'Antidepressant', ''),
  ('Medication 46', 'Analgesic', ''),
  ('Medication 47', 'Antidepressant', ''),
  ('Medication 48', 'Antihypertensive', ''),
  ('Medication 49', 'Analgesic', ''),
  ('Medication 50', 'Antibiotic', ''),
  ('Medication 51', 'Antihypertensive', ''),
  ('Medication 52', 'Anticoagulant', ''),
  ('Medication 53', 'Antibiotic', ''),
  ('Medication 54', 'Antihypertensive', ''),
  ('Medication 55', 'Antihypertensive', ''),
  ('Medication 56', 'Analgesic', ''),
  ('Medication 57', 'Antihypertensive', ''),
  ('Medication 58', 'Antibiotic', ''),
  ('Medication 59', 'Antidepressant', ''),
  ('Medication 60', 'Analgesic', ''),
  ('Medication 61', 'Antihypertensive', ''),
  ('Medication 62', 'Antibiotic', ''),
  ('Medication 63', 'Antihypertensive', ''),
  ('Medication 64', 'Antidepressant', ''),
  ('Medication 65', 'Anticoagulant', ''),
  ('Medication 66', 'Antidepressant', ''),
  ('Medication 67', 'Antihypertensive', ''),
  ('Medication 68', 'Anticoagulant', ''),
  ('Medication 69', 'Antibiotic', ''),
  ('Medication 70', 'Antidepressant', ''),
  ('Medication 71', 'Antihypertensive', ''),
  ('Medication 72', 'Antibiotic', ''),
  ('Medication 73', 'Analgesic', ''),
  ('Medication 74', 'Antibiotic', ''),
  ('Medication 75', 'Anticoagulant', ''),
  ('Medication 76', 'Analgesic', ''),
  ('Medication 77', 'Analgesic', ''),
  ('Medication 78', 'Anticoagulant', ''),
  ('Medication 79', 'Antidepressant', ''),
  ('Medication 80', 'Anticoagulant', ''),
  ('Medication 81', 'Antihypertensive', ''),
  ('Medication 82', 'Antidepressant', ''),
  ('Medication 83', 'Antidepressant', ''),
  ('Medication 84', 'Antidepressant', ''),
  ('Medication 85', 'Anticoagulant', ''),
  ('Medication 86', 'Analgesic', ''),
  ('Medication 87', 'Antibiotic', ''),
  ('Medication 88', 'Anticoagulant', ''),
  ('Medication 89', 'Antidepressant', ''),
  ('Medication 90', 'Antihypertensive', ''),
  ('Medication 91', 'Antihypertensive', ''),
  ('Medication 92', 'Anticoagulant', ''),
  ('Medication 93', 'Analgesic', ''),
  ('Medication 94', 'Anticoagulant', ''),
  ('Medication 95', 'Antidepressant', ''),
  ('Medication 96', 'Anticoagulant', ''),
  ('Medication 97', 'Analgesic', ''),
  ('Medication 98', 'Anticoagulant', ''),
  ('Medication 99', 'Analgesic', ''),
  ('Medication 100', 'Antidepressant', ''),
  ('Medication 101', 'Antidepressant', ''),
  ('Medication 102', 'Analgesic', ''),
  ('Medication 103', 'Antibiotic', ''),
  ('Medication 104', 'Anticoagulant', ''),
  ('Medication 105', 'Analgesic', ''),
  ('Medication 106', 'Antihypertensive', ''),
  ('Medication 107', 'Antihypertensive', ''),
  ('Medication 108', 'Anticoagulant', ''),
  ('Medication 109', 'Analgesic', ''),
  ('Medication 110', 'Antidepressant', ''),
  ('Medication 111', 'Anticoagulant', ''),
  ('Medication 112', 'Antibiotic', ''),
  ('Medication 113', 'Antidepressant', ''),
  ('Medication 114', 'Antihypertensive', ''),
  ('Medication 115', 'Antihypertensive', ''),
  ('Medication 116', 'Antibiotic', ''),
  ('Medication 117', 'Antidepressant', ''),
  ('Medication 118', 'Analgesic', ''),
  ('Medication 119', 'Anticoagulant', ''),
  ('Medication 120', 'Antibiotic', ''),
  ('Medication 121', 'Antibiotic', ''),
  ('Medication 122', 'Antibiotic', ''),
  ('Medication 123', 'Anticoagulant', ''),
  ('Medication 124', 'Antihypertensive', ''),
  ('Medication 125', 'Analgesic', ''),
  ('Medication 126', 'Analgesic', ''),
  ('Medication 127', 'Antidepressant', ''),
  ('Medication 128', 'Antibiotic', ''),
  ('Medication 129', 'Antidepressant', ''),
  ('Medication 130', 'Analgesic', ''),
  ('Medication 131', 'Analgesic', ''),
  ('Medication 132', 'Antibiotic', ''),
  ('Medication 133', 'Anticoagulant', ''),
  ('Medication 134', 'Antihypertensive', ''),
  ('Medication 135', 'Antihypertensive', ''),
  ('Medication 136', 'Antidepressant', ''),
  ('Medication 137', 'Antihypertensive', ''),
  ('Medication 138', 'Antibiotic', ''),
  ('Medication 139', 'Anticoagulant', ''),
  ('Medication 140', 'Anticoagulant', ''),
  ('Medication 141', 'Antidepressant', ''),
  ('Medication 142', 'Analgesic', ''),
  ('Medication 143', 'Anticoagulant', ''),
  ('Medication 144', 'Anticoagulant', ''),
  ('Medication 145', 'Antidepressant', ''),
  ('Medication 146', 'Anticoagulant', ''),
  ('Medication 147', 'Antidepressant', ''),
  ('Medication 148', 'Anticoagulant', ''),
  ('Medication 149', 'Antidepressant', ''),
  ('Medication 150', 'Antidepressant', '')
ON CONFLICT (name) DO NOTHING;