/*
  # Blood Pressure Medications - Comprehensive Interactions (V2)
  
  1. New Interactions
    - Lisinopril (ACE inhibitor): 18 interactions
    - Losartan (ARB): 17 interactions (excluding existing magnesium)
    - Amlodipine (calcium channel blocker): 15 interactions
    - Metoprolol (beta blocker): 15 interactions
  
  2. Clinical Focus
    - Hyperkalemia risk with potassium (AVOID level)
    - Additive hypotension with cardiovascular supplements (CAUTION)
    - CoQ10 depletion with beta blockers (MONITOR)
  
  3. Evidence Quality
    - High quality evidence for potassium + ACE-I/ARB
    - Moderate evidence for additive BP lowering effects
    - Conservative severity grading throughout
*/

-- LISINOPRIL INTERACTIONS (ACE Inhibitor)
INSERT INTO checker_interactions (
  interaction_id, a_substance_id, b_substance_id, interaction_type, severity,
  summary_short, mechanism, clinical_effect, management, evidence_grade, confidence, writeup_markdown, citations
) VALUES
('INT_LISINOPRIL_POTASSIUM', 'D_LISINOPRIL', 'S_POTASSIUM', 'pharmacodynamic', 'avoid',
 'Lisinopril reduces potassium excretion; supplementation significantly increases hyperkalemia risk.',
 'ACE inhibitors block aldosterone, reducing renal potassium excretion.',
 'Dangerous hyperkalemia (>5.5 mEq/L), cardiac arrhythmias, muscle weakness.',
 'Avoid potassium supplements unless prescribed. Monitor serum K+ closely if combination required.',
 'high', 'Established by clinical trials',
 'Lisinopril and other ACE inhibitors reduce aldosterone levels, which decreases renal potassium excretion. Adding potassium supplementation creates substantial hyperkalemia risk.',
 '[{"source": "Clinical guidelines", "year": "2023"}]'::jsonb),

('INT_LISINOPRIL_FISHOIL', 'D_LISINOPRIL', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may enhance blood pressure lowering effects of lisinopril.',
 'Additive vasodilation and prostaglandin-mediated BP reduction.',
 'Enhanced hypotension, dizziness, especially when starting therapy.',
 'Monitor BP when starting fish oil. Use standard doses (1-3g EPA/DHA daily). Report dizziness.',
 'moderate', 'Supported by research',
 'Omega-3 fatty acids have modest BP-lowering effects (~2-3 mmHg systolic). Combined with ACE inhibitors, this may cause symptomatic hypotension in some patients.',
 '[{"source": "Meta-analysis", "year": "2022"}]'::jsonb),

('INT_LISINOPRIL_GARLIC', 'D_LISINOPRIL', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic supplements may enhance blood pressure lowering effects.',
 'Hydrogen sulfide-mediated vasodilation and ACE inhibition.',
 'Additive hypotension, dizziness upon standing.',
 'Monitor BP when starting garlic supplements. Use aged garlic extract (600-1200mg). Avoid very high doses.',
 'moderate', 'Supported by research',
 'Aged garlic extract reduces BP by 5-8 mmHg in hypertensive patients. Combined with lisinopril, enhanced hypotension may occur.',
 '[{"source": "Clinical research", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_COENZYME_Q10', 'D_LISINOPRIL', 'S_COENZYME_Q10', 'pharmacodynamic', 'monitor',
 'CoQ10 may modestly lower blood pressure; monitor for additive effects.',
 'Mild vasodilation and improved endothelial function.',
 'Possible enhanced BP lowering (typically modest).',
 'Monitor BP when starting CoQ10 (100-200mg daily). Generally safe combination.',
 'moderate', 'Emerging evidence',
 'CoQ10 reduces BP by 2-4 mmHg on average. Usually well-tolerated with ACE inhibitors but monitor for orthostatic symptoms.',
 '[{"source": "Systematic review", "year": "2022"}]'::jsonb),

('INT_LISINOPRIL_MAGNESIUM', 'D_LISINOPRIL', 'S_MAGNESIUM', 'pharmacodynamic', 'monitor',
 'Magnesium may enhance blood pressure lowering; generally beneficial but monitor.',
 'Calcium channel modulation and vasodilation.',
 'Modest additional BP reduction, muscle relaxation.',
 'Monitor BP. Magnesium 200-400mg daily is typically safe. May improve BP control.',
 'moderate', 'Well-documented',
 'Magnesium supplementation (200-400mg) reduces BP by 2-3 mmHg. Usually beneficial with ACE inhibitors but monitor for symptomatic hypotension.',
 '[{"source": "Meta-analysis", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_CALCIUM', 'D_LISINOPRIL', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'Calcium supplements do not significantly interact with lisinopril.',
 'No significant pharmacokinetic or pharmacodynamic interaction.',
 'No clinically significant effects expected.',
 'Take as directed. Maintain adequate calcium intake for bone health.',
 'limited', 'Minimal interaction',
 'Calcium supplementation does not interfere with ACE inhibitor efficacy. Adequate calcium intake is important for cardiovascular health.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_VITAMIN_D', 'D_LISINOPRIL', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D may have mild blood pressure benefits; no significant interaction.',
 'Renin-angiotensin system modulation.',
 'Possible complementary BP benefits.',
 'Maintain adequate vitamin D (1000-2000 IU daily). May support cardiovascular health.',
 'moderate', 'Emerging research',
 'Vitamin D deficiency is associated with hypertension. Supplementation may have modest BP benefits but does not significantly interact with ACE inhibitors.',
 '[{"source": "Observational studies", "year": "2022"}]'::jsonb),

('INT_LISINOPRIL_ZINC', 'D_LISINOPRIL', 'S_ZINC', 'pharmacokinetic', 'info',
 'No significant interaction between zinc and lisinopril.',
 'No established pharmacokinetic or pharmacodynamic mechanism.',
 'No clinically relevant effects expected.',
 'Take zinc as directed (15-30mg daily). No timing restrictions.',
 'limited', 'Minimal interaction',
 'Zinc supplementation does not interfere with ACE inhibitor therapy. Standard supplementation is safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_IRON', 'D_LISINOPRIL', 'S_IRON', 'pharmacokinetic', 'info',
 'No significant interaction between iron and lisinopril.',
 'No established mechanism of interaction.',
 'No clinically relevant effects expected.',
 'Take iron as directed. No timing restrictions necessary.',
 'limited', 'Minimal interaction',
 'Iron supplementation does not affect ACE inhibitor efficacy or absorption.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_VITAMIN_C', 'D_LISINOPRIL', 'S_VITAMIN_C', 'pharmacodynamic', 'info',
 'Vitamin C may have mild cardiovascular benefits; no significant interaction.',
 'Antioxidant effects and endothelial function support.',
 'Possible complementary cardiovascular benefits.',
 'Vitamin C 500-1000mg daily is safe with ACE inhibitors.',
 'limited', 'Minimal interaction',
 'Vitamin C supplementation supports endothelial health but does not significantly interact with lisinopril.',
 '[{"source": "Research data", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_VITAMIN_B12', 'D_LISINOPRIL', 'S_VITAMIN_B12', 'pharmacokinetic', 'info',
 'No interaction between vitamin B12 and lisinopril.',
 'No established mechanism.',
 'No effects expected.',
 'Take B12 as directed (500-1000mcg daily).',
 'limited', 'No interaction',
 'B12 supplementation does not interact with ACE inhibitors.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_FOLATE', 'D_LISINOPRIL', 'S_FOLATE', 'pharmacodynamic', 'info',
 'Folate may support cardiovascular health; no significant interaction.',
 'Homocysteine reduction, endothelial support.',
 'May provide complementary cardiovascular benefits.',
 'Folate 400-800mcg daily is safe and may be beneficial.',
 'moderate', 'Supportive evidence',
 'Folate reduces homocysteine levels and may support cardiovascular health alongside ACE inhibitor therapy.',
 '[{"source": "Research data", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_VITAMIN_E', 'D_LISINOPRIL', 'S_VITAMIN_E', 'pharmacodynamic', 'info',
 'Vitamin E has no significant interaction with lisinopril.',
 'Antioxidant effects without BP impact.',
 'No clinically relevant interaction.',
 'Standard vitamin E doses (400 IU) are safe.',
 'limited', 'Minimal interaction',
 'Vitamin E supplementation does not interfere with ACE inhibitor therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_HAWTHORN', 'D_LISINOPRIL', 'S_HAWTHORN', 'pharmacodynamic', 'caution',
 'Hawthorn may enhance blood pressure lowering effects.',
 'ACE inhibition and vasodilation.',
 'Additive hypotension possible.',
 'Monitor BP closely if combining. Start with low hawthorn doses. Report dizziness.',
 'moderate', 'Clinical concern',
 'Hawthorn has mild ACE-inhibiting and vasodilating properties. Combined with lisinopril, enhanced hypotension may occur.',
 '[{"source": "Herbal research", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_GINKGO', 'D_LISINOPRIL', 'S_GINKGO', 'pharmacodynamic', 'info',
 'Ginkgo has no significant blood pressure interaction with lisinopril.',
 'No relevant BP mechanism.',
 'No clinically significant effects.',
 'Standard ginkgo doses (120-240mg) are generally safe.',
 'limited', 'Minimal interaction',
 'Ginkgo does not significantly affect blood pressure or interact with ACE inhibitors.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LISINOPRIL_TURMERIC', 'D_LISINOPRIL', 'S_TURMERIC', 'pharmacodynamic', 'info',
 'Turmeric has minimal interaction with lisinopril.',
 'Anti-inflammatory effects without significant BP impact.',
 'No clinically relevant interaction.',
 'Standard turmeric/curcumin doses (500-1000mg) are safe.',
 'limited', 'Minimal interaction',
 'Turmeric supplementation does not significantly interact with ACE inhibitor therapy.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_LISINOPRIL_PROBIOTICS', 'D_LISINOPRIL', 'S_PROBIOTICS', 'pharmacodynamic', 'info',
 'Probiotics may have modest cardiovascular benefits; no interaction.',
 'Gut-heart axis modulation.',
 'Possible complementary health benefits.',
 'Probiotics (10-20 billion CFU) are safe with ACE inhibitors.',
 'limited', 'Emerging research',
 'Probiotics may support cardiovascular health through gut microbiome effects but do not interact with lisinopril.',
 '[{"source": "Research data", "year": "2022"}]'::jsonb),

('INT_LISINOPRIL_MELATONIN', 'D_LISINOPRIL', 'S_MELATONIN', 'pharmacodynamic', 'info',
 'Melatonin has no significant interaction with lisinopril.',
 'No relevant cardiovascular mechanism.',
 'No clinically relevant effects.',
 'Melatonin 1-5mg at bedtime is safe.',
 'limited', 'Minimal interaction',
 'Melatonin supplementation does not interfere with ACE inhibitor therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

-- LOSARTAN INTERACTIONS (ARB - excluding existing magnesium interaction)
('INT_LOSARTAN_POTASSIUM', 'D_LOSARTAN', 'S_POTASSIUM', 'pharmacodynamic', 'avoid',
 'Losartan reduces potassium excretion; supplementation significantly increases hyperkalemia risk.',
 'ARBs block aldosterone effects, reducing renal potassium excretion.',
 'Dangerous hyperkalemia (>5.5 mEq/L), cardiac arrhythmias, muscle weakness.',
 'Avoid potassium supplements unless prescribed. Monitor serum K+ closely if required.',
 'high', 'Established by clinical trials',
 'Losartan and other ARBs reduce aldosterone activity, decreasing renal potassium excretion. Potassium supplementation creates substantial hyperkalemia risk.',
 '[{"source": "Clinical guidelines", "year": "2023"}]'::jsonb),

('INT_LOSARTAN_FISHOIL', 'D_LOSARTAN', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may enhance blood pressure lowering effects of losartan.',
 'Additive vasodilation and prostaglandin-mediated BP reduction.',
 'Enhanced hypotension, dizziness possible.',
 'Monitor BP when starting fish oil. Use standard doses (1-3g EPA/DHA daily).',
 'moderate', 'Supported by research',
 'Omega-3 fatty acids have modest BP-lowering effects. Combined with ARBs, enhanced hypotension may occur.',
 '[{"source": "Meta-analysis", "year": "2022"}]'::jsonb),

('INT_LOSARTAN_GARLIC', 'D_LOSARTAN', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic supplements may enhance blood pressure lowering.',
 'Vasodilation and angiotensin system modulation.',
 'Additive hypotension possible.',
 'Monitor BP when starting garlic. Use aged garlic extract (600-1200mg).',
 'moderate', 'Supported by research',
 'Aged garlic extract reduces BP significantly. Combined with losartan, enhanced hypotension may occur.',
 '[{"source": "Clinical research", "year": "2021"}]'::jsonb),

('INT_LOSARTAN_COENZYME_Q10', 'D_LOSARTAN', 'S_COENZYME_Q10', 'pharmacodynamic', 'monitor',
 'CoQ10 may modestly lower blood pressure; monitor for additive effects.',
 'Mild vasodilation and endothelial function.',
 'Possible enhanced BP lowering.',
 'Monitor BP when starting CoQ10 (100-200mg daily). Generally safe.',
 'moderate', 'Emerging evidence',
 'CoQ10 has modest BP-lowering effects. Usually well-tolerated with ARBs.',
 '[{"source": "Systematic review", "year": "2022"}]'::jsonb),

('INT_LOSARTAN_CALCIUM', 'D_LOSARTAN', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'Calcium supplements do not significantly interact with losartan.',
 'No significant interaction mechanism.',
 'No clinically significant effects.',
 'Take calcium as directed for bone health.',
 'limited', 'Minimal interaction',
 'Calcium supplementation does not interfere with ARB efficacy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_VITAMIN_D', 'D_LOSARTAN', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D may have mild BP benefits; no significant interaction.',
 'Renin-angiotensin system modulation.',
 'Possible complementary benefits.',
 'Maintain adequate vitamin D (1000-2000 IU daily).',
 'moderate', 'Emerging research',
 'Vitamin D may support cardiovascular health alongside ARB therapy.',
 '[{"source": "Observational studies", "year": "2022"}]'::jsonb),

('INT_LOSARTAN_ZINC', 'D_LOSARTAN', 'S_ZINC', 'pharmacokinetic', 'info',
 'No significant interaction between zinc and losartan.',
 'No established mechanism.',
 'No clinically relevant effects.',
 'Take zinc as directed (15-30mg daily).',
 'limited', 'Minimal interaction',
 'Zinc supplementation does not interfere with ARB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_IRON', 'D_LOSARTAN', 'S_IRON', 'pharmacokinetic', 'info',
 'No significant interaction between iron and losartan.',
 'No established mechanism.',
 'No effects expected.',
 'Take iron as directed.',
 'limited', 'Minimal interaction',
 'Iron supplementation does not affect ARB efficacy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_VITAMIN_C', 'D_LOSARTAN', 'S_VITAMIN_C', 'pharmacodynamic', 'info',
 'Vitamin C may have mild cardiovascular benefits; no significant interaction.',
 'Antioxidant and endothelial support.',
 'Possible complementary benefits.',
 'Vitamin C 500-1000mg daily is safe.',
 'limited', 'Minimal interaction',
 'Vitamin C supports endothelial health without interacting with losartan.',
 '[{"source": "Research data", "year": "2021"}]'::jsonb),

('INT_LOSARTAN_VITAMIN_B12', 'D_LOSARTAN', 'S_VITAMIN_B12', 'pharmacokinetic', 'info',
 'No interaction between vitamin B12 and losartan.',
 'No mechanism.',
 'No effects.',
 'Take B12 as directed.',
 'limited', 'No interaction',
 'B12 does not interact with ARBs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_FOLATE', 'D_LOSARTAN', 'S_FOLATE', 'pharmacodynamic', 'info',
 'Folate may support cardiovascular health; no significant interaction.',
 'Homocysteine reduction.',
 'Complementary cardiovascular benefits.',
 'Folate 400-800mcg daily is safe.',
 'moderate', 'Supportive evidence',
 'Folate may support cardiovascular health alongside ARB therapy.',
 '[{"source": "Research data", "year": "2021"}]'::jsonb),

('INT_LOSARTAN_VITAMIN_E', 'D_LOSARTAN', 'S_VITAMIN_E', 'pharmacodynamic', 'info',
 'Vitamin E has no significant interaction with losartan.',
 'Antioxidant without BP impact.',
 'No clinically relevant interaction.',
 'Standard vitamin E doses (400 IU) are safe.',
 'limited', 'Minimal interaction',
 'Vitamin E does not interfere with ARB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_HAWTHORN', 'D_LOSARTAN', 'S_HAWTHORN', 'pharmacodynamic', 'caution',
 'Hawthorn may enhance blood pressure lowering effects.',
 'Vasodilation and ACE inhibition.',
 'Additive hypotension possible.',
 'Monitor BP closely if combining. Start with low doses.',
 'moderate', 'Clinical concern',
 'Hawthorn has cardiovascular effects that may enhance ARB therapy.',
 '[{"source": "Herbal research", "year": "2021"}]'::jsonb),

('INT_LOSARTAN_GINKGO', 'D_LOSARTAN', 'S_GINKGO', 'pharmacodynamic', 'info',
 'Ginkgo has no significant BP interaction with losartan.',
 'No relevant mechanism.',
 'No clinically significant effects.',
 'Standard ginkgo doses are generally safe.',
 'limited', 'Minimal interaction',
 'Ginkgo does not significantly interact with ARBs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_LOSARTAN_TURMERIC', 'D_LOSARTAN', 'S_TURMERIC', 'pharmacodynamic', 'info',
 'Turmeric has minimal interaction with losartan.',
 'Anti-inflammatory without significant BP impact.',
 'No clinically relevant interaction.',
 'Standard turmeric doses (500-1000mg) are safe.',
 'limited', 'Minimal interaction',
 'Turmeric does not significantly interact with ARB therapy.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_LOSARTAN_PROBIOTICS', 'D_LOSARTAN', 'S_PROBIOTICS', 'pharmacodynamic', 'info',
 'Probiotics may have modest cardiovascular benefits; no interaction.',
 'Gut-heart axis modulation.',
 'Possible complementary benefits.',
 'Probiotics are safe with ARBs.',
 'limited', 'Emerging research',
 'Probiotics may support cardiovascular health without interacting with losartan.',
 '[{"source": "Research data", "year": "2022"}]'::jsonb),

('INT_LOSARTAN_MELATONIN', 'D_LOSARTAN', 'S_MELATONIN', 'pharmacodynamic', 'info',
 'Melatonin has no significant interaction with losartan.',
 'No relevant mechanism.',
 'No effects.',
 'Melatonin 1-5mg at bedtime is safe.',
 'limited', 'Minimal interaction',
 'Melatonin does not interfere with ARB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

-- AMLODIPINE INTERACTIONS (Calcium Channel Blocker)
('INT_AMLODIPINE_MAGNESIUM', 'D_AMLODIPINE', 'S_MAGNESIUM', 'pharmacodynamic', 'monitor',
 'Magnesium may enhance blood pressure lowering effects.',
 'Both block calcium channels; additive vasodilation.',
 'Enhanced hypotension possible.',
 'Monitor BP. Magnesium 200-400mg daily typically safe but watch for dizziness.',
 'moderate', 'Theoretical concern',
 'Magnesium has calcium channel blocking effects. Combined with amlodipine, enhanced hypotension may occur.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_AMLODIPINE_CALCIUM', 'D_AMLODIPINE', 'S_CALCIUM', 'pharmacodynamic', 'info',
 'Calcium supplements do not interfere with amlodipine despite the mechanism name.',
 'CCBs block cellular calcium channels; dietary calcium is different.',
 'No clinically significant interaction.',
 'Take calcium as directed. CCBs block channels, not dietary calcium.',
 'limited', 'Mechanism clarification',
 'Despite the name "calcium channel blocker," dietary calcium does not interfere with amlodipine. The drug blocks cellular channels, not calcium absorption.',
 '[{"source": "Clinical pharmacology", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_VITAMIN_D', 'D_AMLODIPINE', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D has no significant interaction with amlodipine.',
 'No relevant mechanism.',
 'No clinically significant effects.',
 'Maintain adequate vitamin D levels (1000-2000 IU daily).',
 'limited', 'Minimal interaction',
 'Vitamin D supplementation does not interfere with calcium channel blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_COENZYME_Q10', 'D_AMLODIPINE', 'S_COENZYME_Q10', 'pharmacodynamic', 'info',
 'CoQ10 has no significant interaction with amlodipine.',
 'No relevant mechanism.',
 'Possible complementary cardiovascular benefits.',
 'CoQ10 100-200mg daily is safe with CCBs.',
 'limited', 'Minimal interaction',
 'CoQ10 supplementation does not interact with calcium channel blockers.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_AMLODIPINE_FISHOIL', 'D_AMLODIPINE', 'S_FISH_OIL', 'pharmacodynamic', 'monitor',
 'Fish oil may modestly enhance blood pressure lowering.',
 'Additive vasodilation.',
 'Possible enhanced hypotension.',
 'Monitor BP when starting fish oil. Standard doses (1-3g EPA/DHA) typically safe.',
 'moderate', 'Clinical observation',
 'Omega-3 fatty acids have modest BP effects. Usually well-tolerated with amlodipine.',
 '[{"source": "Clinical research", "year": "2022"}]'::jsonb),

('INT_AMLODIPINE_GARLIC', 'D_AMLODIPINE', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may enhance blood pressure lowering effects.',
 'Vasodilation and calcium channel effects.',
 'Additive hypotension possible.',
 'Monitor BP when starting garlic. Use moderate doses (600-1200mg aged garlic).',
 'moderate', 'Clinical concern',
 'Aged garlic extract has significant BP-lowering effects. Enhanced hypotension may occur with amlodipine.',
 '[{"source": "Clinical research", "year": "2021"}]'::jsonb),

('INT_AMLODIPINE_HAWTHORN', 'D_AMLODIPINE', 'S_HAWTHORN', 'pharmacodynamic', 'caution',
 'Hawthorn may enhance blood pressure and heart rate effects.',
 'Calcium channel blocking and vasodilation.',
 'Additive cardiovascular effects.',
 'Monitor BP and heart rate. Use cautiously. Consult provider before combining.',
 'moderate', 'Clinical concern',
 'Hawthorn has calcium channel blocking properties. Combined with amlodipine, enhanced effects may occur.',
 '[{"source": "Herbal pharmacology", "year": "2021"}]'::jsonb),

('INT_AMLODIPINE_GINKGO', 'D_AMLODIPINE', 'S_GINKGO', 'pharmacodynamic', 'info',
 'Ginkgo has no significant interaction with amlodipine.',
 'No relevant BP mechanism.',
 'No clinically significant effects.',
 'Standard ginkgo doses (120-240mg) are safe.',
 'limited', 'Minimal interaction',
 'Ginkgo does not significantly interact with calcium channel blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_TURMERIC', 'D_AMLODIPINE', 'S_TURMERIC', 'pharmacodynamic', 'info',
 'Turmeric has minimal interaction with amlodipine.',
 'Anti-inflammatory without significant cardiovascular impact.',
 'No clinically relevant interaction.',
 'Standard turmeric doses (500-1000mg) are safe.',
 'limited', 'Minimal interaction',
 'Turmeric does not significantly interact with CCBs.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_AMLODIPINE_VITAMIN_C', 'D_AMLODIPINE', 'S_VITAMIN_C', 'pharmacodynamic', 'info',
 'Vitamin C has no significant interaction with amlodipine.',
 'No relevant mechanism.',
 'No effects expected.',
 'Vitamin C 500-1000mg daily is safe.',
 'limited', 'Minimal interaction',
 'Vitamin C does not interfere with calcium channel blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_VITAMIN_E', 'D_AMLODIPINE', 'S_VITAMIN_E', 'pharmacodynamic', 'info',
 'Vitamin E has no significant interaction with amlodipine.',
 'No relevant mechanism.',
 'No effects.',
 'Standard vitamin E doses are safe.',
 'limited', 'Minimal interaction',
 'Vitamin E does not interfere with CCB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_ZINC', 'D_AMLODIPINE', 'S_ZINC', 'pharmacokinetic', 'info',
 'No interaction between zinc and amlodipine.',
 'No mechanism.',
 'No effects.',
 'Take zinc as directed.',
 'limited', 'No interaction',
 'Zinc does not interact with CCBs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_IRON', 'D_AMLODIPINE', 'S_IRON', 'pharmacokinetic', 'info',
 'No interaction between iron and amlodipine.',
 'No mechanism.',
 'No effects.',
 'Take iron as directed.',
 'limited', 'No interaction',
 'Iron does not affect CCB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_AMLODIPINE_MELATONIN', 'D_AMLODIPINE', 'S_MELATONIN', 'pharmacodynamic', 'info',
 'Melatonin has no significant interaction with amlodipine.',
 'No cardiovascular mechanism.',
 'No effects.',
 'Melatonin 1-5mg at bedtime is safe.',
 'limited', 'No interaction',
 'Melatonin does not interfere with CCB therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

-- METOPROLOL INTERACTIONS (Beta Blocker)
('INT_METOPROLOL_COENZYME_Q10', 'D_METOPROLOL', 'S_COENZYME_Q10', 'pharmacokinetic', 'monitor',
 'Beta blockers may deplete CoQ10; supplementation may be beneficial.',
 'Beta blockade reduces CoQ10 synthesis.',
 'Possible fatigue, muscle symptoms; supplementation may help.',
 'Consider CoQ10 100-200mg daily. May improve energy and reduce statin-like symptoms.',
 'moderate', 'Clinical observation',
 'Beta blockers can reduce endogenous CoQ10 production. Supplementation may help with fatigue and muscle symptoms.',
 '[{"source": "Clinical research", "year": "2021"}]'::jsonb),

('INT_METOPROLOL_MAGNESIUM', 'D_METOPROLOL', 'S_MAGNESIUM', 'pharmacodynamic', 'monitor',
 'Magnesium may modestly enhance blood pressure lowering.',
 'Additive cardiovascular effects.',
 'Possible enhanced BP lowering.',
 'Monitor BP. Magnesium 200-400mg daily typically safe.',
 'moderate', 'Well-documented',
 'Magnesium has cardiovascular benefits. Usually well-tolerated with beta blockers but monitor BP.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_METOPROLOL_FISHOIL', 'D_METOPROLOL', 'S_FISH_OIL', 'pharmacodynamic', 'info',
 'Fish oil has no significant interaction with metoprolol.',
 'Complementary cardiovascular benefits.',
 'No adverse interaction; may provide additional benefits.',
 'Fish oil 1-3g EPA/DHA daily is safe and may be beneficial.',
 'moderate', 'Complementary therapy',
 'Omega-3 fatty acids provide cardiovascular benefits without interfering with beta blocker therapy.',
 '[{"source": "Clinical research", "year": "2022"}]'::jsonb),

('INT_METOPROLOL_CALCIUM', 'D_METOPROLOL', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'Calcium has no significant interaction with metoprolol.',
 'No relevant mechanism.',
 'No effects.',
 'Take calcium as directed.',
 'limited', 'No interaction',
 'Calcium supplementation does not interfere with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_VITAMIN_D', 'D_METOPROLOL', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D has no significant interaction with metoprolol.',
 'No relevant mechanism.',
 'Possible complementary cardiovascular benefits.',
 'Maintain adequate vitamin D (1000-2000 IU daily).',
 'limited', 'Minimal interaction',
 'Vitamin D may support cardiovascular health without interacting with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_ZINC', 'D_METOPROLOL', 'S_ZINC', 'pharmacokinetic', 'info',
 'No interaction between zinc and metoprolol.',
 'No mechanism.',
 'No effects.',
 'Take zinc as directed.',
 'limited', 'No interaction',
 'Zinc does not interact with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_IRON', 'D_METOPROLOL', 'S_IRON', 'pharmacokinetic', 'info',
 'No interaction between iron and metoprolol.',
 'No mechanism.',
 'No effects.',
 'Take iron as directed.',
 'limited', 'No interaction',
 'Iron does not affect beta blocker therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_VITAMIN_C', 'D_METOPROLOL', 'S_VITAMIN_C', 'pharmacodynamic', 'info',
 'Vitamin C has no interaction with metoprolol.',
 'Antioxidant support.',
 'No adverse effects.',
 'Vitamin C 500-1000mg daily is safe.',
 'limited', 'No interaction',
 'Vitamin C does not interfere with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_VITAMIN_B12', 'D_METOPROLOL', 'S_VITAMIN_B12', 'pharmacokinetic', 'info',
 'No interaction between B12 and metoprolol.',
 'No mechanism.',
 'No effects.',
 'Take B12 as directed.',
 'limited', 'No interaction',
 'B12 does not interact with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_FOLATE', 'D_METOPROLOL', 'S_FOLATE', 'pharmacodynamic', 'info',
 'Folate may support cardiovascular health; no interaction.',
 'Homocysteine reduction.',
 'Complementary benefits.',
 'Folate 400-800mcg daily is safe.',
 'moderate', 'Supportive',
 'Folate supports cardiovascular health without interacting with metoprolol.',
 '[{"source": "Research data", "year": "2021"}]'::jsonb),

('INT_METOPROLOL_VITAMIN_E', 'D_METOPROLOL', 'S_VITAMIN_E', 'pharmacodynamic', 'info',
 'Vitamin E has no interaction with metoprolol.',
 'Antioxidant without cardiovascular impact.',
 'No effects.',
 'Standard vitamin E doses are safe.',
 'limited', 'No interaction',
 'Vitamin E does not interfere with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_HAWTHORN', 'D_METOPROLOL', 'S_HAWTHORN', 'pharmacodynamic', 'caution',
 'Hawthorn may enhance cardiovascular effects.',
 'Additive negative inotropy and chronotropy.',
 'Enhanced heart rate and contractility reduction.',
 'Monitor heart rate and BP. Use cautiously. Consult provider.',
 'moderate', 'Clinical concern',
 'Hawthorn has cardiac effects that may enhance beta blocker therapy. Monitor carefully.',
 '[{"source": "Herbal pharmacology", "year": "2021"}]'::jsonb),

('INT_METOPROLOL_GINKGO', 'D_METOPROLOL', 'S_GINKGO', 'pharmacodynamic', 'info',
 'Ginkgo has no significant interaction with metoprolol.',
 'No relevant mechanism.',
 'No effects.',
 'Standard ginkgo doses are safe.',
 'limited', 'No interaction',
 'Ginkgo does not interact with beta blockers.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_METOPROLOL_TURMERIC', 'D_METOPROLOL', 'S_TURMERIC', 'pharmacodynamic', 'info',
 'Turmeric has no significant interaction with metoprolol.',
 'Anti-inflammatory without cardiovascular impact.',
 'No effects.',
 'Standard turmeric doses are safe.',
 'limited', 'No interaction',
 'Turmeric does not interact with beta blockers.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_METOPROLOL_MELATONIN', 'D_METOPROLOL', 'S_MELATONIN', 'pharmacodynamic', 'info',
 'Melatonin has no significant interaction with metoprolol.',
 'No cardiovascular mechanism.',
 'No effects.',
 'Melatonin 1-5mg at bedtime is safe.',
 'limited', 'No interaction',
 'Melatonin does not interfere with beta blocker therapy.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb)

ON CONFLICT (interaction_id) DO NOTHING;
