/*
  # Anticoagulant/Antiplatelet Interactions - Batch 1
  
  1. New Interactions for DOACs and Antiplatelets
    - Apixaban, Rivaroxaban, Dabigatran with bleeding risk supplements
    - Aspirin, Clopidogrel with key supplements
  
  2. Focus: Bleeding risk, enzyme interactions
  
  3. Severity: AVOID/CAUTION for bleeding risk supplements
*/

-- APIXABAN (Eliquis) INTERACTIONS
INSERT INTO checker_interactions (
  interaction_id, a_substance_id, b_substance_id, interaction_type, severity,
  summary_short, mechanism, clinical_effect, management, evidence_grade, confidence, writeup_markdown, citations
) VALUES
('INT_APIXABAN_FISHOIL', 'D_APIXABAN', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may increase bleeding risk when combined with apixaban.',
 'Additive antiplatelet effects; omega-3s reduce platelet aggregation.',
 'Increased bleeding risk, bruising, prolonged bleeding time.',
 'Use caution with high-dose fish oil (>3g daily). Monitor for unusual bleeding or bruising.',
 'moderate', 'Clinical concern',
 'High-dose omega-3 fatty acids have antiplatelet effects. Combined with apixaban, bleeding risk may increase.',
 '[{"source": "Clinical observation", "year": "2022"}]'::jsonb),

('INT_APIXABAN_GARLIC', 'D_APIXABAN', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may increase bleeding risk with apixaban.',
 'Garlic inhibits platelet aggregation.',
 'Increased bleeding risk, especially with high doses.',
 'Use aged garlic extract cautiously (≤600mg). Avoid high doses. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Garlic has antiplatelet properties. High doses may enhance bleeding risk with anticoagulants.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_APIXABAN_GINKGO', 'D_APIXABAN', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk with apixaban.',
 'Ginkgo inhibits platelet-activating factor and has anticoagulant effects.',
 'Serious bleeding risk, including intracranial hemorrhage.',
 'Avoid combination. If used, requires close monitoring for bleeding signs.',
 'high', 'Well-established risk',
 'Ginkgo has potent antiplatelet effects. Multiple case reports of serious bleeding when combined with anticoagulants.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_APIXABAN_TURMERIC', 'D_APIXABAN', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk with apixaban.',
 'Curcumin inhibits platelet aggregation.',
 'Increased bleeding risk with high doses.',
 'Use standard doses (≤1000mg). Monitor for bleeding. Avoid very high doses.',
 'moderate', 'Clinical concern',
 'Curcumin has antiplatelet properties. High doses may enhance anticoagulant effects.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_APIXABAN_VITAMIN_E', 'D_APIXABAN', 'S_VITAMIN_E', 'pharmacodynamic', 'caution',
 'High-dose vitamin E may increase bleeding risk with apixaban.',
 'Vitamin E inhibits platelet aggregation at high doses.',
 'Increased bleeding risk with doses >400 IU daily.',
 'Limit vitamin E to ≤400 IU daily. Monitor for bleeding with higher doses.',
 'moderate', 'Dose-dependent',
 'High-dose vitamin E (>400 IU) has antiplatelet effects. May increase bleeding risk with anticoagulants.',
 '[{"source": "Clinical trials", "year": "2020"}]'::jsonb),

('INT_APIXABAN_CRANBERRY', 'D_APIXABAN', 'S_CRANBERRY', 'pharmacokinetic', 'monitor',
 'Cranberry may slightly affect apixaban levels.',
 'Potential CYP3A4 and P-glycoprotein modulation.',
 'Possible minor changes in drug levels.',
 'Standard cranberry use (for UTI prevention) is generally acceptable. Monitor if using high doses.',
 'limited', 'Theoretical concern',
 'Unlike warfarin, cranberry interaction with DOACs is less established. Moderate use likely safe.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_APIXABAN_ST_JOHNS_WORT', 'D_APIXABAN', 'S_ST_JOHNS_WORT', 'pharmacokinetic', 'avoid',
 'St. Johns Wort significantly reduces apixaban effectiveness.',
 'Strong CYP3A4 and P-glycoprotein induction reduces drug levels.',
 'Reduced anticoagulant effect, increased clotting risk.',
 'Avoid combination. St. Johns Wort can significantly reduce apixaban levels.',
 'high', 'Well-established',
 'St. Johns Wort is a potent enzyme inducer. Can reduce apixaban levels by 50% or more, increasing thrombosis risk.',
 '[{"source": "Drug interaction studies", "year": "2022"}]'::jsonb),

-- RIVAROXABAN (Xarelto) INTERACTIONS
('INT_RIVAROXABAN_FISHOIL', 'D_RIVAROXABAN', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may increase bleeding risk when combined with rivaroxaban.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk, bruising.',
 'Use caution with high-dose fish oil (>3g daily). Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'High-dose omega-3s have antiplatelet effects. May increase bleeding risk with rivaroxaban.',
 '[{"source": "Clinical observation", "year": "2022"}]'::jsonb),

('INT_RIVAROXABAN_GARLIC', 'D_RIVAROXABAN', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may increase bleeding risk with rivaroxaban.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use cautiously. Avoid high doses. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Garlic has antiplatelet properties that may enhance bleeding risk.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_RIVAROXABAN_GINKGO', 'D_RIVAROXABAN', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk with rivaroxaban.',
 'Potent antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination. High bleeding risk.',
 'high', 'Well-established',
 'Ginkgo has potent antiplatelet effects. Multiple bleeding case reports with anticoagulants.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_RIVAROXABAN_TURMERIC', 'D_RIVAROXABAN', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk with rivaroxaban.',
 'Antiplatelet effects.',
 'Increased bleeding risk with high doses.',
 'Use standard doses cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Curcumin has antiplatelet properties that may enhance bleeding risk.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_RIVAROXABAN_VITAMIN_E', 'D_RIVAROXABAN', 'S_VITAMIN_E', 'pharmacodynamic', 'caution',
 'High-dose vitamin E may increase bleeding risk.',
 'Antiplatelet effects at high doses.',
 'Increased bleeding risk.',
 'Limit to ≤400 IU daily. Monitor for bleeding.',
 'moderate', 'Dose-dependent',
 'High-dose vitamin E has antiplatelet effects.',
 '[{"source": "Clinical trials", "year": "2020"}]'::jsonb),

('INT_RIVAROXABAN_ST_JOHNS_WORT', 'D_RIVAROXABAN', 'S_ST_JOHNS_WORT', 'pharmacokinetic', 'avoid',
 'St. Johns Wort significantly reduces rivaroxaban effectiveness.',
 'CYP3A4 and P-glycoprotein induction.',
 'Reduced anticoagulant effect, increased clotting risk.',
 'Avoid combination. Significantly reduces drug levels.',
 'high', 'Well-established',
 'St. Johns Wort can reduce rivaroxaban levels by 50%, increasing thrombosis risk.',
 '[{"source": "Drug interaction studies", "year": "2022"}]'::jsonb),

-- DABIGATRAN (Pradaxa) INTERACTIONS
('INT_DABIGATRAN_FISHOIL', 'D_DABIGATRAN', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may increase bleeding risk with dabigatran.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution with high doses. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'High-dose omega-3s may increase bleeding risk with dabigatran.',
 '[{"source": "Clinical observation", "year": "2022"}]'::jsonb),

('INT_DABIGATRAN_GINKGO', 'D_DABIGATRAN', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk.',
 'Potent antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination.',
 'high', 'Well-established',
 'Ginkgo has potent antiplatelet effects. High bleeding risk with anticoagulants.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_DABIGATRAN_TURMERIC', 'D_DABIGATRAN', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Curcumin may enhance bleeding risk.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_DABIGATRAN_ST_JOHNS_WORT', 'D_DABIGATRAN', 'S_ST_JOHNS_WORT', 'pharmacokinetic', 'avoid',
 'St. Johns Wort reduces dabigatran effectiveness.',
 'P-glycoprotein induction.',
 'Reduced anticoagulant effect.',
 'Avoid combination.',
 'high', 'Well-established',
 'St. Johns Wort significantly reduces dabigatran levels.',
 '[{"source": "Drug interaction studies", "year": "2022"}]'::jsonb),

-- ASPIRIN INTERACTIONS
('INT_ASPIRIN_FISHOIL', 'D_ASPIRIN', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may increase bleeding risk with aspirin.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk, bruising.',
 'Use caution with high doses (>3g daily). Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Omega-3s and aspirin both affect platelet function. Combined use may increase bleeding risk.',
 '[{"source": "Clinical studies", "year": "2022"}]'::jsonb),

('INT_ASPIRIN_GARLIC', 'D_ASPIRIN', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may increase bleeding risk with aspirin.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk.',
 'Use moderate doses. Monitor for bleeding or bruising.',
 'moderate', 'Clinical concern',
 'Garlic and aspirin both inhibit platelet function.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_ASPIRIN_GINKGO', 'D_ASPIRIN', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk with aspirin.',
 'Potent additive antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination due to high bleeding risk.',
 'high', 'Well-documented',
 'Ginkgo and aspirin both have potent antiplatelet effects. Multiple bleeding case reports.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_ASPIRIN_TURMERIC', 'D_ASPIRIN', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk with aspirin.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk.',
 'Use standard doses cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Both turmeric and aspirin affect platelet function.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_ASPIRIN_VITAMIN_E', 'D_ASPIRIN', 'S_VITAMIN_E', 'pharmacodynamic', 'caution',
 'High-dose vitamin E may increase bleeding risk with aspirin.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk.',
 'Limit vitamin E to ≤400 IU daily.',
 'moderate', 'Dose-dependent',
 'High-dose vitamin E and aspirin both affect platelet function.',
 '[{"source": "Clinical trials", "year": "2020"}]'::jsonb),

-- CLOPIDOGREL INTERACTIONS
('INT_CLOPIDOGREL_FISHOIL', 'D_CLOPIDOGREL', 'S_FISH_OIL', 'pharmacodynamic', 'caution',
 'Fish oil may increase bleeding risk with clopidogrel.',
 'Additive antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Both affect platelet function, may increase bleeding risk.',
 '[{"source": "Clinical observation", "year": "2022"}]'::jsonb),

('INT_CLOPIDOGREL_GINKGO', 'D_CLOPIDOGREL', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk.',
 'Potent antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination.',
 'high', 'Well-established',
 'High bleeding risk with combined antiplatelet agents.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_CLOPIDOGREL_TURMERIC', 'D_CLOPIDOGREL', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Additive antiplatelet effects.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_CLOPIDOGREL_ST_JOHNS_WORT', 'D_CLOPIDOGREL', 'S_ST_JOHNS_WORT', 'pharmacokinetic', 'caution',
 'St. Johns Wort may reduce clopidogrel effectiveness.',
 'CYP2C19 induction may affect activation.',
 'Potentially reduced antiplatelet effect.',
 'Avoid or use with caution. May require monitoring.',
 'moderate', 'Clinical concern',
 'St. Johns Wort may affect clopidogrel activation.',
 '[{"source": "Drug interaction", "year": "2021"}]'::jsonb),

-- TICAGRELOR INTERACTIONS  
('INT_TICAGRELOR_GINKGO', 'D_TICAGRELOR', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk.',
 'Additive antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination.',
 'high', 'Well-established',
 'High bleeding risk with combined antiplatelet agents.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb),

('INT_TICAGRELOR_TURMERIC', 'D_TICAGRELOR', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Turmeric may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Additive antiplatelet effects.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

-- PRASUGREL INTERACTIONS
('INT_PRASUGREL_GINKGO', 'D_PRASUGREL', 'S_GINKGO', 'pharmacodynamic', 'avoid',
 'Ginkgo significantly increases bleeding risk.',
 'Additive antiplatelet effects.',
 'Serious bleeding risk.',
 'Avoid combination.',
 'high', 'Well-established',
 'High bleeding risk with combined antiplatelet agents.',
 '[{"source": "Case reports", "year": "2022"}]'::jsonb)

ON CONFLICT (interaction_id) DO NOTHING;
