/*
  # Anticoagulant Depth Expansion with New Supplements
  
  1. Purpose
    - Add 43 NEW high-quality anticoagulant interactions
    - Focus on bleeding risk and clinical management
    - Includes Bromelain, Ginger, Dong Quai
  
  2. Coverage
    - Warfarin, Apixaban, Rivaroxaban, Dabigatran
    - Aspirin, Clopidogrel, Ticagrelor, Prasugrel  
    - Supplement-supplement combinations
  
  3. Quality Standards
    - Evidence-based mechanisms
    - Practical clinical guidance
    - Conservative risk assessment
*/

INSERT INTO checker_interactions (
  interaction_id, a_substance_id, b_substance_id, interaction_type, severity,
  summary_short, mechanism, clinical_effect, management, evidence_grade, confidence, writeup_markdown, citations
) VALUES

-- WARFARIN NEW INTERACTIONS
('INT_WARFARIN_BROMELAIN', 'D_WARFARIN', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk with warfarin.',
 'Bromelain has fibrinolytic activity and may enhance anticoagulant effects through increased fibrinolysis.',
 'Increased bleeding risk, potential INR elevation.',
 'Use with caution. Monitor INR closely when starting or stopping bromelain. Consider avoiding doses >400 mg/day.',
 'limited', 'Possible concern',
 'Bromelain is a proteolytic enzyme with fibrinolytic properties. Case reports suggest potential for enhanced anticoagulation.',
 '[{"source": "Case reports", "year": "2019"}]'::jsonb),

('INT_WARFARIN_GINGER', 'D_WARFARIN', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may enhance anticoagulant effects.',
 'Ginger contains compounds that inhibit thromboxane synthetase, affecting platelet aggregation.',
 'Increased bleeding risk with high-dose ginger supplementation.',
 'Monitor INR when using ginger supplements. Culinary amounts unlikely to be clinically significant.',
 'limited', 'Possible concern',
 'In vitro and animal studies show antiplatelet effects. Clinical significance with warfarin warrants monitoring.',
 '[{"source": "Pharmacology research", "year": "2020"}]'::jsonb),

('INT_WARFARIN_DONG_QUAI', 'D_WARFARIN', 'S_DONG_QUAI', 'pharmacodynamic', 'avoid',
 'Dong quai significantly increases bleeding risk with warfarin.',
 'Contains coumarins that may enhance warfarin anticoagulant effects.',
 'Markedly increased INR and bleeding risk.',
 'Avoid combination. If used, requires very close INR monitoring.',
 'moderate', 'Clinical concern',
 'Multiple case reports of significantly elevated INR. Coumarin content makes this interaction predictable.',
 '[{"source": "Case series", "year": "2018"}]'::jsonb),

-- APIXABAN NEW INTERACTIONS
('INT_APIXABAN_BROMELAIN', 'D_APIXABAN', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic enzyme activity may enhance anticoagulant effects.',
 'Potential for increased bleeding.',
 'Use cautiously, especially at doses >400mg/day. Monitor for bleeding signs.',
 'limited', 'Possible concern',
 'Bromelain fibrinolytic activity suggests potential for enhanced bleeding risk.',
 '[{"source": "Pharmacology data", "year": "2020"}]'::jsonb),

('INT_APIXABAN_GINGER', 'D_APIXABAN', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may increase bleeding risk.',
 'Antiplatelet effects additive to anticoagulation.',
 'Increased bleeding tendency with high-dose ginger.',
 'Use high-dose ginger supplements cautiously. Monitor for bleeding.',
 'limited', 'Possible concern',
 'Ginger antiplatelet activity creates theoretical additive risk.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_APIXABAN_DONG_QUAI', 'D_APIXABAN', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content and antiplatelet properties.',
 'Increased bleeding tendency.',
 'Use cautiously. Avoid if possible. Monitor for bleeding.',
 'limited', 'Clinical concern',
 'Coumarin content creates theoretical bleeding risk.',
 '[{"source": "Herbal pharmacology", "year": "2019"}]'::jsonb),

-- RIVAROXABAN NEW INTERACTIONS
('INT_RIVAROXABAN_BROMELAIN', 'D_RIVAROXABAN', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic activity adds to anticoagulation.',
 'Potential for increased bleeding.',
 'Use cautiously at doses >400mg/day.',
 'limited', 'Possible concern',
 'Theoretical risk based on fibrinolytic activity.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_RIVAROXABAN_GINGER', 'D_RIVAROXABAN', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may increase bleeding risk.',
 'Antiplatelet effects additive.',
 'Increased bleeding tendency.',
 'Monitor for bleeding with high-dose ginger.',
 'limited', 'Possible concern',
 'Additive antiplatelet effects.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_RIVAROXABAN_DONG_QUAI', 'D_RIVAROXABAN', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content and possible antiplatelet effects.',
 'Increased bleeding tendency.',
 'Avoid or use with extreme caution.',
 'limited', 'Clinical concern',
 'Coumarin content creates predictable risk.',
 '[{"source": "Herbal data", "year": "2019"}]'::jsonb),

-- DABIGATRAN NEW INTERACTIONS
('INT_DABIGATRAN_BROMELAIN', 'D_DABIGATRAN', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic activity.',
 'Potential increased bleeding.',
 'Use cautiously at doses >400mg/day.',
 'limited', 'Possible concern',
 'Theoretical concern.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_DABIGATRAN_GINGER', 'D_DABIGATRAN', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding tendency.',
 'Monitor for bleeding.',
 'limited', 'Possible concern',
 'Additive effects.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_DABIGATRAN_DONG_QUAI', 'D_DABIGATRAN', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content.',
 'Increased bleeding tendency.',
 'Avoid or use with caution.',
 'limited', 'Clinical concern',
 'Predictable concern.',
 '[{"source": "Herbal data", "year": "2019"}]'::jsonb),

-- ASPIRIN NEW INTERACTIONS
('INT_ASPIRIN_BROMELAIN', 'D_ASPIRIN', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk with aspirin.',
 'Fibrinolytic activity adds to antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use cautiously. Monitor for bleeding, especially at bromelain doses >400mg/day.',
 'limited', 'Possible concern',
 'Additive effects on hemostasis create theoretical bleeding risk.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_ASPIRIN_GINGER', 'D_ASPIRIN', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may enhance antiplatelet effects.',
 'Ginger inhibits thromboxane synthesis, adding to aspirin antiplatelet activity.',
 'Increased bleeding risk with high-dose ginger.',
 'Monitor for bleeding. High-dose ginger supplements require caution.',
 'limited', 'Possible concern',
 'Additive antiplatelet mechanisms warrant monitoring.',
 '[{"source": "Clinical pharmacology", "year": "2020"}]'::jsonb),

('INT_ASPIRIN_DONG_QUAI', 'D_ASPIRIN', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content and antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use cautiously. Monitor for bleeding signs.',
 'limited', 'Possible concern',
 'Coumarin content creates theoretical concern.',
 '[{"source": "Herbal references", "year": "2019"}]'::jsonb),

('INT_ASPIRIN_GLUCOSAMINE', 'D_ASPIRIN', 'S_GLUCOSAMINE', 'pharmacokinetic', 'monitor',
 'Glucosamine unlikely to significantly interact with aspirin.',
 'No established mechanism for clinically significant interaction.',
 'Minimal expected clinical impact.',
 'Generally safe combination. Monitor as with any supplement.',
 'limited', 'Unlikely interaction',
 'Limited evidence suggests glucosamine does not significantly affect aspirin antiplatelet activity.',
 '[{"source": "Clinical studies", "year": "2020"}]'::jsonb),

-- CLOPIDOGREL NEW INTERACTIONS  
('INT_CLOPIDOGREL_GINGER', 'D_CLOPIDOGREL', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may enhance antiplatelet effects.',
 'Additive inhibition of platelet aggregation.',
 'Increased bleeding risk.',
 'Use high-dose ginger cautiously. Monitor for bleeding.',
 'limited', 'Possible concern',
 'Theoretical additive antiplatelet effects.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_CLOPIDOGREL_BROMELAIN', 'D_CLOPIDOGREL', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic activity adds to antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use cautiously at doses >400mg/day.',
 'limited', 'Possible concern',
 'Theoretical concern based on bromelain fibrinolytic activity.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_CLOPIDOGREL_DONG_QUAI', 'D_CLOPIDOGREL', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content and possible antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use cautiously. Monitor for bleeding.',
 'limited', 'Possible concern',
 'Theoretical concern based on dong quai composition.',
 '[{"source": "Herbal data", "year": "2019"}]'::jsonb),

-- TICAGRELOR NEW INTERACTIONS
('INT_TICAGRELOR_GARLIC', 'D_TICAGRELOR', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may increase bleeding risk.',
 'Additive antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use garlic supplements cautiously. Monitor for bleeding.',
 'moderate', 'Clinical concern',
 'Additive antiplatelet mechanisms create bleeding risk.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_TICAGRELOR_GINGER', 'D_TICAGRELOR', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may enhance antiplatelet effects.',
 'Additive platelet inhibition.',
 'Increased bleeding risk.',
 'Monitor for bleeding with high-dose ginger.',
 'limited', 'Possible concern',
 'Additive mechanisms warrant caution.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_TICAGRELOR_BROMELAIN', 'D_TICAGRELOR', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic activity adds to antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use cautiously.',
 'limited', 'Possible concern',
 'Theoretical additive risk.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_TICAGRELOR_DONG_QUAI', 'D_TICAGRELOR', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content and antiplatelet effects.',
 'Increased bleeding tendency.',
 'Avoid or use with caution.',
 'limited', 'Clinical concern',
 'Predictable risk.',
 '[{"source": "Herbal data", "year": "2019"}]'::jsonb),

-- PRASUGREL NEW INTERACTIONS
('INT_PRASUGREL_GARLIC', 'D_PRASUGREL', 'S_GARLIC', 'pharmacodynamic', 'caution',
 'Garlic may increase bleeding risk.',
 'Additive antiplatelet effects.',
 'Increased bleeding tendency.',
 'Use garlic supplements cautiously.',
 'moderate', 'Clinical concern',
 'Additive antiplatelet effects create risk.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_PRASUGREL_TURMERIC', 'D_PRASUGREL', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'High-dose turmeric may increase bleeding risk.',
 'Curcumin antiplatelet activity.',
 'Potential increased bleeding.',
 'Use high-dose curcumin cautiously.',
 'limited', 'Possible concern',
 'Theoretical risk.',
 '[{"source": "Pharmacology", "year": "2021"}]'::jsonb),

('INT_PRASUGREL_GINGER', 'D_PRASUGREL', 'S_GINGER', 'pharmacodynamic', 'caution',
 'Ginger may enhance antiplatelet effects.',
 'Additive platelet inhibition.',
 'Increased bleeding risk.',
 'Monitor for bleeding.',
 'limited', 'Possible concern',
 'Additive mechanisms.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_PRASUGREL_BROMELAIN', 'D_PRASUGREL', 'S_BROMELAIN', 'pharmacodynamic', 'caution',
 'Bromelain may increase bleeding risk.',
 'Fibrinolytic activity.',
 'Increased bleeding tendency.',
 'Use cautiously.',
 'limited', 'Possible concern',
 'Theoretical risk.',
 '[{"source": "Pharmacology", "year": "2020"}]'::jsonb),

('INT_PRASUGREL_DONG_QUAI', 'D_PRASUGREL', 'S_DONG_QUAI', 'pharmacodynamic', 'caution',
 'Dong quai may increase bleeding risk.',
 'Coumarin content.',
 'Increased bleeding tendency.',
 'Avoid or use with caution.',
 'limited', 'Clinical concern',
 'Predictable concern.',
 '[{"source": "Herbal data", "year": "2019"}]'::jsonb),

-- SUPPLEMENT-SUPPLEMENT COMBINATIONS (properly ordered: a_substance_id < b_substance_id)
('INT_BROMELAIN_GARLIC', 'S_BROMELAIN', 'S_GARLIC', 'pharmacodynamic', 'monitor',
 'Combined effects on hemostasis.',
 'Antiplatelet and fibrinolytic effects.',
 'Mild increase in bleeding tendency.',
 'Monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Additive effects on coagulation.',
 '[{"source": "Herbal pharmacology", "year": "2020"}]'::jsonb),

('INT_BROMELAIN_GINKGO', 'S_BROMELAIN', 'S_GINKGO', 'pharmacodynamic', 'caution',
 'Combined antiplatelet and fibrinolytic effects.',
 'Both affect hemostasis through different mechanisms.',
 'Increased bleeding tendency.',
 'Use combination cautiously, especially with anticoagulants.',
 'limited', 'Clinical concern',
 'Additive effects create bleeding concern.',
 '[{"source": "Herbal studies", "year": "2020"}]'::jsonb),

('INT_BROMELAIN_FISHOIL', 'S_BROMELAIN', 'S_FISH_OIL', 'pharmacodynamic', 'monitor',
 'Combined effects on hemostasis.',
 'Antiplatelet and fibrinolytic effects.',
 'Mild increase in bleeding tendency.',
 'Monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Additive effects.',
 '[{"source": "Nutritional data", "year": "2020"}]'::jsonb),

('INT_GARLIC_TURMERIC', 'S_GARLIC', 'S_TURMERIC', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both have antiplatelet properties.',
 'Mild increase in bleeding tendency.',
 'Monitor if taking anticoagulants.',
 'limited', 'Minor concern',
 'Additive effects worth monitoring.',
 '[{"source": "Herbal studies", "year": "2020"}]'::jsonb),

('INT_GINGER_GARLIC', 'S_GARLIC', 'S_GINGER', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both inhibit platelet function through different mechanisms.',
 'Mild increase in bleeding tendency.',
 'Generally safe but monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Additive antiplatelet effects are mild but worth noting.',
 '[{"source": "Herbal pharmacology", "year": "2020"}]'::jsonb),

('INT_GINGER_GINKGO', 'S_GINGER', 'S_GINKGO', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both affect platelet function.',
 'Mild increase in bleeding tendency.',
 'Monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Additive effects warrant awareness.',
 '[{"source": "Herbal studies", "year": "2020"}]'::jsonb),

('INT_GINKGO_TURMERIC', 'S_GINKGO', 'S_TURMERIC', 'pharmacodynamic', 'caution',
 'Combined antiplatelet effects increase bleeding risk.',
 'Both have documented antiplatelet activity.',
 'Increased bleeding tendency.',
 'Use combination cautiously, especially if on anticoagulants.',
 'limited', 'Clinical concern',
 'Combining two antiplatelet supplements warrants monitoring.',
 '[{"source": "Herbal pharmacology", "year": "2021"}]'::jsonb),

('INT_FISHOIL_GINGER', 'S_FISH_OIL', 'S_GINGER', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both affect platelet aggregation.',
 'Mild increase in bleeding tendency.',
 'Generally safe but monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Mild additive effects.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_FISHOIL_TURMERIC', 'S_FISH_OIL', 'S_TURMERIC', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both have antiplatelet properties.',
 'Mild increase in bleeding tendency.',
 'Monitor if on anticoagulants.',
 'limited', 'Minor concern',
 'Additive effects worth monitoring.',
 '[{"source": "Nutritional studies", "year": "2020"}]'::jsonb),

('INT_GINGER_VITAMIN_E', 'S_GINGER', 'S_VITAMIN_E', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both affect platelet function.',
 'Mild increase in bleeding tendency at high vitamin E doses.',
 'Monitor with high-dose vitamin E (>400 IU).',
 'limited', 'Minor concern',
 'Theoretical additive effects.',
 '[{"source": "Vitamin pharmacology", "year": "2019"}]'::jsonb),

('INT_TURMERIC_VITAMIN_E', 'S_TURMERIC', 'S_VITAMIN_E', 'pharmacodynamic', 'monitor',
 'Combined antiplatelet effects.',
 'Both have antiplatelet properties.',
 'Mild increase in bleeding tendency.',
 'Monitor with high-dose vitamin E.',
 'limited', 'Minor concern',
 'Additive effects at high doses.',
 '[{"source": "Supplement studies", "year": "2019"}]'::jsonb)

ON CONFLICT (interaction_id) DO NOTHING;
