/*
  # Expansion Batch - Common Supplements with Multiple Medications (V2 - No Duplicates)
  
  1. Add missing common supplement interactions across medications
  2. Focus on common supplements with various meds
  
  3. These are high-search, credible interactions users expect
*/

INSERT INTO checker_interactions (
  interaction_id, a_substance_id, b_substance_id, interaction_type, severity,
  summary_short, mechanism, clinical_effect, management, evidence_grade, confidence, writeup_markdown, citations
) VALUES
-- WARFARIN ADDITIONAL (skip CoQ10 and Omega3 - already exist)
('INT_WARFARIN_CRANBERRY', 'D_WARFARIN', 'S_CRANBERRY', 'pharmacodynamic', 'caution',
 'Cranberry may increase warfarin effects and bleeding risk.',
 'Possible CYP2C9 inhibition affecting warfarin metabolism.',
 'Increased INR, increased bleeding risk.',
 'Use cranberry cautiously. Monitor INR closely if using cranberry products.',
 'moderate', 'Clinical concern',
 'Several case reports of increased INR with cranberry juice and warfarin. Mechanism unclear but clinically relevant.',
 '[{"source": "Case reports", "year": "2021"}]'::jsonb),

-- COMMON SUPPLEMENT INTERACTIONS WITH PSYCHIATRIC MEDS
('INT_PAROXETINE_MAGNESIUM', 'D_PAROXETINE', 'S_MAGNESIUM', 'pharmacodynamic', 'info',
 'No significant interaction between paroxetine and magnesium.',
 'No established mechanism.',
 'No clinically relevant effects.',
 'Magnesium supplementation is safe with SSRIs.',
 'limited', 'No interaction',
 'Magnesium does not affect serotonin systems or SSRI metabolism.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_VENLAFAXINE_MAGNESIUM', 'D_VENLAFAXINE', 'S_MAGNESIUM', 'pharmacodynamic', 'info',
 'No significant interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Magnesium does not affect SNRIs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_DULOXETINE_MAGNESIUM', 'D_DULOXETINE', 'S_MAGNESIUM', 'pharmacodynamic', 'info',
 'No significant interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Magnesium safe with SNRIs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_BUPROPION_MAGNESIUM', 'D_BUPROPION', 'S_MAGNESIUM', 'pharmacodynamic', 'info',
 'No significant interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Magnesium safe with bupropion.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_APIXABAN_OMEGA3', 'D_APIXABAN', 'S_OMEGA3', 'pharmacodynamic', 'caution',
 'Omega-3 may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution with high doses.',
 'moderate', 'Clinical concern',
 'Omega-3s may enhance bleeding.',
 '[{"source": "Clinical data", "year": "2022"}]'::jsonb),

('INT_RIVAROXABAN_OMEGA3', 'D_RIVAROXABAN', 'S_OMEGA3', 'pharmacodynamic', 'caution',
 'Omega-3 may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution with high doses.',
 'moderate', 'Clinical concern',
 'Omega-3s may enhance bleeding.',
 '[{"source": "Clinical data", "year": "2022"}]'::jsonb),

('INT_DABIGATRAN_OMEGA3', 'D_DABIGATRAN', 'S_OMEGA3', 'pharmacodynamic', 'caution',
 'Omega-3 may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution.',
 'moderate', 'Clinical concern',
 'Omega-3s may enhance bleeding.',
 '[{"source": "Clinical data", "year": "2022"}]'::jsonb),

('INT_ASPIRIN_OMEGA3', 'D_ASPIRIN', 'S_OMEGA3', 'pharmacodynamic', 'caution',
 'Omega-3 may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution.',
 'moderate', 'Clinical concern',
 'Both affect platelet function.',
 '[{"source": "Clinical data", "year": "2022"}]'::jsonb),

('INT_CLOPIDOGREL_OMEGA3', 'D_CLOPIDOGREL', 'S_OMEGA3', 'pharmacodynamic', 'caution',
 'Omega-3 may increase bleeding risk.',
 'Antiplatelet effects.',
 'Increased bleeding risk.',
 'Use caution.',
 'moderate', 'Clinical concern',
 'Both affect platelets.',
 '[{"source": "Clinical data", "year": "2022"}]'::jsonb),

-- PROBIOTIC INTERACTIONS
('INT_PAROXETINE_PROBIOTICS', 'D_PAROXETINE', 'S_PROBIOTICS', 'pharmacodynamic', 'info',
 'Probiotics may support gut-brain health.',
 'Gut-brain axis modulation.',
 'Possible complementary mood benefits.',
 'Probiotics are safe with SSRIs.',
 'limited', 'Complementary',
 'Probiotics may support mental health.',
 '[{"source": "Research data", "year": "2022"}]'::jsonb),

('INT_VENLAFAXINE_PROBIOTICS', 'D_VENLAFAXINE', 'S_PROBIOTICS', 'pharmacodynamic', 'info',
 'Probiotics may support gut health.',
 'Gut-brain axis.',
 'Possible benefits.',
 'Safe.',
 'limited', 'Complementary',
 'Probiotics safe with SNRIs.',
 '[{"source": "Research data", "year": "2022"}]'::jsonb),

('INT_DULOXETINE_PROBIOTICS', 'D_DULOXETINE', 'S_PROBIOTICS', 'pharmacodynamic', 'info',
 'Probiotics may support gut health.',
 'Gut-brain axis.',
 'Possible benefits.',
 'Safe.',
 'limited', 'Complementary',
 'Probiotics safe.',
 '[{"source": "Research data", "year": "2022"}]'::jsonb),

('INT_APIXABAN_PROBIOTICS', 'D_APIXABAN', 'S_PROBIOTICS', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Probiotics safe with anticoagulants.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_ASPIRIN_PROBIOTICS', 'D_ASPIRIN', 'S_PROBIOTICS', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Probiotics safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

-- CALCIUM INTERACTIONS
('INT_PAROXETINE_CALCIUM', 'D_PAROXETINE', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Calcium safe with SSRIs.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_VENLAFAXINE_CALCIUM', 'D_VENLAFAXINE', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Calcium safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_DULOXETINE_CALCIUM', 'D_DULOXETINE', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Calcium safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_BUPROPION_CALCIUM', 'D_BUPROPION', 'S_CALCIUM', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Calcium safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_BUPROPION_VITAMIN_D', 'D_BUPROPION', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_VENLAFAXINE_VITAMIN_D', 'D_VENLAFAXINE', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D may support mood.',
 'Mood modulation.',
 'Possible benefits.',
 'Safe and may be beneficial.',
 'moderate', 'Supportive',
 'Vitamin D supports mood.',
 '[{"source": "Clinical studies", "year": "2021"}]'::jsonb),

('INT_DULOXETINE_VITAMIN_D', 'D_DULOXETINE', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D may support mood.',
 'Mood modulation.',
 'Possible benefits.',
 'Safe.',
 'moderate', 'Supportive',
 'Vitamin D supports mood.',
 '[{"source": "Clinical studies", "year": "2021"}]'::jsonb),

('INT_APIXABAN_VITAMIN_D', 'D_APIXABAN', 'S_VITAMIN_D', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_RIVAROXABAN_VITAMIN_D', 'D_RIVAROXABAN', 'S_VITAMIN_D', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_DABIGATRAN_VITAMIN_D', 'D_DABIGATRAN', 'S_VITAMIN_D', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_ASPIRIN_VITAMIN_D', 'D_ASPIRIN', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_CLOPIDOGREL_VITAMIN_D', 'D_CLOPIDOGREL', 'S_VITAMIN_D', 'pharmacokinetic', 'info',
 'No interaction.',
 'No mechanism.',
 'No effects.',
 'Safe.',
 'limited', 'No interaction',
 'Vitamin D safe.',
 '[{"source": "Clinical data", "year": "2020"}]'::jsonb),

('INT_GLIPIZIDE_ALPHA_LIPOIC_ACID', 'D_GLIPIZIDE', 'S_ALPHA_LIPOIC_ACID', 'pharmacodynamic', 'monitor',
 'ALA may enhance glucose lowering.',
 'Improves insulin sensitivity.',
 'Possible increased hypoglycemia risk.',
 'Monitor blood glucose.',
 'moderate', 'Clinical observation',
 'ALA may enhance sulfonylurea effects.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_GLYBURIDE_ALPHA_LIPOIC_ACID', 'D_GLYBURIDE', 'S_ALPHA_LIPOIC_ACID', 'pharmacodynamic', 'monitor',
 'ALA may enhance glucose lowering.',
 'Improves insulin sensitivity.',
 'Possible increased hypoglycemia risk.',
 'Monitor blood glucose.',
 'moderate', 'Clinical observation',
 'ALA may enhance effects.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_GLIMEPIRIDE_ALPHA_LIPOIC_ACID', 'D_GLIMEPIRIDE', 'S_ALPHA_LIPOIC_ACID', 'pharmacodynamic', 'monitor',
 'ALA may enhance glucose lowering.',
 'Improves insulin sensitivity.',
 'Possible increased hypoglycemia risk.',
 'Monitor blood glucose.',
 'moderate', 'Clinical observation',
 'ALA may enhance effects.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb),

('INT_INSULIN_VITAMIN_D', 'D_INSULIN', 'S_VITAMIN_D', 'pharmacodynamic', 'info',
 'Vitamin D may support glucose metabolism.',
 'Improves insulin sensitivity.',
 'Possible modest benefits.',
 'Vitamin D supplementation may be beneficial.',
 'moderate', 'Supportive',
 'Vitamin D deficiency linked to insulin resistance.',
 '[{"source": "Clinical studies", "year": "2021"}]'::jsonb),

('INT_METFORMIN_ALPHA_LIPOIC_ACID', 'D_METFORMIN', 'S_ALPHA_LIPOIC_ACID', 'pharmacodynamic', 'info',
 'ALA may complement metformin effects.',
 'Both improve insulin sensitivity.',
 'Possible complementary benefits.',
 'Safe combination.',
 'moderate', 'Complementary',
 'ALA and metformin may work synergistically.',
 '[{"source": "Clinical data", "year": "2021"}]'::jsonb)

ON CONFLICT (interaction_id) DO NOTHING;
